<?php
// Prints Go source for the time zone abbreviations PHP's date parser
// knows (timelib's timezonemap.h, as DateTimeZone::listAbbreviations()
// lists it), for internal/pkg/loader/datetime_abbr.go. timelib's
// abbr_search() takes the first entry of an abbreviation, so only that
// one is kept.
//
// Run: php tools/oracle/pkg/datetime_abbr.php > internal/pkg/loader/datetime_abbr.go && gofmt -w internal/pkg/loader/datetime_abbr.go
$abbrs = [];
foreach (\DateTimeZone::listAbbreviations() as $name => $entries) {
    $abbrs[$name] = [$entries[0]['offset'], $entries[0]['dst'] ? 1 : 0];
}
echo "// Code generated by tools/oracle/pkg/datetime_abbr.php from PHP ".PHP_VERSION."'s timelib; DO NOT EDIT.\n\n";
echo "package loader\n\n";
echo "// zoneAbbreviations maps the time zone abbreviations timelib knows\n";
echo "// (lower case) to their UTC offset in seconds and DST flag.\n";
echo "var zoneAbbreviations = map[string]zoneAbbreviation{\n";
foreach ($abbrs as $name => [$offset, $dst]) {
    printf("\t%s: {%d, %d},\n", json_encode((string) $name), $offset, $dst);
}
echo "}\n";
