package plugin

import (
	"strings"
	"testing"

	"github.com/stubbedev/maestro/internal/php"
)

// AutoloadGenerator's protected methods through a subclass: after a dump,
// the file generators reproduce the files maestro wrote.
func TestShimStubs_AutoloadGeneratorInternals(t *testing.T) {
	requirePHP(t)

	p := newEvalProject(t, "commands")

	got := evalPHP(t, p.rt, `
		$io = $vars['io'];
		$composer = \Composer\Factory::create($io, null, true);
		$ag = new class(new \Composer\EventDispatcher\EventDispatcher($composer, $io), $io) extends \Composer\Autoload\AutoloadGenerator {
			public function call(string $method, ...$args) { return $this->$method(...$args); }
		};
		$ag->setRunScripts(false);
		$ag->dump($composer->getConfig(), $composer->getRepositoryManager()->getLocalRepository(), $composer->getPackage(), $composer->getInstallationManager(), 'composer');

		$fs = new \Composer\Util\Filesystem();
		// AutoloadGenerator::dump() works on normalized paths (forward
		// slashes on Windows too).
		$base = $fs->normalizePath(getcwd());
		$vendor = $base.'/vendor';
		$target = $vendor.'/composer';
		preg_match('{ComposerAutoloaderInit([0-9a-f]+)}', file_get_contents($target.'/autoload_real.php'), $m);
		$suffix = $m[1];
		$out = [];
		$out[] = 'static '.var_export($ag->call('getStaticFile', $suffix, $target, $vendor, $base) === file_get_contents($target.'/autoload_static.php'), true);
		$out[] = 'autoload '.var_export($ag->call('getAutoloadFile', "__DIR__ . '/composer'", $suffix) === file_get_contents($vendor.'/autoload.php'), true);
		$real = $ag->call('getAutoloadRealFile', true, false, null, false, '__DIR__', "dirname(__DIR__)", $suffix, false, 'true', false);
		$out[] = 'real '.var_export($real === file_get_contents($target.'/autoload_real.php'), true);
		$out[] = 'path code '.$ag->call('getPathCode', $fs, $base, $vendor, 'src/').' | '.$ag->call('getPathCode', $fs, $base, $vendor, $vendor.'/acme/lib/x.php');

		$root = $composer->getPackage();
		$map = $ag->buildPackageMap($composer->getInstallationManager(), $root, [new \Composer\Package\Package('acme/a', '1.0.0.0', '1.0.0')]);
		$out[] = 'filter '.json_encode(array_keys($ag->call('filterPackageMap', $map, $root)));
		$out[] = 'sort '.implode(',', array_map(function ($i) { return $i[0]->getName(); }, $ag->call('sortPackageMap', $map)));
		$out[] = 'psr-4 '.json_encode($ag->call('parseAutoloadsType', $map, 'psr-4', $root));
		$out[] = 'platform '.var_export($ag->call('getPlatformCheck', $map, 'php-only', []), true);
		$out[] = 'include paths '.var_export($ag->call('getIncludePathsFile', $map, $fs, $base, $vendor, '__DIR__', 'dirname(__DIR__)'), true);
		$out[] = 'files '.json_encode($ag->call('getIncludeFilesFile', ['abc' => $base.'/src/f.php', 'def' => $base.'/src/f.php'], $fs, $base, $vendor, 'V', 'B'));

		$ag->call('validatePackage', $root);
		$bad = new \Composer\Package\Package('acme/bad', '1.0.0.0', '1.0.0');
		$bad->setAutoload(['psr-4' => ['Acme' => 'src/']]);
		try {
			$ag->call('validatePackage', $bad);
		} catch (\InvalidArgumentException $e) {
			$out[] = 'invalid: '.$e->getMessage();
		}

		return $out;
	`, php.ArrayOf("io", p.rt.value(p.out)))

	want := strings.Join([]string{
		"static true",
		"autoload true",
		"real true",
		"path code $baseDir . '/src' | $vendorDir . '/acme/lib/x.php'",
		"filter []",
		"sort acme/a,maestro-test/commands-project",
		`psr-4 {"Project\\":["src\/"]}`,
		"platform NULL",
		"include paths NULL",
		`files "<?php\n\n\/\/ autoload_files.php @generated by Composer\n\n$vendorDir = V;\n$baseDir = B;\n\nreturn array(\n    'abc' => $baseDir . '\/src\/f.php',\n    'def' => $baseDir . '\/src\/f.php',\n);\n"`,
		`invalid: psr-4 namespaces must end with a namespace separator, 'Acme' does not, use 'Acme\'.`,
	}, "\n")
	if g := lines(got); g != want {
		t.Errorf("got\n%s\nwant\n%s\noutput:\n%s", g, want, p.output())
	}
	if !strings.Contains(p.output(), `The following "files" autoload rules are included multiple times`) {
		t.Errorf("no duplicate files warning:\n%s", p.output())
	}
}
