<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\FilterList\FilterListProvider;

class FilterListProviderSet
{
    public function __construct(array $repositories, array $sources)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListProvider\\FilterListProviderSet::__construct() in plugins yet');
    }

    public static function create(\Composer\Policy\PolicyConfig $config, array $repositories, \Composer\Util\HttpDownloader $httpDownloader): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListProvider\\FilterListProviderSet::create() in plugins yet');
    }

    public function getMatchingFilterLists(array $packages, array $configuredLists, bool $ignoreUnreachable = false): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListProvider\\FilterListProviderSet::getMatchingFilterLists() in plugins yet');
    }
}
