<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\FilterList\FilterListProvider;

class UrlSourceFilterListProvider implements \Composer\Repository\FilterListProviderInterface
{
    public function __construct(\Composer\Util\HttpDownloader $httpDownloader, \Composer\FilterList\Source\UrlSource $source)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListProvider\\UrlSourceFilterListProvider::__construct() in plugins yet');
    }

    public function getFilter(array $packageConstraintMap, array $configuredLists): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListProvider\\UrlSourceFilterListProvider::getFilter() in plugins yet');
    }

    public function getFilterLists(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListProvider\\UrlSourceFilterListProvider::getFilterLists() in plugins yet');
    }

    public function hasFilter(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListProvider\\UrlSourceFilterListProvider::hasFilter() in plugins yet');
    }
}
