<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Downloader;

abstract class ArchiveDownloader extends \Composer\Downloader\FileDownloader
{
    protected $cleanupExecuted = [];

    public function cleanup(string $type, \Composer\Package\PackageInterface $package, string $path, ?\Composer\Package\PackageInterface $prevPackage = null): \React\Promise\PromiseInterface
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('downloader.cleanup', [$this, $type, $package, $path, $prevPackage]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\ArchiveDownloader::cleanup() in plugins yet');
    }

    abstract protected function extract(\Composer\Package\PackageInterface $package, string $file, string $path): \React\Promise\PromiseInterface;

    protected function getInstallOperationAppendix(\Composer\Package\PackageInterface $package, string $path): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\ArchiveDownloader::getInstallOperationAppendix() in plugins yet');
    }

    public function install(\Composer\Package\PackageInterface $package, string $path, bool $output = true): \React\Promise\PromiseInterface
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('downloader.install', [$this, $package, $path, $output]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\ArchiveDownloader::install() in plugins yet');
    }

    public function prepare(string $type, \Composer\Package\PackageInterface $package, string $path, ?\Composer\Package\PackageInterface $prevPackage = null): \React\Promise\PromiseInterface
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('downloader.prepare', [$this, $type, $package, $path, $prevPackage]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\ArchiveDownloader::prepare() in plugins yet');
    }
}
