<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Downloader;

class DownloadManager
{
    public function __construct(\Composer\IO\IOInterface $io, bool $preferSource = false, ?\Composer\Util\Filesystem $filesystem = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::__construct() in plugins yet');
    }

    public function cleanup(string $type, \Composer\Package\PackageInterface $package, string $targetDir, ?\Composer\Package\PackageInterface $prevPackage = null): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::cleanup() in plugins yet');
    }

    public function download(\Composer\Package\PackageInterface $package, string $targetDir, ?\Composer\Package\PackageInterface $prevPackage = null): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::download() in plugins yet');
    }

    public function getDownloader(string $type): \Composer\Downloader\DownloaderInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::getDownloader() in plugins yet');
    }

    public function getDownloaderForPackage(\Composer\Package\PackageInterface $package): ?\Composer\Downloader\DownloaderInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::getDownloaderForPackage() in plugins yet');
    }

    public function getDownloaderType(\Composer\Downloader\DownloaderInterface $downloader): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::getDownloaderType() in plugins yet');
    }

    public function install(\Composer\Package\PackageInterface $package, string $targetDir): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::install() in plugins yet');
    }

    public function prepare(string $type, \Composer\Package\PackageInterface $package, string $targetDir, ?\Composer\Package\PackageInterface $prevPackage = null): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::prepare() in plugins yet');
    }

    public function remove(\Composer\Package\PackageInterface $package, string $targetDir): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::remove() in plugins yet');
    }

    protected function resolvePackageInstallPreference(\Composer\Package\PackageInterface $package): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::resolvePackageInstallPreference() in plugins yet');
    }

    public function setDownloader(string $type, \Composer\Downloader\DownloaderInterface $downloader): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::setDownloader() in plugins yet');
    }

    public function setPreferDist(bool $preferDist): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::setPreferDist() in plugins yet');
    }

    public function setPreferSource(bool $preferSource): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::setPreferSource() in plugins yet');
    }

    public function setPreferences(array $preferences): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::setPreferences() in plugins yet');
    }

    public function setSourceFallback(bool $sourceFallback): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::setSourceFallback() in plugins yet');
    }

    public function update(\Composer\Package\PackageInterface $initial, \Composer\Package\PackageInterface $target, string $targetDir): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\DownloadManager::update() in plugins yet');
    }
}
