<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Downloader;

class FileDownloader implements \Composer\Downloader\ChangeReportInterface, \Composer\Downloader\DownloaderInterface
{
    protected $cache;
    protected $config;
    public static $downloadMetadata = [];
    protected $eventDispatcher;
    protected $filesystem;
    protected $httpDownloader;
    protected $io;
    protected $process;
    public static $responseHeaders = [];

    public function __construct(\Composer\IO\IOInterface $io, \Composer\Config $config, \Composer\Util\HttpDownloader $httpDownloader, ?\Composer\EventDispatcher\EventDispatcher $eventDispatcher = null, ?\Composer\Cache $cache = null, ?\Composer\Util\Filesystem $filesystem = null, ?\Composer\Util\ProcessExecutor $process = null)
    {
        \Maestro\Shim\Rpc::call('downloader.new', [$this, $io, $config, $httpDownloader, $eventDispatcher, $cache, $filesystem, $process]);
    }

    protected function addCleanupPath(\Composer\Package\PackageInterface $package, string $path): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::addCleanupPath() in plugins yet');
    }

    public function cleanup(string $type, \Composer\Package\PackageInterface $package, string $path, ?\Composer\Package\PackageInterface $prevPackage = null): \React\Promise\PromiseInterface
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('downloader.cleanup', [$this, $type, $package, $path, $prevPackage]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::cleanup() in plugins yet');
    }

    protected function clearLastCacheWrite(\Composer\Package\PackageInterface $package): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::clearLastCacheWrite() in plugins yet');
    }

    public function download(\Composer\Package\PackageInterface $package, string $path, ?\Composer\Package\PackageInterface $prevPackage = null, bool $output = true): \React\Promise\PromiseInterface
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('downloader.download', [$this, $package, $path, $prevPackage, $output]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::download() in plugins yet');
    }

    protected function getDistPath(\Composer\Package\PackageInterface $package, int $component): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::getDistPath() in plugins yet');
    }

    protected function getFileName(\Composer\Package\PackageInterface $package, string $path): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::getFileName() in plugins yet');
    }

    protected function getInstallOperationAppendix(\Composer\Package\PackageInterface $package, string $path): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::getInstallOperationAppendix() in plugins yet');
    }

    public function getInstallationSource(): string
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('downloader.getInstallationSource', [$this]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::getInstallationSource() in plugins yet');
    }

    public function getLocalChanges(\Composer\Package\PackageInterface $package, string $path): ?string
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('downloader.getLocalChanges', [$this, $package, $path]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::getLocalChanges() in plugins yet');
    }

    public function install(\Composer\Package\PackageInterface $package, string $path, bool $output = true): \React\Promise\PromiseInterface
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('downloader.install', [$this, $package, $path, $output]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::install() in plugins yet');
    }

    public function prepare(string $type, \Composer\Package\PackageInterface $package, string $path, ?\Composer\Package\PackageInterface $prevPackage = null): \React\Promise\PromiseInterface
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('downloader.prepare', [$this, $type, $package, $path, $prevPackage]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::prepare() in plugins yet');
    }

    protected function processUrl(\Composer\Package\PackageInterface $package, string $url): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::processUrl() in plugins yet');
    }

    public function remove(\Composer\Package\PackageInterface $package, string $path, bool $output = true): \React\Promise\PromiseInterface
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('downloader.remove', [$this, $package, $path, $output]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::remove() in plugins yet');
    }

    protected function removeCleanupPath(\Composer\Package\PackageInterface $package, string $path): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::removeCleanupPath() in plugins yet');
    }

    public function update(\Composer\Package\PackageInterface $initial, \Composer\Package\PackageInterface $target, string $path): \React\Promise\PromiseInterface
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('downloader.update', [$this, $initial, $target, $path]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\FileDownloader::update() in plugins yet');
    }
}
