<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Downloader;

class GitDownloader extends \Composer\Downloader\VcsDownloader implements \Composer\Downloader\DvcsDownloaderInterface
{
    public function __construct(\Composer\IO\IOInterface $io, \Composer\Config $config, ?\Composer\Util\ProcessExecutor $process = null, ?\Composer\Util\Filesystem $fs = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::__construct() in plugins yet');
    }

    protected function cleanChanges(\Composer\Package\PackageInterface $package, string $path, bool $update): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::cleanChanges() in plugins yet');
    }

    protected function discardChanges(string $path): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::discardChanges() in plugins yet');
    }

    protected function doDownload(\Composer\Package\PackageInterface $package, string $path, string $url, ?\Composer\Package\PackageInterface $prevPackage = null): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::doDownload() in plugins yet');
    }

    protected function doInstall(\Composer\Package\PackageInterface $package, string $path, string $url): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::doInstall() in plugins yet');
    }

    protected function doUpdate(\Composer\Package\PackageInterface $initial, \Composer\Package\PackageInterface $target, string $path, string $url): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::doUpdate() in plugins yet');
    }

    protected function getCommitLogs(string $fromReference, string $toReference, string $path): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::getCommitLogs() in plugins yet');
    }

    public function getLocalChanges(\Composer\Package\PackageInterface $package, string $path): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::getLocalChanges() in plugins yet');
    }

    protected function getShortHash(string $reference): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::getShortHash() in plugins yet');
    }

    public function getUnpushedChanges(\Composer\Package\PackageInterface $package, string $path): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::getUnpushedChanges() in plugins yet');
    }

    protected function hasMetadataRepository(string $path): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::hasMetadataRepository() in plugins yet');
    }

    protected function normalizePath(string $path): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::normalizePath() in plugins yet');
    }

    protected function reapplyChanges(string $path): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::reapplyChanges() in plugins yet');
    }

    protected function setPushUrl(string $path, string $url): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::setPushUrl() in plugins yet');
    }

    protected function stashChanges(string $path): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::stashChanges() in plugins yet');
    }

    protected function updateOriginUrl(string $path, string $url): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::updateOriginUrl() in plugins yet');
    }

    protected function updateToCommit(\Composer\Package\PackageInterface $package, string $path, string $reference, string $prettyVersion): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::updateToCommit() in plugins yet');
    }

    protected function viewDiff(string $path): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\GitDownloader::viewDiff() in plugins yet');
    }
}
