<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Downloader;

class PathDownloader extends \Composer\Downloader\FileDownloader implements \Composer\Downloader\VcsCapableDownloaderInterface
{
    public function download(\Composer\Package\PackageInterface $package, string $path, ?\Composer\Package\PackageInterface $prevPackage = null, bool $output = true): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\PathDownloader::download() in plugins yet');
    }

    protected function getInstallOperationAppendix(\Composer\Package\PackageInterface $package, string $path): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\PathDownloader::getInstallOperationAppendix() in plugins yet');
    }

    public function getVcsReference(\Composer\Package\PackageInterface $package, string $path): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\PathDownloader::getVcsReference() in plugins yet');
    }

    public function install(\Composer\Package\PackageInterface $package, string $path, bool $output = true): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\PathDownloader::install() in plugins yet');
    }

    public function remove(\Composer\Package\PackageInterface $package, string $path, bool $output = true): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\PathDownloader::remove() in plugins yet');
    }
}
