<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Downloader;

class SvnDownloader extends \Composer\Downloader\VcsDownloader
{
    protected $cacheCredentials = true;

    protected function cleanChanges(\Composer\Package\PackageInterface $package, string $path, bool $update): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\SvnDownloader::cleanChanges() in plugins yet');
    }

    protected function discardChanges(string $path): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\SvnDownloader::discardChanges() in plugins yet');
    }

    protected function doDownload(\Composer\Package\PackageInterface $package, string $path, string $url, ?\Composer\Package\PackageInterface $prevPackage = null): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\SvnDownloader::doDownload() in plugins yet');
    }

    protected function doInstall(\Composer\Package\PackageInterface $package, string $path, string $url): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\SvnDownloader::doInstall() in plugins yet');
    }

    protected function doUpdate(\Composer\Package\PackageInterface $initial, \Composer\Package\PackageInterface $target, string $path, string $url): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\SvnDownloader::doUpdate() in plugins yet');
    }

    protected function execute(\Composer\Package\PackageInterface $package, string $baseUrl, array $command, string $url, ?string $cwd = null, ?string $path = null): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\SvnDownloader::execute() in plugins yet');
    }

    protected function getCommitLogs(string $fromReference, string $toReference, string $path): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\SvnDownloader::getCommitLogs() in plugins yet');
    }

    public function getLocalChanges(\Composer\Package\PackageInterface $package, string $path): ?string
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('downloader.getLocalChanges', [$this, $package, $path]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\SvnDownloader::getLocalChanges() in plugins yet');
    }

    protected function hasMetadataRepository(string $path): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\SvnDownloader::hasMetadataRepository() in plugins yet');
    }
}
