<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Downloader;

class TransportException extends \RuntimeException
{
    protected $headers;
    protected $response;
    protected $responseInfo = [];
    protected $statusCode;

    public function __construct(string $message = '', int $code = 400, ?\Throwable $previous = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\TransportException::__construct() in plugins yet');
    }

    public function getHeaders(): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\TransportException::getHeaders() in plugins yet');
    }

    public function getResponse(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\TransportException::getResponse() in plugins yet');
    }

    public function getResponseInfo(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\TransportException::getResponseInfo() in plugins yet');
    }

    public function getStatusCode(): ?int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\TransportException::getStatusCode() in plugins yet');
    }

    public function setHeaders(array $headers): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\TransportException::setHeaders() in plugins yet');
    }

    public function setResponse(?string $response): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\TransportException::setResponse() in plugins yet');
    }

    public function setResponseInfo(array $responseInfo): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\TransportException::setResponseInfo() in plugins yet');
    }

    public function setStatusCode($statusCode): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\TransportException::setStatusCode() in plugins yet');
    }
}
