<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Downloader;

class XzDownloader extends \Composer\Downloader\ArchiveDownloader
{
    protected function extract(\Composer\Package\PackageInterface $package, string $file, string $path): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\XzDownloader::extract() in plugins yet');
    }
}
