<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Downloader;

class ZipDownloader extends \Composer\Downloader\ArchiveDownloader
{
    public function download(\Composer\Package\PackageInterface $package, string $path, ?\Composer\Package\PackageInterface $prevPackage = null, bool $output = true): \React\Promise\PromiseInterface
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Promises::fromMaestro(\Maestro\Shim\Rpc::call('downloader.download', [$this, $package, $path, $prevPackage, $output]));
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\ZipDownloader::download() in plugins yet');
    }

    protected function extract(\Composer\Package\PackageInterface $package, string $file, string $path): \React\Promise\PromiseInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\ZipDownloader::extract() in plugins yet');
    }

    protected function getErrorMessage(int $retval, string $file): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Downloader\\ZipDownloader::getErrorMessage() in plugins yet');
    }
}
