<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Advisory;

class Auditor
{
    public const ABANDONED_FAIL = 'fail';
    public const ABANDONED_IGNORE = 'ignore';
    public const ABANDONED_REPORT = 'report';
    public const FORMATS = ['table', 'plain', 'json', 'summary'];
    public const FORMAT_JSON = 'json';
    public const FORMAT_PLAIN = 'plain';
    public const FORMAT_SUMMARY = 'summary';
    public const FORMAT_TABLE = 'table';
    public const STATUS_FAILED = 1;
    public const STATUS_OK = 0;

    public function audit(\Composer\IO\IOInterface $io, \Composer\Repository\RepositorySet $repoSet, \Composer\Policy\PolicyConfig $policyConfig, array $packages, string $format, bool $warningOnly = true, ?\Composer\FilterList\FilterListProvider\FilterListProviderSet $filterListProviderSet = null): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Advisory\\Auditor::audit() in plugins yet');
    }

    public function filterAbandonedPackages(array $packages, array $ignoreAbandoned): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Advisory\\Auditor::filterAbandonedPackages() in plugins yet');
    }

    public function needsCompleteAdvisoryLoad(array $advisories, array $ignoreList): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Advisory\\Auditor::needsCompleteAdvisoryLoad() in plugins yet');
    }

    public function processAdvisories(array $allAdvisories, array $ignoreList, array $ignoredSeverities): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Advisory\\Auditor::processAdvisories() in plugins yet');
    }
}
