<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Advisory;

class PartialSecurityAdvisory implements \JsonSerializable
{
    public $advisoryId;
    public $affectedVersions;
    public $packageName;

    public function __construct(string $packageName, string $advisoryId, \Composer\Semver\Constraint\ConstraintInterface $affectedVersions)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Advisory\\PartialSecurityAdvisory::__construct() in plugins yet');
    }

    public static function create(string $packageName, array $data, \Composer\Semver\VersionParser $parser): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Advisory\\PartialSecurityAdvisory::create() in plugins yet');
    }

    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Advisory\\PartialSecurityAdvisory::jsonSerialize() in plugins yet');
    }
}
