<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Installer;

interface InstallerInterface
{
    public function cleanup(string $type, \Composer\Package\PackageInterface $package, ?\Composer\Package\PackageInterface $prevPackage = null);

    public function download(\Composer\Package\PackageInterface $package, ?\Composer\Package\PackageInterface $prevPackage = null);

    public function getInstallPath(\Composer\Package\PackageInterface $package);

    public function install(\Composer\Repository\InstalledRepositoryInterface $repo, \Composer\Package\PackageInterface $package);

    public function isInstalled(\Composer\Repository\InstalledRepositoryInterface $repo, \Composer\Package\PackageInterface $package);

    public function prepare(string $type, \Composer\Package\PackageInterface $package, ?\Composer\Package\PackageInterface $prevPackage = null);

    public function supports(string $packageType);

    public function uninstall(\Composer\Repository\InstalledRepositoryInterface $repo, \Composer\Package\PackageInterface $package);

    public function update(\Composer\Repository\InstalledRepositoryInterface $repo, \Composer\Package\PackageInterface $initial, \Composer\Package\PackageInterface $target);
}
