<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Installer;

class InstallerEvent extends \Composer\EventDispatcher\Event
{
    public function __construct(string $eventName, \Composer\Composer $composer, \Composer\IO\IOInterface $io, bool $devMode, bool $executeOperations, \Composer\DependencyResolver\Transaction $transaction)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\InstallerEvent::__construct() in plugins yet');
    }

    public function getComposer(): \Composer\Composer
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\InstallerEvent::getComposer() in plugins yet');
    }

    public function getIO(): \Composer\IO\IOInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\InstallerEvent::getIO() in plugins yet');
    }

    public function getTransaction(): ?\Composer\DependencyResolver\Transaction
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\InstallerEvent::getTransaction() in plugins yet');
    }

    public function isDevMode(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\InstallerEvent::isDevMode() in plugins yet');
    }

    public function isExecutingOperations(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\InstallerEvent::isExecutingOperations() in plugins yet');
    }
}
