<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Installer;

class LibraryInstaller implements \Composer\Installer\BinaryPresenceInterface, \Composer\Installer\InstallerInterface
{
    protected $binaryInstaller;
    protected $composer;
    protected $downloadManager;
    protected $filesystem;
    protected $io;
    protected $type;
    protected $vendorDir;

    public function __construct(\Composer\IO\IOInterface $io, \Composer\PartialComposer $composer, ?string $type = 'library', ?\Composer\Util\Filesystem $filesystem = null, ?\Composer\Installer\BinaryInstaller $binaryInstaller = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::__construct() in plugins yet');
    }

    public function cleanup($type, \Composer\Package\PackageInterface $package, ?\Composer\Package\PackageInterface $prevPackage = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::cleanup() in plugins yet');
    }

    public function download(\Composer\Package\PackageInterface $package, ?\Composer\Package\PackageInterface $prevPackage = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::download() in plugins yet');
    }

    public function ensureBinariesPresence(\Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::ensureBinariesPresence() in plugins yet');
    }

    protected function getDownloadManager(): \Composer\Downloader\DownloadManager
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::getDownloadManager() in plugins yet');
    }

    public function getInstallPath(\Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::getInstallPath() in plugins yet');
    }

    protected function getPackageBasePath(\Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::getPackageBasePath() in plugins yet');
    }

    protected function initializeVendorDir()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::initializeVendorDir() in plugins yet');
    }

    public function install(\Composer\Repository\InstalledRepositoryInterface $repo, \Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::install() in plugins yet');
    }

    protected function installCode(\Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::installCode() in plugins yet');
    }

    public function isInstalled(\Composer\Repository\InstalledRepositoryInterface $repo, \Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::isInstalled() in plugins yet');
    }

    public function prepare($type, \Composer\Package\PackageInterface $package, ?\Composer\Package\PackageInterface $prevPackage = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::prepare() in plugins yet');
    }

    protected function removeCode(\Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::removeCode() in plugins yet');
    }

    public function supports(string $packageType)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::supports() in plugins yet');
    }

    public function uninstall(\Composer\Repository\InstalledRepositoryInterface $repo, \Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::uninstall() in plugins yet');
    }

    public function update(\Composer\Repository\InstalledRepositoryInterface $repo, \Composer\Package\PackageInterface $initial, \Composer\Package\PackageInterface $target)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::update() in plugins yet');
    }

    protected function updateCode(\Composer\Package\PackageInterface $initial, \Composer\Package\PackageInterface $target)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\LibraryInstaller::updateCode() in plugins yet');
    }
}
