<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Installer;

class PluginInstaller extends \Composer\Installer\LibraryInstaller
{
    public function __construct(\Composer\IO\IOInterface $io, \Composer\PartialComposer $composer, ?\Composer\Util\Filesystem $fs = null, ?\Composer\Installer\BinaryInstaller $binaryInstaller = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\PluginInstaller::__construct() in plugins yet');
    }

    public function disablePlugins(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\PluginInstaller::disablePlugins() in plugins yet');
    }

    public function download(\Composer\Package\PackageInterface $package, ?\Composer\Package\PackageInterface $prevPackage = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\PluginInstaller::download() in plugins yet');
    }

    protected function getPluginManager(): \Composer\Plugin\PluginManager
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\PluginInstaller::getPluginManager() in plugins yet');
    }

    public function install(\Composer\Repository\InstalledRepositoryInterface $repo, \Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\PluginInstaller::install() in plugins yet');
    }

    public function prepare($type, \Composer\Package\PackageInterface $package, ?\Composer\Package\PackageInterface $prevPackage = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\PluginInstaller::prepare() in plugins yet');
    }

    public function supports(string $packageType)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\PluginInstaller::supports() in plugins yet');
    }

    public function uninstall(\Composer\Repository\InstalledRepositoryInterface $repo, \Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\PluginInstaller::uninstall() in plugins yet');
    }

    public function update(\Composer\Repository\InstalledRepositoryInterface $repo, \Composer\Package\PackageInterface $initial, \Composer\Package\PackageInterface $target)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\PluginInstaller::update() in plugins yet');
    }
}
