<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Installer;

class SuggestedPackagesReporter
{
    public const MODE_BY_PACKAGE = 2;
    public const MODE_BY_SUGGESTION = 4;
    public const MODE_LIST = 1;

    protected $suggestedPackages = [];

    public function __construct(\Composer\IO\IOInterface $io)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\SuggestedPackagesReporter::__construct() in plugins yet');
    }

    public function addPackage(string $source, string $target, string $reason): \Composer\Installer\SuggestedPackagesReporter
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\SuggestedPackagesReporter::addPackage() in plugins yet');
    }

    public function addSuggestionsFromPackage(\Composer\Package\PackageInterface $package): \Composer\Installer\SuggestedPackagesReporter
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\SuggestedPackagesReporter::addSuggestionsFromPackage() in plugins yet');
    }

    public function getPackages(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\SuggestedPackagesReporter::getPackages() in plugins yet');
    }

    public function output(int $mode, ?\Composer\Repository\InstalledRepository $installedRepo = null, ?\Composer\Package\PackageInterface $onlyDependentsOf = null): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\SuggestedPackagesReporter::output() in plugins yet');
    }

    public function outputMinimalistic(?\Composer\Repository\InstalledRepository $installedRepo = null, ?\Composer\Package\PackageInterface $onlyDependentsOf = null): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Installer\\SuggestedPackagesReporter::outputMinimalistic() in plugins yet');
    }
}
