<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\FilterList;

class ComposerRepositoryFilterInformation
{
    public $apiUrl;
    public $lists;
    public $metadata;
    public $summaryUrl;

    public static function fromData(array $data, ?\Closure $canonicalizeUrl = null): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\ComposerRepositoryFilterInformation::fromData() in plugins yet');
    }
}
