<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\FilterList;

class FilterListAuditor
{
    public function collectFilterLists(array $packages, \Composer\FilterList\FilterListProvider\FilterListProviderSet $providerSet, array $configuredLists, bool $ignoreUnreachable): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListAuditor::collectFilterLists() in plugins yet');
    }

    public function getMatchingAuditEntries(\Composer\Package\PackageInterface $package, array $filterListMap, \Composer\Policy\PolicyConfig $policyConfig): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListAuditor::getMatchingAuditEntries() in plugins yet');
    }

    public function getMatchingBlockEntries(\Composer\Package\PackageInterface $package, array $filterListMap, \Composer\Policy\PolicyConfig $policyConfig, string $blockScope): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListAuditor::getMatchingBlockEntries() in plugins yet');
    }
}
