<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\FilterList;

class FilterListApiClient
{
    public function __construct(\Composer\Util\HttpDownloader $httpDownloader, array $options = [])
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListApiClient::__construct() in plugins yet');
    }

    public function postPurls(string $url, array $packageConstraintMap, array $configuredLists): \Composer\Util\Http\Response
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListApiClient::postPurls() in plugins yet');
    }
}
