<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\FilterList;

class FilterListEntry
{
    public $constraint;
    public $id;
    public $listName;
    public $packageName;
    public $reason;
    public $source;
    public $url;

    public function __construct(string $packageName, \Composer\Semver\Constraint\ConstraintInterface $constraint, string $listName, ?string $url = null, ?string $reason = null, ?string $id = null, ?string $source = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListEntry::__construct() in plugins yet');
    }

    public static function create(string $listName, array $data, \Composer\Semver\VersionParser $parser): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\FilterList\\FilterListEntry::create() in plugins yet');
    }
}
