// Ports the file builders of src/Composer/Autoload/AutoloadGenerator.php:
// the autoload_namespaces/psr4/classmap.php parts of dump(),
// getIncludePathsFile, getIncludeFilesFile, getAutoloadFile,
// getAutoloadRealFile and getStaticFile.

package autoload

import (
	"os"
	"slices"
	"strconv"
	"strings"

	"github.com/stubbedev/maestro/internal/classmap"
	"github.com/stubbedev/maestro/internal/io"
	"github.com/stubbedev/maestro/internal/php"
	"github.com/stubbedev/maestro/internal/phperr"
	"github.com/stubbedev/maestro/internal/pkg"
	"github.com/stubbedev/maestro/internal/util"
)

// dump is the state of one dump(): the paths, the codes for them and the
// generated autoload_*.php contents, plus what PHP gets back when
// getStaticFile requires those files.
type dump struct {
	basePath   string // the project dir
	vendorPath string
	targetDir  string // vendorPath/targetDir
	realTarget string // realpath(targetDir), the __DIR__ of its files

	vendorPathCode            string
	vendorPathToTargetDirCode string
	appBaseDirCode            string

	// vendorDir and baseDir are what $vendorDir and $baseDir evaluate to
	// in the generated files.
	vendorDir, baseDir string

	namespacesFile, psr4File, classmapFile string

	psr0, psr4 []namespacePaths
	classes    []string
	classPaths []pathRef
	// files is what autoload_files.php returns, nil without one.
	files *php.Array
}

// namespacePaths is one entry of autoload_namespaces.php or
// autoload_psr4.php.
type namespacePaths struct {
	namespace php.Key
	paths     []pathRef
}

// newDump creates vendor-dir and vendor-dir/targetDir and works out the
// paths of a dump.
func newDump(config Config, targetDir string) (*dump, error) {
	vendorDir, err := configString(config, "vendor-dir")
	if err != nil {
		return nil, err
	}
	if err := util.EnsureDirectoryExists(vendorDir); err != nil {
		return nil, err
	}

	cwd, err := util.GetCwd(false)
	if err != nil {
		return nil, err
	}
	d := &dump{}
	if d.basePath, err = realpath(cwd, 217); err != nil {
		return nil, err
	}
	d.basePath = util.NormalizePath(d.basePath)
	if d.vendorPath, err = realpath(vendorDir, 218); err != nil {
		return nil, err
	}
	d.vendorPath = util.NormalizePath(d.vendorPath)
	d.targetDir = d.vendorPath + "/" + targetDir
	if err := util.EnsureDirectoryExists(d.targetDir); err != nil {
		return nil, err
	}
	if d.realTarget, err = realpath(d.targetDir, 224); err != nil {
		return nil, err
	}

	if d.vendorPathCode, err = util.FindShortestPathCode(d.realTarget, d.vendorPath, true, false, false); err != nil {
		return nil, err
	}
	if d.vendorPathToTargetDirCode, err = util.FindShortestPathCode(d.vendorPath, d.realTarget, true, false, false); err != nil {
		return nil, err
	}
	if d.appBaseDirCode, err = util.FindShortestPathCode(d.vendorPath, d.basePath, true, false, false); err != nil {
		return nil, err
	}
	d.appBaseDirCode = strings.ReplaceAll(d.appBaseDirCode, "__DIR__", "$vendorDir")

	d.vendorDir = evalPathCode(d.vendorPathCode, d.realTarget, "")
	d.baseDir = evalPathCode(d.appBaseDirCode, "", d.vendorDir)

	return d, nil
}

// realpath is realpath(), failing as PHP's strict_types call taking its
// false result would: Filesystem::normalizePath() at line 217 or 218 of
// AutoloadGenerator.php, findShortestPathCode() at line 224 (0: a call
// maestro adds).
func realpath(path string, line int) (string, error) {
	real, ok := util.RealpathOK(path)
	if !ok {
		fn, param, decl := "normalizePath", "path", 605
		if line == 224 {
			fn, param, decl = "findShortestPathCode", "from", 524
		}
		e := &php.EngineError{Class: "TypeError", Message: "Composer\\Util\\Filesystem::" + fn + "(): Argument #1 ($" + param + ") must be of type string, false given"}
		if line > 0 {
			e.Called(`Composer\Util\Filesystem->`+fn, phperr.At("Filesystem.php", decl), "AutoloadGenerator.php", line)
		}

		return "", e
	}

	return real, nil
}

// appendHeader appends the head of the autoload_*.php file name, up to and
// including "return array(\n".
func (d *dump) appendHeader(name string) []byte {
	b := append(make([]byte, 0, 256), "<?php\n\n// "...)
	b = append(b, name...)
	b = append(b, " @generated by Composer\n\n$vendorDir = "...)
	b = append(b, d.vendorPathCode...)
	b = append(b, ";\n$baseDir = "...)
	b = append(b, d.appBaseDirCode...)

	return append(b, ";\n\nreturn array(\n"...)
}

// pathRef ports getPathCode.
func (d *dump) pathRef(path string) (pathRef, error) {
	return pathRefOf(d.basePath, d.vendorPath, path)
}

// namespaces builds autoload_namespaces.php and autoload_psr4.php.
func (d *dump) namespaces(autoloads *Autoloads) error {
	var err error
	if d.namespacesFile, d.psr0, err = d.namespacesOf("autoload_namespaces.php", autoloads.PSR0); err != nil {
		return err
	}
	d.psr4File, d.psr4, err = d.namespacesOf("autoload_psr4.php", autoloads.PSR4)

	return err
}

func (d *dump) namespacesOf(name string, rules *php.Array) (string, []namespacePaths, error) {
	b := d.appendHeader(name)
	entries := make([]namespacePaths, 0, rules.Len())
	for namespace, v := range rules.All() {
		paths, _ := v.(*php.Array)
		refs := make([]pathRef, 0, paths.Len())
		b = append(b, "    "...)
		b = php.AppendVarExport(b, namespace.Value())
		b = append(b, " => array("...)
		for i, path := range paths.Values() {
			ref, err := d.pathRef(php.ToString(path))
			if err != nil {
				return "", nil, err
			}
			if i > 0 {
				b = append(b, ", "...)
			}
			b = ref.appendCode(b)
			refs = append(refs, ref)
		}
		b = append(b, "),\n"...)
		entries = append(entries, namespacePaths{namespace, refs})
	}

	return string(append(b, ");\n"...)), entries, nil
}

// classmap builds autoload_classmap.php.
func (d *dump) classmap(classMap *classmap.ClassMap) error {
	b := d.appendHeader("autoload_classmap.php")
	d.classes = classMap.Classes()
	d.classPaths = make([]pathRef, 0, len(d.classes))
	for className, path := range classMap.Map() {
		ref, err := d.pathRef(path)
		if err != nil {
			return err
		}
		b = append(b, "    "...)
		b = php.AppendVarExport(b, className)
		b = append(b, " => "...)
		b = ref.appendCode(b)
		b = append(b, ",\n"...)
		d.classPaths = append(d.classPaths, ref)
	}
	d.classmapFile = string(append(b, ");\n"...))

	return nil
}

// targetDirLoader returns the autoload() method of the root package's
// target-dir loader, or "" for none.
func (d *dump) targetDirLoader(rootPackage pkg.RootPackageInterface) (string, error) {
	targetDir := rootPackage.TargetDir()
	psr0, _ := rootPackage.Autoload().Get("psr-0")
	if !php.ToBool(targetDir.Value()) || !php.ToBool(psr0) {
		return "", nil
	}
	rules, ok := psr0.(*php.Array)
	if !ok {
		return "", (&php.EngineError{Class: "TypeError", Message: "array_keys(): Argument #1 ($array) must be of type array, " + php.ZvalValueName(psr0) + " given"}).
			Raised("array_keys", "AutoloadGenerator.php", 297)
	}

	levels := strings.Count(util.NormalizePath(targetDir.S), "/") + 1
	prefixes := make([]string, 0, rules.Len())
	for prefix := range rules.All() {
		prefixes = append(prefixes, php.VarExport(prefix.Value()))
	}
	baseDirFromTargetDirCode, err := util.FindShortestPathCode(d.targetDir, d.basePath, true, false, false)
	if err != nil {
		return "", err
	}

	return `
    public static function autoload($class)
    {
        $dir = ` + baseDirFromTargetDirCode + ` . '/';
        $prefixes = array(` + strings.Join(prefixes, ", ") + `);
        foreach ($prefixes as $prefix) {
            if (0 !== strpos($class, $prefix)) {
                continue;
            }
            $path = $dir . implode('/', array_slice(explode('\\', $class), ` + strconv.Itoa(levels) + `)).'.php';
            if (!$path = stream_resolve_include_path($path)) {
                return false;
            }
            require $path;

            return true;
        }
    }
`, nil
}

// psrScan is one ScanPaths call of the PSR-0/4 scan.
type psrScan struct {
	dir       string
	excluded  classmap.Matcher
	typ       classmap.AutoloadType
	namespace string
}

// psrScans lists the scans that add the classes of the PSR-0/4
// directories to the class map, in order.
func (d *dump) psrScans(autoloads *Autoloads, excluded []string) []psrScan {
	type group struct {
		paths *php.Array
		typ   classmap.AutoloadType
	}
	// namespacesToScan maps namespaces to indexes into groups.
	namespacesToScan := php.NewArray()
	var groups [][]group
	for _, psr := range [2]struct {
		rules *php.Array
		typ   classmap.AutoloadType
	}{{autoloads.PSR4, classmap.PSR4}, {autoloads.PSR0, classmap.PSR0}} {
		for namespace, paths := range psr.rules.All() {
			v, ok := namespacesToScan.GetKey(namespace)
			i, _ := v.(int64)
			if !ok {
				i = int64(len(groups))
				namespacesToScan.SetKey(namespace, i)
				groups = append(groups, nil)
			}
			list, _ := paths.(*php.Array)
			groups[i] = append(groups[i], group{list, psr.typ})
		}
	}

	php.Krsort(namespacesToScan, 0)

	var scans []psrScan
	for namespace, v := range namespacesToScan.All() {
		i, _ := v.(int64)
		for _, group := range groups[i] {
			for _, v := range group.paths.Values() {
				dir := php.ToString(v)
				if !util.IsAbsolutePath(dir) {
					dir = d.basePath + "/" + dir
				}
				dir = util.NormalizePath(dir)
				if fi, err := os.Stat(dir); err != nil || !fi.IsDir() {
					continue
				}

				// if the vendor dir is contained within a psr-0/psr-4 dir
				// being scanned we exclude it
				dirExcluded := excluded
				if strings.Contains(d.vendorPath, dir+"/") {
					dirExcluded = append(slices.Clip(excluded), d.vendorPath+"/")
				}

				scans = append(scans, psrScan{dir, buildExclusionRegex(dir, dirExcluded), group.typ, namespace.String()})
			}
		}
	}

	return scans
}

// includePathsFile ports getIncludePathsFile ("" for null).
func (d *dump) includePathsFile(packageMap []PackageMapEntry) (string, error) {
	var b []byte
	for _, item := range packageMap {
		// packages that are not installed cannot autoload anything
		if !item.Installed {
			continue
		}
		p, installPath := item.Package, item.InstallPath

		if targetDir := p.TargetDir(); targetDir.Valid && targetDir.S != "" {
			installPath = php.SubstrLen(installPath, 0, -len("/"+targetDir.S))
		}

		for _, v := range p.IncludePaths().Values() {
			includePath := php.TrimSet(php.ToString(v), "/")
			if installPath != "" {
				includePath = installPath + "/" + includePath
			}
			ref, err := d.pathRef(includePath)
			if err != nil {
				return "", err
			}
			b = append(b, "    "...)
			b = ref.appendCode(b)
			b = append(b, ",\n"...)
		}
	}

	if b == nil {
		return "", nil
	}

	return string(append(append(d.appendHeader("include_paths.php"), b...), ");\n"...)), nil
}

// includeFilesFile ports getIncludeFilesFile ("" for null), warning about
// files included more than once.
func (g *Generator) includeFilesFile(d *dump, files *php.Array) (string, error) {
	// Get the path to each file, and make sure these paths are unique.
	codes := make([]string, 0, files.Len())
	refs := make([]pathRef, 0, files.Len())
	seen := make(map[string]bool, files.Len())
	var duplicates []string
	for _, v := range files.All() {
		ref, err := d.pathRef(php.ToString(v))
		if err != nil {
			return "", err
		}
		code := ref.code()
		codes = append(codes, code)
		refs = append(refs, ref)
		if seen[code] {
			duplicates = append(duplicates, code)
		}
		seen[code] = true
	}
	if duplicates != nil {
		g.io.WriteError(`<warning>The following "files" autoload rules are included multiple times, this may cause issues and should be resolved:</warning>`, true, io.Normal)
		reported := map[string]bool{}
		for _, duplicate := range duplicates {
			if !reported[duplicate] {
				reported[duplicate] = true
				g.io.WriteError("<warning> - "+duplicate+"</warning>", true, io.Normal)
			}
		}
	}

	if len(codes) == 0 {
		return "", nil
	}

	b := d.appendHeader("autoload_files.php")
	d.files = php.NewArrayCap(files.Len())
	i := 0
	for fileIdentifier := range files.All() {
		b = append(b, "    "...)
		b = php.AppendVarExport(b, fileIdentifier.Value())
		b = append(b, " => "...)
		b = append(b, codes[i]...)
		b = append(b, ",\n"...)
		d.files.SetKey(fileIdentifier, refs[i].value(d.vendorDir, d.baseDir))
		i++
	}

	return string(append(b, ");\n"...)), nil
}

// autoloadFile ports getAutoloadFile: vendor/autoload.php.
func autoloadFile(vendorPathToTargetDirCode, suffix string) string {
	if last := vendorPathToTargetDirCode[len(vendorPathToTargetDirCode)-1]; last == '\'' || last == '"' {
		vendorPathToTargetDirCode = vendorPathToTargetDirCode[:len(vendorPathToTargetDirCode)-1] + "/autoload_real.php" + string(last)
	} else {
		vendorPathToTargetDirCode += " . '/autoload_real.php'"
	}

	return `<?php

// autoload.php @generated by Composer

if (PHP_VERSION_ID < 50600) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, $err);
        } elseif (!headers_sent()) {
            echo $err;
        }
    }
    throw new RuntimeException($err);
}

require_once ` + vendorPathToTargetDirCode + `;

return ComposerAutoloaderInit` + suffix + `::getLoader();
`
}

// autoloadRealFile ports getAutoloadRealFile: vendor/composer/autoload_real.php.
func (g *Generator) autoloadRealFile(useIncludePath bool, targetDirLoader string, useIncludeFiles bool, suffix string, useGlobalIncludePath, prependAutoloader, checkPlatform bool) string {
	prepend := "false"
	if prependAutoloader {
		prepend = "true"
	}

	var b strings.Builder
	b.WriteString(`<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit` + suffix + `
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

`)

	if checkPlatform {
		b.WriteString(`        require __DIR__ . '/platform_check.php';

`)
	}

	b.WriteString(`        spl_autoload_register(array('ComposerAutoloaderInit` + suffix + `', 'loadClassLoader'), true, ` + prepend + `);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit` + suffix + `', 'loadClassLoader'));

`)

	if useIncludePath {
		b.WriteString(`        $includePaths = require __DIR__ . '/include_paths.php';
        $includePaths[] = get_include_path();
        set_include_path(implode(PATH_SEPARATOR, $includePaths));

`)
	}

	// keeping PHP 5.6+ compatibility for the autoloader here by using
	// call_user_func vs getInitializer()()
	b.WriteString(`        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInit` + suffix + `::getInitializer($loader));

`)

	if g.classMapAuthoritative {
		b.WriteString("        $loader->setClassMapAuthoritative(true);\n")
	}

	if g.apcu {
		prefix := ""
		if g.apcuPrefix != nil {
			prefix = *g.apcuPrefix
		} else {
			prefix = randomHex(10)
		}
		b.WriteString("        $loader->setApcuPrefix(" + php.VarExport(prefix) + ");\n")
	}

	if useGlobalIncludePath {
		b.WriteString("        $loader->setUseIncludePath(true);\n")
	}

	if targetDirLoader != "" {
		b.WriteString(`        spl_autoload_register(array('ComposerAutoloaderInit` + suffix + `', 'autoload'), true, true);

`)
	}

	b.WriteString("        $loader->register(" + prepend + ");\n\n")

	if useIncludeFiles {
		b.WriteString(`        $filesToLoad = \Composer\Autoload\ComposerStaticInit` + suffix + `::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

`)
	}

	b.WriteString("        return $loader;\n    }\n")
	b.WriteString(targetDirLoader)
	b.WriteString("}\n")

	return b.String()
}

// staticFile ports getStaticFile: vendor/composer/autoload_static.php, the
// properties a ClassLoader has after loading autoload_namespaces.php,
// autoload_psr4.php, autoload_classmap.php and autoload_files.php, as code.
func (d *dump) staticFile(suffix string) (string, error) {
	loader := NewClassLoader("")

	for _, entry := range d.psr0 {
		if err := loader.Set(entry.namespace, d.values(entry.paths)); err != nil {
			return "", err
		}
	}
	for _, entry := range d.psr4 {
		if err := loader.SetPsr4(entry.namespace, d.values(entry.paths)); err != nil {
			return "", phperr.Call(err, `Composer\Autoload\ClassLoader->setPsr4`, "AutoloadGenerator.php", 1175)
		}
	}
	classMap := php.NewArrayCap(len(d.classes))
	for i, class := range d.classes {
		classMap.Set(class, d.classPaths[i].value(d.vendorDir, d.baseDir))
	}
	if classMap.Len() > 0 {
		loader.AddClassMap(classMap)
	}

	staticCode := func(to string, phar bool) (string, error) {
		code, err := util.FindShortestPathCode(d.realTarget, to, true, true, false)
		if err != nil {
			return "", err
		}
		if phar {
			return " => 'phar://' . " + code + " . '/", nil
		}

		return " => " + code + " . '/", nil
	}
	absoluteCode := func(path string) string {
		code := php.VarExport(php.RtrimSet(path, `\/`) + "/")

		return " => " + code[:len(code)-1]
	}

	// The keys of strtr()'s array literal, a later equal key replacing an
	// earlier one's value.
	replacements := make(map[string]string, 4)
	for _, r := range [4]struct {
		absolute, to string
		phar         bool
	}{
		{absoluteCode(d.vendorDir), d.vendorPath, false},
		{absoluteCode("phar://" + d.vendorDir), d.vendorPath, true},
		{absoluteCode(d.baseDir), d.basePath, false},
		{absoluteCode("phar://" + d.baseDir), d.basePath, true},
	} {
		code, err := staticCode(r.to, r.phar)
		if err != nil {
			return "", err
		}
		replacements[r.absolute] = code
	}

	var b strings.Builder
	b.WriteString(`<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit` + suffix + `
{
`)

	var initializer strings.Builder
	writeProperty := func(name string, value *php.Array) {
		b.WriteString("    public static $" + name + " = ")
		b.WriteString(indentExport(php.StrtrPairs(php.VarExport(value), replacements)))
		b.WriteString(";\n\n")
		if name != "files" {
			initializer.WriteString("            $loader->" + name + " = ComposerStaticInit" + suffix + "::$" + name + ";\n")
		}
	}
	if d.files != nil {
		writeProperty("files", d.files)
	}
	for _, prop := range loader.properties() {
		if prop.value.Len() > 0 {
			writeProperty(prop.name, prop.value)
		}
	}

	b.WriteString(`    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
` + initializer.String() + `
        }, null, ClassLoader::class);
    }
}
`)

	return b.String(), nil
}

// values evaluates path codes to the list of paths they stand for.
func (d *dump) values(refs []pathRef) *php.Array {
	a := php.NewArrayCap(len(refs))
	for _, ref := range refs {
		a.Append(ref.value(d.vendorDir, d.baseDir))
	}

	return a
}

// indentExport re-indents var_export output for a static property:
// ltrim(Preg::replace('/^ */m', '    $0$0', $value)) then
// Preg::replace('/ +$/m', "", $value). Each line's leading spaces are
// doubled plus four, trailing spaces before a newline or the end are
// dropped, then leading whitespace of the whole is trimmed.
func indentExport(s string) string {
	b := make([]byte, 0, len(s)+len(s)/4)
	for lineStart := 0; ; {
		// ^ matches at the start and after each newline except a final one.
		n := 0
		for lineStart+n < len(s) && s[lineStart+n] == ' ' {
			n++
		}
		b = append(b, "    "...)
		for range 2 * n {
			b = append(b, ' ')
		}
		end := strings.IndexByte(s[lineStart+n:], '\n')
		if end < 0 {
			b = append(b, s[lineStart+n:]...)

			break
		}
		end += lineStart + n
		b = append(b, s[lineStart+n:end+1]...)
		lineStart = end + 1
		if lineStart == len(s) {
			break
		}
	}

	// / +$/m: spaces before each newline and at the end.
	out := b[:0]
	for i := 0; i < len(b); {
		if b[i] != ' ' {
			out = append(out, b[i])
			i++

			continue
		}
		j := i
		for j < len(b) && b[j] == ' ' {
			j++
		}
		if j < len(b) && b[j] != '\n' {
			out = append(out, b[i:j]...)
		}
		i = j
	}

	return php.Ltrim(string(out))
}
