// Ports the file builders of src/Composer/Autoload/AutoloadGenerator.php:
// the autoload_namespaces/psr4/classmap.php parts of dump(),
// getIncludePathsFile, getIncludeFilesFile, getAutoloadFile,
// getAutoloadRealFile and getStaticFile.

package autoload

import (
	"os"
	"runtime"
	"slices"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"

	"github.com/stubbedev/maestro/internal/classmap"
	"github.com/stubbedev/maestro/internal/io"
	"github.com/stubbedev/maestro/internal/php"
	"github.com/stubbedev/maestro/internal/pkg"
	"github.com/stubbedev/maestro/internal/util"
	"github.com/stubbedev/maestro/internal/util/fspath"
)

// dump is the state of one dump(): the paths, the codes for them and the
// generated autoload_*.php contents, plus what PHP gets back when
// getStaticFile requires those files.
type dump struct {
	dumpPaths

	namespacesFile, psr4File, classmapFile string

	psr0, psr4 []namespacePaths
	classes    []string
	classPaths []pathRef
	// files is what autoload_files.php returns, nil without one.
	files *php.Array
	// staticClassMap is autoload_static.php's $classMap value, exported
	// with autoload_classmap.php (classmap), "" when staticFile exports
	// it.
	staticClassMap string

	exclusions exclusionRegexes
}

// dumpPaths are a dump's paths and the codes for them: everything
// dump.classmap reads besides the class map, so that the class map files
// a speculation built are taken only by a dump with equal dumpPaths
// (speculation.takeClassmap). A field dump.classmap reads goes here.
type dumpPaths struct {
	basePath   string // the project dir
	vendorPath string
	targetDir  string // vendorPath/targetDir
	realTarget string // realpath(targetDir), the __DIR__ of its files

	vendorPathCode            string
	vendorPathToTargetDirCode string
	appBaseDirCode            string

	// vendorDir and baseDir are what $vendorDir and $baseDir evaluate to
	// in the generated files.
	vendorDir, baseDir string
}

// namespacePaths is one entry of autoload_namespaces.php or
// autoload_psr4.php.
type namespacePaths struct {
	namespace php.Key
	paths     []pathRef
}

// newDump creates vendor-dir and vendor-dir/targetDir and works out the
// paths of a dump.
func newDump(config Config, targetDir string) (*dump, error) {
	vendorDir, err := vendorDirConfig(config)
	if err != nil {
		return nil, err
	}
	if err := util.EnsureDirectoryExists(vendorDir); err != nil {
		return nil, err
	}

	cwd, err := util.GetCwd(false)
	if err != nil {
		return nil, err
	}
	d := &dump{}
	if d.basePath, err = realpath(cwd); err != nil {
		return nil, err
	}
	d.basePath = fspath.NormalizePath(d.basePath)
	if d.vendorPath, err = realpath(vendorDir); err != nil {
		return nil, err
	}
	d.vendorPath = fspath.NormalizePath(d.vendorPath)
	d.targetDir = d.vendorPath + "/" + targetDir
	if err := util.EnsureDirectoryExists(d.targetDir); err != nil {
		return nil, err
	}
	if d.realTarget, err = realpath(d.targetDir); err != nil {
		return nil, err
	}

	if d.vendorPathCode, err = util.FindShortestPathCode(d.realTarget, d.vendorPath, true, false, false); err != nil {
		return nil, err
	}
	if d.vendorPathToTargetDirCode, err = util.FindShortestPathCode(d.vendorPath, d.realTarget, true, false, false); err != nil {
		return nil, err
	}
	if d.appBaseDirCode, err = util.FindShortestPathCode(d.vendorPath, d.basePath, true, false, false); err != nil {
		return nil, err
	}
	d.appBaseDirCode = strings.ReplaceAll(d.appBaseDirCode, "__DIR__", "$vendorDir")

	d.vendorDir = evalPathCode(d.vendorPathCode, d.realTarget, "")
	d.baseDir = evalPathCode(d.appBaseDirCode, "", d.vendorDir)

	return d, nil
}

// realpath is realpath() of a path AutoloadGenerator::dump hands to
// Filesystem's strictly typed methods: when it fails, PHP throws a
// TypeError for the false those methods receive in place of a path.
func realpath(path string) (string, error) {
	real, ok := php.Realpath(path)
	if !ok {
		return "", &php.EngineError{Class: "TypeError", Message: "Could not resolve the real path of " + path}
	}

	return real, nil
}

// appendHeader appends the head of the autoload_*.php file name, up to and
// including "return array(\n".
func (d *dump) appendHeader(name string) []byte {
	b := append(make([]byte, 0, 256), "<?php\n\n// "...)
	b = append(b, name...)
	b = append(b, " @generated by Composer\n\n$vendorDir = "...)
	b = append(b, d.vendorPathCode...)
	b = append(b, ";\n$baseDir = "...)
	b = append(b, d.appBaseDirCode...)

	return append(b, ";\n\nreturn array(\n"...)
}

// pathRef ports getPathCode.
func (d *dump) pathRef(path string) (pathRef, error) {
	return pathRefOf(d.basePath, d.vendorPath, path)
}

// namespaces builds autoload_namespaces.php and autoload_psr4.php.
func (d *dump) namespaces(autoloads *Autoloads) error {
	var err error
	if d.namespacesFile, d.psr0, err = d.namespacesOf("autoload_namespaces.php", autoloads.PSR0); err != nil {
		return err
	}
	d.psr4File, d.psr4, err = d.namespacesOf("autoload_psr4.php", autoloads.PSR4)

	return err
}

func (d *dump) namespacesOf(name string, rules *php.Array) (string, []namespacePaths, error) {
	b := d.appendHeader(name)
	entries := make([]namespacePaths, 0, rules.Len())
	for namespace, v := range rules.All() {
		paths, _ := v.(*php.Array)
		refs := make([]pathRef, 0, paths.Len())
		b = append(b, "    "...)
		b = php.AppendVarExport(b, namespace.Value())
		b = append(b, " => array("...)
		for i, path := range paths.Values() {
			ref, err := d.pathRef(php.ToString(path))
			if err != nil {
				return "", nil, err
			}
			if i > 0 {
				b = append(b, ", "...)
			}
			b = ref.appendCode(b)
			refs = append(refs, ref)
		}
		b = append(b, "),\n"...)
		entries = append(entries, namespacePaths{namespace, refs})
	}

	return string(append(b, ");\n"...)), entries, nil
}

// classmap builds autoload_classmap.php and autoload_static.php's class
// map, in parallel chunks of classes (deliberate deviation 3, speed).
func (d *dump) classmap(classMap *classmap.ClassMap) error {
	d.classes = classMap.Classes()
	paths := make([]string, 0, len(d.classes))
	for _, path := range classMap.Map() {
		paths = append(paths, path)
	}
	d.classPaths = make([]pathRef, len(d.classes))

	// The static class map is exported in chunks when no strtr() match
	// can span two entries' lines (no replaced text holds a newline).
	// Otherwise, or when the replacements fail, staticFile exports it
	// whole (and fails the same way).
	var replacements map[string]string
	static := len(d.classes) > 0
	if static {
		var err error
		replacements, err = d.staticReplacements()
		static = err == nil
	}
	for k := range replacements {
		if strings.Contains(k, "\n") {
			static = false
		}
	}

	type chunk struct {
		classmapFile, staticClassMap []byte
		err                          error
	}
	chunks := make([]chunk, (len(d.classes)+classmapChunk-1)/classmapChunk)
	parallelChunks(len(chunks), func(c int) {
		lo, hi := c*classmapChunk, min((c+1)*classmapChunk, len(d.classes))
		b := make([]byte, 0, (hi-lo)*128)
		for i := lo; i < hi; i++ {
			ref, err := d.pathRef(paths[i])
			if err != nil {
				chunks[c].err = err

				return
			}
			d.classPaths[i] = ref
			b = append(b, "    "...)
			b = php.AppendVarExport(b, d.classes[i])
			b = append(b, " => "...)
			b = ref.appendCode(b)
			b = append(b, ",\n"...)
		}
		chunks[c].classmapFile = b
		if static {
			chunks[c].staticClassMap = d.staticClassMapChunk(lo, hi, replacements)
		}
	})

	// the first failing class's error, as a loop over them would return
	b := d.appendHeader("autoload_classmap.php")
	n := len(b) + len(");\n")
	for _, c := range chunks {
		if c.err != nil {
			return c.err
		}
		n += len(c.classmapFile)
	}
	b = slices.Grow(b, n-len(b))
	for _, c := range chunks {
		b = append(b, c.classmapFile...)
	}
	d.classmapFile = string(append(b, ");\n"...))

	if static {
		// what staticProperty makes of var_export's first and last lines
		head, tail := indentExport("array (\n"), appendIndented(nil, ")")
		n := len(head) + len(tail)
		for _, c := range chunks {
			n += len(c.staticClassMap)
		}
		b := make([]byte, 0, n)
		b = append(b, head...)
		for _, c := range chunks {
			b = append(b, c.staticClassMap...)
		}
		d.staticClassMap = string(append(b, tail...))
	}

	return nil
}

// classmapChunk is the number of classes per chunk the class map files
// are built in.
const classmapChunk = 512

// parallelChunks runs fn(0..n-1) on up to GOMAXPROCS goroutines.
func parallelChunks(n int, fn func(i int)) {
	workers := min(runtime.GOMAXPROCS(0), n)
	if workers <= 1 {
		for i := range n {
			fn(i)
		}

		return
	}
	var next atomic.Int64
	var wg sync.WaitGroup
	for range workers {
		wg.Go(func() {
			for {
				i := int(next.Add(1) - 1)
				if i >= n {
					return
				}
				fn(i)
			}
		})
	}
	wg.Wait()
}

// staticClassMapChunk is the part of staticProperty(staticClassMapValue(),
// replacements) that holds the entries of classes lo to hi-1: their lines
// of var_export's output, strtr()ed and re-indented as in the whole, since
// var_export puts each entry on its own line, the re-indent works line by
// line and no strtr() match spans lines.
func (d *dump) staticClassMapChunk(lo, hi int, replacements map[string]string) []byte {
	// var_export's lines for these entries (the array's keys are the
	// classes as PHP keys)
	b := make([]byte, 0, (hi-lo)*160)
	for i := lo; i < hi; i++ {
		b = append(b, "  "...)
		if k := php.StrKey(d.classes[i]); k.IsInt() {
			b = strconv.AppendInt(b, k.Int(), 10)
		} else {
			b = php.AppendVarExport(b, d.classes[i])
		}
		b = append(b, " => "...)
		b = php.AppendVarExport(b, d.classPaths[i].value(d.vendorDir, d.baseDir))
		b = append(b, ",\n"...)
	}
	replaced := php.StrtrPairs(string(b), replacements)

	return appendIndented(b[:0], replaced)
}

// staticClassMapValue is the class loader's classMap as getStaticFile
// sees it: what autoload_classmap.php returns.
func (d *dump) staticClassMapValue() *php.Array {
	classMap := php.NewArrayCap(len(d.classes))
	for i, class := range d.classes {
		classMap.Set(class, d.classPaths[i].value(d.vendorDir, d.baseDir))
	}

	return classMap
}

// targetDirLoader returns the autoload() method of the root package's
// target-dir loader, or "" for none.
func (d *dump) targetDirLoader(rootPackage pkg.RootPackageInterface) (string, error) {
	targetDir := rootPackage.TargetDir()
	psr0, _ := rootPackage.Autoload().Get("psr-0")
	if !php.ToBool(targetDir.Value()) || !php.ToBool(psr0) {
		return "", nil
	}
	rules, ok := psr0.(*php.Array)
	if !ok {
		return "", &php.EngineError{Class: "TypeError", Message: "array_keys(): Argument #1 ($array) must be of type array, " + php.ZvalValueName(psr0) + " given"}
	}

	levels := strings.Count(fspath.NormalizePath(targetDir.S), "/") + 1
	prefixes := make([]string, 0, rules.Len())
	for prefix := range rules.All() {
		prefixes = append(prefixes, php.VarExport(prefix.Value()))
	}
	baseDirFromTargetDirCode, err := util.FindShortestPathCode(d.targetDir, d.basePath, true, false, false)
	if err != nil {
		return "", err
	}

	return `
    public static function autoload($class)
    {
        $dir = ` + baseDirFromTargetDirCode + ` . '/';
        $prefixes = array(` + strings.Join(prefixes, ", ") + `);
        foreach ($prefixes as $prefix) {
            if (0 !== strpos($class, $prefix)) {
                continue;
            }
            $path = $dir . implode('/', array_slice(explode('\\', $class), ` + strconv.Itoa(levels) + `)).'.php';
            if (!$path = stream_resolve_include_path($path)) {
                return false;
            }
            require $path;

            return true;
        }
    }
`, nil
}

// psrScan is one ScanPaths call of the PSR-0/4 scan.
type psrScan struct {
	dir       string
	excluded  classmap.Matcher
	typ       classmap.AutoloadType
	namespace string
}

// psrScans lists the scans that add the classes of the PSR-0/4
// directories to the class map, in order.
func (d *dump) psrScans(autoloads *Autoloads, excluded []string) []psrScan {
	type group struct {
		paths *php.Array
		typ   classmap.AutoloadType
	}
	// namespacesToScan maps namespaces to indexes into groups.
	namespacesToScan := php.NewArray()
	var groups [][]group
	for _, psr := range [2]struct {
		rules *php.Array
		typ   classmap.AutoloadType
	}{{autoloads.PSR4, classmap.PSR4}, {autoloads.PSR0, classmap.PSR0}} {
		for namespace, paths := range psr.rules.All() {
			v, ok := namespacesToScan.GetKey(namespace)
			i, _ := v.(int64)
			if !ok {
				i = int64(len(groups))
				namespacesToScan.SetKey(namespace, i)
				groups = append(groups, nil)
			}
			list, _ := paths.(*php.Array)
			groups[i] = append(groups[i], group{list, psr.typ})
		}
	}

	php.Krsort(namespacesToScan, 0)

	var scans []psrScan
	for namespace, v := range namespacesToScan.All() {
		i, _ := v.(int64)
		for _, group := range groups[i] {
			for _, v := range group.paths.Values() {
				dir := php.ToString(v)
				if !fspath.IsAbsolutePath(dir) {
					dir = d.basePath + "/" + dir
				}
				dir = fspath.NormalizePath(dir)
				if fi, err := os.Stat(dir); err != nil || !fi.IsDir() {
					continue
				}

				// if the vendor dir is contained within a psr-0/psr-4 dir
				// being scanned we exclude it
				dirExcluded := excluded
				if strings.Contains(d.vendorPath, dir+"/") {
					dirExcluded = append(slices.Clip(excluded), d.vendorPath+"/")
				}

				scans = append(scans, psrScan{dir, d.exclusions.build(dir, dirExcluded), group.typ, namespace.String()})
			}
		}
	}

	return scans
}

// includePathsFile ports getIncludePathsFile ("" for null).
func (d *dump) includePathsFile(packageMap []PackageMapEntry) (string, error) {
	var b []byte
	for _, item := range packageMap {
		// packages that are not installed cannot autoload anything
		if !item.Installed {
			continue
		}
		p, installPath := item.Package, item.InstallPath

		if targetDir := p.TargetDir(); targetDir.Valid && targetDir.S != "" {
			installPath = php.SubstrLen(installPath, 0, -len("/"+targetDir.S))
		}

		for _, v := range p.IncludePaths().Values() {
			str, ok := v.(string)
			if !ok {
				// trim(string $string) under strict_types
				return "", typeError("trim", php.ZvalValueName(v))
			}
			includePath := php.TrimSet(str, "/")
			if installPath != "" {
				includePath = installPath + "/" + includePath
			}
			ref, err := d.pathRef(includePath)
			if err != nil {
				return "", err
			}
			b = append(b, "    "...)
			b = ref.appendCode(b)
			b = append(b, ",\n"...)
		}
	}

	if b == nil {
		return "", nil
	}

	return string(append(append(d.appendHeader("include_paths.php"), b...), ");\n"...)), nil
}

// includeFilesFile ports getIncludeFilesFile ("" for null), warning about
// files included more than once.
func (g *Generator) includeFilesFile(d *dump, files *php.Array) (string, error) {
	// Get the path to each file, and make sure these paths are unique.
	codes := make([]string, 0, files.Len())
	refs := make([]pathRef, 0, files.Len())
	seen := make(map[string]bool, files.Len())
	var duplicates []string
	for _, v := range files.All() {
		ref, err := d.pathRef(php.ToString(v))
		if err != nil {
			return "", err
		}
		code := ref.code()
		codes = append(codes, code)
		refs = append(refs, ref)
		if seen[code] {
			duplicates = append(duplicates, code)
		}
		seen[code] = true
	}
	if duplicates != nil {
		g.io.WriteError(`<warning>The following "files" autoload rules are included multiple times, this may cause issues and should be resolved:</warning>`, true, io.Normal)
		reported := map[string]bool{}
		for _, duplicate := range duplicates {
			if !reported[duplicate] {
				reported[duplicate] = true
				g.io.WriteError("<warning> - "+duplicate+"</warning>", true, io.Normal)
			}
		}
	}

	if len(codes) == 0 {
		return "", nil
	}

	b := d.appendHeader("autoload_files.php")
	d.files = php.NewArrayCap(files.Len())
	i := 0
	for fileIdentifier := range files.All() {
		b = append(b, "    "...)
		b = php.AppendVarExport(b, fileIdentifier.Value())
		b = append(b, " => "...)
		b = append(b, codes[i]...)
		b = append(b, ",\n"...)
		d.files.SetKey(fileIdentifier, refs[i].value(d.vendorDir, d.baseDir))
		i++
	}

	return string(append(b, ");\n"...)), nil
}

// autoloadFile ports getAutoloadFile: vendor/autoload.php.
func autoloadFile(vendorPathToTargetDirCode, suffix string) string {
	if last := vendorPathToTargetDirCode[len(vendorPathToTargetDirCode)-1]; last == '\'' || last == '"' {
		vendorPathToTargetDirCode = vendorPathToTargetDirCode[:len(vendorPathToTargetDirCode)-1] + "/autoload_real.php" + string(last)
	} else {
		vendorPathToTargetDirCode += " . '/autoload_real.php'"
	}

	return `<?php

// autoload.php @generated by Composer

if (PHP_VERSION_ID < 50600) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    $err = 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, $err);
        } elseif (!headers_sent()) {
            echo $err;
        }
    }
    throw new RuntimeException($err);
}

require_once ` + vendorPathToTargetDirCode + `;

return ComposerAutoloaderInit` + suffix + `::getLoader();
`
}

// autoloadRealFile ports getAutoloadRealFile: vendor/composer/autoload_real.php.
func (g *Generator) autoloadRealFile(useIncludePath bool, targetDirLoader string, useIncludeFiles bool, suffix string, useGlobalIncludePath, prependAutoloader, checkPlatform bool) string {
	prepend := "false"
	if prependAutoloader {
		prepend = "true"
	}

	var b strings.Builder
	b.WriteString(`<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit` + suffix + `
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

`)

	if checkPlatform {
		b.WriteString(`        require __DIR__ . '/platform_check.php';

`)
	}

	b.WriteString(`        spl_autoload_register(array('ComposerAutoloaderInit` + suffix + `', 'loadClassLoader'), true, ` + prepend + `);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit` + suffix + `', 'loadClassLoader'));

`)

	if useIncludePath {
		b.WriteString(`        $includePaths = require __DIR__ . '/include_paths.php';
        $includePaths[] = get_include_path();
        set_include_path(implode(PATH_SEPARATOR, $includePaths));

`)
	}

	// keeping PHP 5.6+ compatibility for the autoloader here by using
	// call_user_func vs getInitializer()()
	b.WriteString(`        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInit` + suffix + `::getInitializer($loader));

`)

	if g.classMapAuthoritative {
		b.WriteString("        $loader->setClassMapAuthoritative(true);\n")
	}

	if g.apcu {
		prefix := ""
		if g.apcuPrefix != nil {
			prefix = *g.apcuPrefix
		} else {
			prefix = php.RandomHex(10)
		}
		b.WriteString("        $loader->setApcuPrefix(" + php.VarExport(prefix) + ");\n")
	}

	if useGlobalIncludePath {
		b.WriteString("        $loader->setUseIncludePath(true);\n")
	}

	if targetDirLoader != "" {
		b.WriteString(`        spl_autoload_register(array('ComposerAutoloaderInit` + suffix + `', 'autoload'), true, true);

`)
	}

	b.WriteString("        $loader->register(" + prepend + ");\n\n")

	if useIncludeFiles {
		b.WriteString(`        $filesToLoad = \Composer\Autoload\ComposerStaticInit` + suffix + `::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

`)
	}

	b.WriteString("        return $loader;\n    }\n")
	b.WriteString(targetDirLoader)
	b.WriteString("}\n")

	return b.String()
}

// staticFile ports getStaticFile: vendor/composer/autoload_static.php, the
// properties a ClassLoader has after loading autoload_namespaces.php,
// autoload_psr4.php, autoload_classmap.php and autoload_files.php, as code.
func (d *dump) staticFile(suffix string) (string, error) {
	loader := NewClassLoader("")

	for _, entry := range d.psr0 {
		if err := loader.Set(entry.namespace, d.values(entry.paths)); err != nil {
			return "", err
		}
	}
	for _, entry := range d.psr4 {
		if err := loader.SetPsr4(entry.namespace, d.values(entry.paths)); err != nil {
			return "", err
		}
	}
	// the classMap, exported apart (classmap), is the only one the loader
	// holds
	replacements, err := d.staticReplacements()
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString(`<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit` + suffix + `
{
`)

	var initializer strings.Builder
	writeExported := func(name, exported string) {
		b.WriteString("    public static $" + name + " = ")
		b.WriteString(exported)
		b.WriteString(";\n\n")
		if name != "files" {
			initializer.WriteString("            $loader->" + name + " = ComposerStaticInit" + suffix + "::$" + name + ";\n")
		}
	}
	if d.files != nil {
		writeExported("files", staticProperty(d.files, replacements))
	}
	for _, prop := range loader.properties() {
		if prop.value.Len() > 0 {
			writeExported(prop.name, staticProperty(prop.value, replacements))
		}
	}
	if len(d.classes) > 0 {
		exported := d.staticClassMap
		if exported == "" {
			exported = staticProperty(d.staticClassMapValue(), replacements)
		}
		writeExported("classMap", exported)
	}

	b.WriteString(`    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
` + initializer.String() + `
        }, null, ClassLoader::class);
    }
}
`)

	return b.String(), nil
}

// staticProperty is a static property's value in autoload_static.php:
// var_export()ed, with the absolute paths turned into code, re-indented.
func staticProperty(value *php.Array, replacements map[string]string) string {
	return indentExport(php.StrtrPairs(php.VarExport(value), replacements))
}

// staticReplacements are getStaticFile's strtr() pairs: the absolute
// vendor and base dirs (also as phar://) as found in var_export()ed
// paths, and the code for them relative to __DIR__.
func (d *dump) staticReplacements() (map[string]string, error) {
	staticCode := func(to string, phar bool) (string, error) {
		code, err := util.FindShortestPathCode(d.realTarget, to, true, true, false)
		if err != nil {
			return "", err
		}
		if phar {
			return " => 'phar://' . " + code + " . '/", nil
		}

		return " => " + code + " . '/", nil
	}
	absoluteCode := func(path string) string {
		code := php.VarExport(php.RtrimSet(path, `\/`) + "/")

		return " => " + code[:len(code)-1]
	}

	// The keys of strtr()'s array literal, a later equal key replacing an
	// earlier one's value.
	replacements := make(map[string]string, 4)
	for _, r := range [4]struct {
		absolute, to string
		phar         bool
	}{
		{absoluteCode(d.vendorDir), d.vendorPath, false},
		{absoluteCode("phar://" + d.vendorDir), d.vendorPath, true},
		{absoluteCode(d.baseDir), d.basePath, false},
		{absoluteCode("phar://" + d.baseDir), d.basePath, true},
	} {
		code, err := staticCode(r.to, r.phar)
		if err != nil {
			return nil, err
		}
		replacements[r.absolute] = code
	}

	return replacements, nil
}

// values evaluates path codes to the list of paths they stand for.
func (d *dump) values(refs []pathRef) *php.Array {
	a := php.NewArrayCap(len(refs))
	for _, ref := range refs {
		a.Append(ref.value(d.vendorDir, d.baseDir))
	}

	return a
}

// indentExport re-indents var_export output for a static property:
// ltrim(Preg::replace('/^ */m', '    $0$0', $value)) then
// Preg::replace('/ +$/m', "", $value). Each line's leading spaces are
// doubled plus four, trailing spaces before a newline or the end are
// dropped, then leading whitespace of the whole is trimmed.
func indentExport(s string) string {
	return php.Ltrim(string(appendIndented(make([]byte, 0, len(s)+len(s)/4), s)))
}

// appendIndented appends indentExport's result for s to dst, without the
// final ltrim.
func appendIndented(dst []byte, s string) []byte {
	start := len(dst)
	b := dst
	for lineStart := 0; ; {
		// ^ matches at the start and after each newline except a final one.
		n := 0
		for lineStart+n < len(s) && s[lineStart+n] == ' ' {
			n++
		}
		b = append(b, "    "...)
		for range 2 * n {
			b = append(b, ' ')
		}
		end := strings.IndexByte(s[lineStart+n:], '\n')
		if end < 0 {
			b = append(b, s[lineStart+n:]...)

			break
		}
		end += lineStart + n
		b = append(b, s[lineStart+n:end+1]...)
		lineStart = end + 1
		if lineStart == len(s) {
			break
		}
	}

	// / +$/m: spaces before each newline and at the end.
	out := b[:start]
	for i := start; i < len(b); {
		if b[i] != ' ' {
			out = append(out, b[i])
			i++

			continue
		}
		j := i
		for j < len(b) && b[j] == ' ' {
			j++
		}
		if j < len(b) && b[j] != '\n' {
			out = append(out, b[i:j]...)
		}
		i = j
	}

	return out
}
