// Ports AutoloadGenerator::getPlatformCheck
// (src/Composer/Autoload/AutoloadGenerator.php).

package autoload

import (
	"slices"
	"strconv"
	"strings"

	"github.com/stubbedev/maestro/internal/php"
	"github.com/stubbedev/maestro/internal/pkg"
	"github.com/stubbedev/maestro/internal/semver"
)

// {^ext-(.+)$}iD
var reExt = php.MustCompile(`{^ext-(.+)$}iD`)

// platformCheck ports getPlatformCheck: the contents of platform_check.php
// ("" for null). checkPlatform is the platform-check setting, true or
// "php-only".
func (g *Generator) platformCheck(packageMap []PackageMapEntry, checkPlatform any, devPackageNames []string) (string, error) {
	lowestPhpVersion := semver.ZeroBound()
	requiredPhp64bit := false
	requiredExtensions := php.NewArray()
	extensionProviders := map[string][]semver.ConstraintInterface{}

	for _, item := range packageMap {
		for _, link := range mergeLinks(item.Package.Replaces(), item.Package.Provides()) {
			m, err := reExt.Match(link.Target())
			if err != nil {
				return "", err
			}
			if m != nil {
				extensionProviders[m.Get(1)] = append(extensionProviders[m.Get(1)], link.Constraint())
			}
		}
	}

	for _, item := range packageMap {
		p := item.Package
		// skip dev dependencies platform requirements as platform-check
		// really should only be a production safeguard
		if slices.Contains(devPackageNames, p.Name()) {
			continue
		}

	links:
		for link := range p.Requires().Values() {
			target := link.Target()
			if g.platformRequirementFilter.IsIgnored(target) {
				continue
			}

			if target == "php" || target == "php-64bit" {
				lower := link.Constraint().LowerBound()
				greater, err := lower.CompareTo(lowestPhpVersion, ">")
				if err != nil {
					return "", err
				}
				if greater {
					lowestPhpVersion = lower
				}
			}

			if target == "php-64bit" {
				requiredPhp64bit = true
			}

			if checkPlatform != true {
				continue
			}
			m, err := reExt.Match(target)
			if err != nil {
				return "", err
			}
			if m == nil {
				continue
			}
			name := m.Get(1)
			// skip extension checks if they have a valid provider/replacer
			for _, provided := range extensionProviders[name] {
				if provided.Matches(link.Constraint()) {
					continue links
				}
			}

			if name == "zend-opcache" {
				name = "zend opcache"
			}

			extension := php.VarExport(name)
			if name == "pcntl" || name == "readline" {
				requiredExtensions.Set(extension, "PHP_SAPI !== 'cli' || extension_loaded("+extension+") || $missingExtensions[] = "+extension+";\n")
			} else {
				requiredExtensions.Set(extension, "extension_loaded("+extension+") || $missingExtensions[] = "+extension+";\n")
			}
		}
	}

	php.Ksort(requiredExtensions, 0)

	requiredPhp := ""
	if !lowestPhpVersion.IsZero() {
		operator := ">"
		if lowestPhpVersion.IsInclusive() {
			operator = ">="
		}
		requiredPhp = `
if (!(PHP_VERSION_ID ` + operator + " " + formatToPhpVersionID(lowestPhpVersion) + `)) {
    $issues[] = 'Your Composer dependencies require a PHP version "` + operator + " " + formatToHumanReadable(lowestPhpVersion) + `". You are running ' . PHP_VERSION . '.';
}
`
	}

	if requiredPhp64bit {
		requiredPhp += `
if (PHP_INT_SIZE !== 8) {
    $issues[] = 'Your Composer dependencies require a 64-bit build of PHP.';
}
`
	}

	var checks strings.Builder
	for _, check := range requiredExtensions.Values() {
		s, _ := check.(string)
		checks.WriteString(s)
	}
	extensionChecks := ""
	if checks.Len() > 0 {
		extensionChecks = `
$missingExtensions = array();
` + checks.String() + `
if ($missingExtensions) {
    $issues[] = 'Your Composer dependencies require the following PHP extensions to be installed: ' . implode(', ', $missingExtensions) . '.';
}
`
	}

	if requiredPhp == "" && extensionChecks == "" {
		return "", nil
	}

	return `<?php

// platform_check.php @generated by Composer

$issues = array();
` + requiredPhp + extensionChecks + `
if ($issues) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, 'Composer detected issues in your platform:' . PHP_EOL.PHP_EOL . implode(PHP_EOL, $issues) . PHP_EOL.PHP_EOL);
        } elseif (!headers_sent()) {
            echo 'Composer detected issues in your platform:' . PHP_EOL.PHP_EOL . str_replace('You are running '.PHP_VERSION.'.', '', implode(PHP_EOL, $issues)) . PHP_EOL.PHP_EOL;
        }
    }
    throw new \RuntimeException(
        'Composer detected issues in your platform: ' . implode(' ', $issues)
    );
}
`, nil
}

// mergeLinks is array_merge($a, $b) for link maps: a string key of b
// replaces a's link in place, int keys are appended.
func mergeLinks(a, b pkg.Links) []*pkg.Link {
	links := make([]*pkg.Link, 0, a.Len()+b.Len())
	for k, l := range a.All() {
		if !php.StrKey(k).IsInt() {
			if bl, ok := b.Get(k); ok {
				l = bl
			}
		}
		links = append(links, l)
	}
	for k, l := range b.All() {
		if php.StrKey(k).IsInt() || !a.Has(k) {
			links = append(links, l)
		}
	}

	return links
}

// formatToPhpVersionID turns a bound into a PHP_VERSION_ID.
func formatToPhpVersionID(bound semver.Bound) string {
	if bound.IsZero() {
		return "0"
	}
	if bound.IsPositiveInfinity() {
		return "99999"
	}

	chunks := strings.Split(strings.ReplaceAll(bound.Version(), "-", "."), ".")
	chunk := func(i int) int64 {
		if i < len(chunks) {
			return php.ToInt(chunks[i])
		}

		return 0
	}

	return strconv.FormatInt(chunk(0)*10000+chunk(1)*100+chunk(2), 10)
}

// formatToHumanReadable turns a bound into a version of at most three
// parts.
func formatToHumanReadable(bound semver.Bound) string {
	if bound.IsZero() {
		return "0"
	}
	if bound.IsPositiveInfinity() {
		return "99999"
	}

	chunks := strings.Split(strings.ReplaceAll(bound.Version(), "-", "."), ".")

	return strings.Join(chunks[:min(3, len(chunks))], ".")
}
