<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Version;

class VersionBumper
{
    public function bumpRequirement(\Composer\Semver\Constraint\ConstraintInterface $constraint, \Composer\Package\PackageInterface $package): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Version\\VersionBumper::bumpRequirement() in plugins yet');
    }
}
