<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Version;

class VersionSelector
{
    public function __construct(\Composer\Repository\RepositorySet $repositorySet, ?\Composer\Repository\PlatformRepository $platformRepo = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Version\\VersionSelector::__construct() in plugins yet');
    }

    public function findBestCandidate(string $packageName, ?string $targetPackageVersion = null, string $preferredStability = 'stable', $platformRequirementFilter = null, int $repoSetFlags = 0, ?\Composer\IO\IOInterface $io = null, $showWarnings = true)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Version\\VersionSelector::findBestCandidate() in plugins yet');
    }

    public function findRecommendedRequireVersion(\Composer\Package\PackageInterface $package): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Version\\VersionSelector::findRecommendedRequireVersion() in plugins yet');
    }
}
