<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Version;

class VersionGuesser
{
    public function __construct(\Composer\Config $config, \Composer\Util\ProcessExecutor $process, \Composer\Semver\VersionParser $versionParser, ?\Composer\IO\IOInterface $io = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Version\\VersionGuesser::__construct() in plugins yet');
    }

    public function getRootVersionFromEnv(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Version\\VersionGuesser::getRootVersionFromEnv() in plugins yet');
    }

    public function guessVersion(array $packageConfig, string $path): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Version\\VersionGuesser::guessVersion() in plugins yet');
    }
}
