<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Version;

class VersionParser extends \Composer\Semver\VersionParser
{
    public const DEFAULT_BRANCH_ALIAS = '9999999-dev';

    public static function isUpgrade(string $normalizedFrom, string $normalizedTo): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Version\\VersionParser::isUpgrade() in plugins yet');
    }

    public function parseConstraints($constraints): \Composer\Semver\Constraint\ConstraintInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Version\\VersionParser::parseConstraints() in plugins yet');
    }

    public function parseNameVersionPairs(array $pairs): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Version\\VersionParser::parseNameVersionPairs() in plugins yet');
    }
}
