<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Filter\PlatformRequirementFilter;

final class IgnoreListPlatformRequirementFilter implements \Composer\Filter\PlatformRequirementFilter\PlatformRequirementFilterInterface
{
    public function __construct(array $reqList)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Filter\\PlatformRequirementFilter\\IgnoreListPlatformRequirementFilter::__construct() in plugins yet');
    }

    public function filterConstraint(string $req, \Composer\Semver\Constraint\ConstraintInterface $constraint, bool $allowUpperBoundOverride = true): \Composer\Semver\Constraint\ConstraintInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Filter\\PlatformRequirementFilter\\IgnoreListPlatformRequirementFilter::filterConstraint() in plugins yet');
    }

    public function isIgnored(string $req): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Filter\\PlatformRequirementFilter\\IgnoreListPlatformRequirementFilter::isIgnored() in plugins yet');
    }

    public function isUpperBoundIgnored(string $req): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Filter\\PlatformRequirementFilter\\IgnoreListPlatformRequirementFilter::isUpperBoundIgnored() in plugins yet');
    }
}
