<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Filter\PlatformRequirementFilter;

final class IgnoreAllPlatformRequirementFilter implements \Composer\Filter\PlatformRequirementFilter\PlatformRequirementFilterInterface
{
    public function isIgnored(string $req): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Filter\\PlatformRequirementFilter\\IgnoreAllPlatformRequirementFilter::isIgnored() in plugins yet');
    }

    public function isUpperBoundIgnored(string $req): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Filter\\PlatformRequirementFilter\\IgnoreAllPlatformRequirementFilter::isUpperBoundIgnored() in plugins yet');
    }
}
