<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Platform;

class HhvmDetector
{
    public function __construct(?\Symfony\Component\Process\ExecutableFinder $executableFinder = null, ?\Composer\Util\ProcessExecutor $processExecutor = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Platform\\HhvmDetector::__construct() in plugins yet');
    }

    public function getVersion(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Platform\\HhvmDetector::getVersion() in plugins yet');
    }

    public function reset(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Platform\\HhvmDetector::reset() in plugins yet');
    }
}
