<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Platform;

class Version
{
    public static function convertLibxpmVersionId(int $versionId): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Platform\\Version::convertLibxpmVersionId() in plugins yet');
    }

    public static function convertOpenldapVersionId(int $versionId): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Platform\\Version::convertOpenldapVersionId() in plugins yet');
    }

    public static function parseLibjpeg(string $libjpegVersion): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Platform\\Version::parseLibjpeg() in plugins yet');
    }

    public static function parseOpenssl(string $opensslVersion, ?bool &$isFips): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Platform\\Version::parseOpenssl() in plugins yet');
    }

    public static function parseZoneinfoVersion(string $zoneinfoVersion): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Platform\\Version::parseZoneinfoVersion() in plugins yet');
    }
}
