<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver\Operation;

class MarkAliasUninstalledOperation extends \Composer\DependencyResolver\Operation\SolverOperation
{
    protected const TYPE = 'markAliasUninstalled';

    protected $package;

    public function __construct(\Composer\Package\AliasPackage $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Operation\\MarkAliasUninstalledOperation::__construct() in plugins yet');
    }

    public function getPackage(): \Composer\Package\AliasPackage
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Operation\\MarkAliasUninstalledOperation::getPackage() in plugins yet');
    }

    public function show($lock): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Operation\\MarkAliasUninstalledOperation::show() in plugins yet');
    }
}
