<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver\Operation;

class UninstallOperation extends \Composer\DependencyResolver\Operation\SolverOperation
{
    protected const TYPE = 'uninstall';

    protected $package;

    public function __construct(\Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Operation\\UninstallOperation::__construct() in plugins yet');
    }

    public static function format(\Composer\Package\PackageInterface $package, bool $lock = false): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Operation\\UninstallOperation::format() in plugins yet');
    }

    public function getPackage(): \Composer\Package\PackageInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Operation\\UninstallOperation::getPackage() in plugins yet');
    }

    public function show($lock): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Operation\\UninstallOperation::show() in plugins yet');
    }
}
