<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Autoload;

class ClassMapGenerator
{
    public static function createMap($path, ?string $excluded = null, ?\Composer\IO\IOInterface $io = null, ?string $namespace = null, ?string $autoloadType = null, array &$scannedFiles = []): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Autoload\\ClassMapGenerator::createMap() in plugins yet');
    }

    public static function dump(iterable $dirs, string $file): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Autoload\\ClassMapGenerator::dump() in plugins yet');
    }
}
