<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Command;

abstract class BaseDependencyCommand extends \Composer\Command\BaseCommand
{
    protected const ARGUMENT_CONSTRAINT = 'version';
    protected const ARGUMENT_PACKAGE = 'package';
    protected const OPTION_RECURSIVE = 'recursive';
    protected const OPTION_TREE = 'tree';

    protected $colors;

    protected function doExecute(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output, bool $inverted = false): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\BaseDependencyCommand::doExecute() in plugins yet');
    }

    protected function initStyles(\Symfony\Component\Console\Output\OutputInterface $output): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\BaseDependencyCommand::initStyles() in plugins yet');
    }

    protected function printTable(\Symfony\Component\Console\Output\OutputInterface $output, array $results): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\BaseDependencyCommand::printTable() in plugins yet');
    }

    protected function printTree(array $results, string $prefix = '', int $level = 1): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\BaseDependencyCommand::printTree() in plugins yet');
    }
}
