<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Command;

abstract class BaseConfigCommand extends \Composer\Command\BaseCommand
{
    protected $config;
    protected $configFile;
    protected $configSource;

    protected function getAuthConfigFile(\Symfony\Component\Console\Input\InputInterface $input, \Composer\Config $config): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\BaseConfigCommand::getAuthConfigFile() in plugins yet');
    }

    protected function getComposerConfigFile(\Symfony\Component\Console\Input\InputInterface $input, \Composer\Config $config): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\BaseConfigCommand::getComposerConfigFile() in plugins yet');
    }

    protected function initialize(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): void
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            \Maestro\Shim\Console::builtin($this, 'initialize', [$input, $output]);

            return;
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\BaseConfigCommand::initialize() in plugins yet');
    }
}
