<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Command;

class CreateProjectCommand extends \Composer\Command\BaseCommand
{
    use \Composer\Command\CompletionTrait;

    protected $suggestedPackagesReporter;

    protected function configure(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\CreateProjectCommand::configure() in plugins yet');
    }

    protected function execute(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): int
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Console::builtin($this, 'execute', [$input, $output]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\CreateProjectCommand::execute() in plugins yet');
    }

    public function installProject(\Composer\IO\IOInterface $io, \Composer\Config $config, \Symfony\Component\Console\Input\InputInterface $input, ?string $packageName = null, ?string $directory = null, ?string $packageVersion = null, ?string $stability = 'stable', bool $preferSource = false, bool $preferDist = false, bool $installDevPackages = false, $repositories = null, bool $disablePlugins = false, bool $disableScripts = false, bool $noProgress = false, bool $noInstall = false, ?\Composer\Filter\PlatformRequirementFilter\PlatformRequirementFilterInterface $platformRequirementFilter = null, bool $secureHttp = true, bool $addRepository = false, array $requiredPackages = []): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\CreateProjectCommand::installProject() in plugins yet');
    }

    protected function installRootPackage(\Symfony\Component\Console\Input\InputInterface $input, \Composer\IO\IOInterface $io, \Composer\Config $config, string $packageName, \Composer\Filter\PlatformRequirementFilter\PlatformRequirementFilterInterface $platformRequirementFilter, ?string $directory = null, ?string $packageVersion = null, ?string $stability = 'stable', bool $preferSource = false, bool $preferDist = false, bool $installDevPackages = false, ?array $repositories = null, bool $disablePlugins = false, bool $disableScripts = false, bool $noProgress = false, bool $secureHttp = true): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\CreateProjectCommand::installRootPackage() in plugins yet');
    }
}
