<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Command;

class GlobalCommand extends \Composer\Command\BaseCommand
{
    public function complete(\Symfony\Component\Console\Completion\CompletionInput $input, \Symfony\Component\Console\Completion\CompletionSuggestions $suggestions): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\GlobalCommand::complete() in plugins yet');
    }

    protected function configure(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\GlobalCommand::configure() in plugins yet');
    }

    public function isProxyCommand(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\GlobalCommand::isProxyCommand() in plugins yet');
    }

    public function run(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\GlobalCommand::run() in plugins yet');
    }
}
