<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Command;

class InitCommand extends \Composer\Command\BaseCommand
{
    use \Composer\Command\CompletionTrait;
    use \Composer\Command\PackageDiscoveryTrait;

    protected function addVendorIgnore(string $ignoreFile, string $vendor = '/vendor/'): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\InitCommand::addVendorIgnore() in plugins yet');
    }

    protected function configure(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\InitCommand::configure() in plugins yet');
    }

    protected function execute(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): int
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Console::builtin($this, 'execute', [$input, $output]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\InitCommand::execute() in plugins yet');
    }

    protected function formatAuthors(string $author): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\InitCommand::formatAuthors() in plugins yet');
    }

    protected function getGitConfig(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\InitCommand::getGitConfig() in plugins yet');
    }

    protected function hasVendorIgnore(string $ignoreFile, string $vendor = 'vendor'): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\InitCommand::hasVendorIgnore() in plugins yet');
    }

    protected function initialize(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): void
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            \Maestro\Shim\Console::builtin($this, 'initialize', [$input, $output]);

            return;
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\InitCommand::initialize() in plugins yet');
    }

    protected function interact(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): void
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            \Maestro\Shim\Console::builtin($this, 'interact', [$input, $output]);

            return;
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\InitCommand::interact() in plugins yet');
    }

    protected function isValidEmail(string $email): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\InitCommand::isValidEmail() in plugins yet');
    }

    public function namespaceFromPackageName(string $packageName): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\InitCommand::namespaceFromPackageName() in plugins yet');
    }
}
