<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Command;

trait PackageDiscoveryTrait
{
    final protected function determineRequirements(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output, array $requires = [], ?\Composer\Repository\PlatformRepository $platformRepo = null, string $preferredStability = 'stable', bool $useBestVersionConstraint = true, bool $fixed = false): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\PackageDiscoveryTrait::determineRequirements() in plugins yet');
    }

    protected function getRepos(): \Composer\Repository\CompositeRepository
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\PackageDiscoveryTrait::getRepos() in plugins yet');
    }
}
