<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Command;

class RequireCommand extends \Composer\Command\BaseCommand
{
    use \Composer\Command\CompletionTrait;
    use \Composer\Command\PackageDiscoveryTrait;

    protected function configure(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\RequireCommand::configure() in plugins yet');
    }

    protected function execute(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): int
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Console::builtin($this, 'execute', [$input, $output]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\RequireCommand::execute() in plugins yet');
    }

    protected function interact(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): void
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            \Maestro\Shim\Console::builtin($this, 'interact', [$input, $output]);

            return;
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\RequireCommand::interact() in plugins yet');
    }
}
