<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Command;

class RunScriptCommand extends \Composer\Command\BaseCommand
{
    protected $scriptEvents = ['pre-install-cmd', 'post-install-cmd', 'pre-update-cmd', 'post-update-cmd', 'pre-status-cmd', 'post-status-cmd', 'post-root-package-install', 'post-create-project-cmd', 'pre-archive-cmd', 'post-archive-cmd', 'pre-autoload-dump', 'post-autoload-dump'];

    protected function configure(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\RunScriptCommand::configure() in plugins yet');
    }

    protected function execute(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): int
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Console::builtin($this, 'execute', [$input, $output]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\RunScriptCommand::execute() in plugins yet');
    }

    protected function interact(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): void
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            \Maestro\Shim\Console::builtin($this, 'interact', [$input, $output]);

            return;
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\RunScriptCommand::interact() in plugins yet');
    }

    protected function listScripts(\Symfony\Component\Console\Output\OutputInterface $output): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\RunScriptCommand::listScripts() in plugins yet');
    }
}
