<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Command;

class ScriptAliasCommand extends \Composer\Command\BaseCommand
{
    public function __construct(string $script, ?string $description, array $aliases = [])
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ScriptAliasCommand::__construct() in plugins yet');
    }

    protected function configure(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ScriptAliasCommand::configure() in plugins yet');
    }

    protected function execute(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): int
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Console::builtin($this, 'execute', [$input, $output]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ScriptAliasCommand::execute() in plugins yet');
    }
}
