<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Command;

class ShowCommand extends \Composer\Command\BaseCommand
{
    use \Composer\Command\CompletionTrait;

    protected $colors;
    protected $versionParser;

    protected function addTree(string $name, \Composer\Package\Link $link, \Composer\Repository\InstalledRepository $installedRepo, \Composer\Repository\RepositoryInterface $remoteRepos, array $packagesInTree): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::addTree() in plugins yet');
    }

    protected function configure(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::configure() in plugins yet');
    }

    protected function displayPackageTree(array $arrayTree): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::displayPackageTree() in plugins yet');
    }

    protected function displayTree($package, array $packagesInTree, string $previousTreeBar = '├', int $level = 1): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::displayTree() in plugins yet');
    }

    protected function execute(\Symfony\Component\Console\Input\InputInterface $input, \Symfony\Component\Console\Output\OutputInterface $output): int
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Console::builtin($this, 'execute', [$input, $output]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::execute() in plugins yet');
    }

    protected function generatePackageTree(\Composer\Package\PackageInterface $package, \Composer\Repository\InstalledRepository $installedRepo, \Composer\Repository\RepositoryInterface $remoteRepos): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::generatePackageTree() in plugins yet');
    }

    protected function getPackage(\Composer\Repository\InstalledRepository $installedRepo, \Composer\Repository\RepositoryInterface $repos, string $name, $version = null): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::getPackage() in plugins yet');
    }

    protected function getRootRequires(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::getRootRequires() in plugins yet');
    }

    protected function getVersionStyle(\Composer\Package\PackageInterface $latestPackage, \Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::getVersionStyle() in plugins yet');
    }

    protected function initStyles(\Symfony\Component\Console\Output\OutputInterface $output): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::initStyles() in plugins yet');
    }

    protected function printLicenses(\Composer\Package\CompletePackageInterface $package): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::printLicenses() in plugins yet');
    }

    protected function printLinks(\Composer\Package\CompletePackageInterface $package, string $linkType, ?string $title = null): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::printLinks() in plugins yet');
    }

    protected function printMeta(\Composer\Package\CompletePackageInterface $package, array $versions, \Composer\Repository\InstalledRepository $installedRepo, ?\Composer\Package\PackageInterface $latestPackage = null): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::printMeta() in plugins yet');
    }

    protected function printPackageInfo(\Composer\Package\CompletePackageInterface $package, array $versions, \Composer\Repository\InstalledRepository $installedRepo, ?\Composer\Package\PackageInterface $latestPackage = null): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::printPackageInfo() in plugins yet');
    }

    protected function printPackageInfoAsJson(\Composer\Package\CompletePackageInterface $package, array $versions, \Composer\Repository\InstalledRepository $installedRepo, ?\Composer\Package\PackageInterface $latestPackage = null): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::printPackageInfoAsJson() in plugins yet');
    }

    protected function printVersions(\Composer\Package\CompletePackageInterface $package, array $versions, \Composer\Repository\InstalledRepository $installedRepo): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::printVersions() in plugins yet');
    }

    protected function suggestPackageBasedOnMode(): \Closure
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Command\\ShowCommand::suggestPackageBasedOnMode() in plugins yet');
    }
}
