<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

class Bitbucket
{
    public const OAUTH2_ACCESS_TOKEN_URL = 'https://bitbucket.org/site/oauth2/access_token';

    public function __construct(\Composer\IO\IOInterface $io, \Composer\Config $config, ?\Composer\Util\ProcessExecutor $process = null, ?\Composer\Util\HttpDownloader $httpDownloader = null, ?int $time = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Bitbucket::__construct() in plugins yet');
    }

    public function authorizeOAuth(string $originUrl): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Bitbucket::authorizeOAuth() in plugins yet');
    }

    public function authorizeOAuthInteractively(string $originUrl, ?string $message = null): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Bitbucket::authorizeOAuthInteractively() in plugins yet');
    }

    public function getToken(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Bitbucket::getToken() in plugins yet');
    }

    public function requestToken(string $originUrl, string $consumerKey, string $consumerSecret): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Bitbucket::requestToken() in plugins yet');
    }
}
