<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

class ComposerMirror
{
    public static function processGitUrl(string $mirrorUrl, string $packageName, string $url, ?string $type): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\ComposerMirror::processGitUrl() in plugins yet');
    }

    public static function processHgUrl(string $mirrorUrl, string $packageName, string $url, string $type): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\ComposerMirror::processHgUrl() in plugins yet');
    }

    public static function processUrl(string $mirrorUrl, string $packageName, string $version, ?string $reference, ?string $type, ?string $prettyVersion = null): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\ComposerMirror::processUrl() in plugins yet');
    }
}
