<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

class ConfigValidator
{
    public const CHECK_VERSION = 1;

    public function __construct(\Composer\IO\IOInterface $io)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\ConfigValidator::__construct() in plugins yet');
    }

    public function validate(string $file, int $arrayLoaderValidationFlags = \Composer\Package\Loader\ValidatingArrayLoader::CHECK_ALL, int $flags = self::CHECK_VERSION): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\ConfigValidator::validate() in plugins yet');
    }
}
