<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

class Filesystem
{
    public function __construct(?\Composer\Util\ProcessExecutor $executor = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::__construct() in plugins yet');
    }

    public function copy(string $source, string $target)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::copy() in plugins yet');
    }

    public function copyThenRemove(string $source, string $target)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::copyThenRemove() in plugins yet');
    }

    protected function directorySize(string $directory)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::directorySize() in plugins yet');
    }

    public function emptyDirectory(string $dir, bool $ensureDirectoryExists = true)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::emptyDirectory() in plugins yet');
    }

    public function ensureDirectoryExists(string $directory)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::ensureDirectoryExists() in plugins yet');
    }

    public function filePutContentsIfModified(string $path, string $content)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::filePutContentsIfModified() in plugins yet');
    }

    public function findShortestPath(string $from, string $to, bool $directories = false, bool $preferRelative = false)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::findShortestPath() in plugins yet');
    }

    public function findShortestPathCode(string $from, string $to, bool $directories = false, bool $staticCode = false, bool $preferRelative = false)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::findShortestPathCode() in plugins yet');
    }

    public static function getPlatformPath(string $path)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::getPlatformPath() in plugins yet');
    }

    protected function getProcess()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::getProcess() in plugins yet');
    }

    public function isAbsolutePath(string $path)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::isAbsolutePath() in plugins yet');
    }

    public function isDirEmpty(string $dir)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::isDirEmpty() in plugins yet');
    }

    public function isJunction(string $junction)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::isJunction() in plugins yet');
    }

    public static function isLocalPath(string $path)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::isLocalPath() in plugins yet');
    }

    public static function isReadable(string $path)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::isReadable() in plugins yet');
    }

    public function isSymlinkedDirectory(string $directory)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::isSymlinkedDirectory() in plugins yet');
    }

    public function junction(string $target, string $junction)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::junction() in plugins yet');
    }

    public function normalizePath(string $path)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::normalizePath() in plugins yet');
    }

    public function relativeSymlink(string $target, string $link)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::relativeSymlink() in plugins yet');
    }

    public function remove(string $file)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::remove() in plugins yet');
    }

    public function removeDirectory(string $directory)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::removeDirectory() in plugins yet');
    }

    public function removeDirectoryAsync(string $directory)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::removeDirectoryAsync() in plugins yet');
    }

    public function removeDirectoryPhp(string $directory)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::removeDirectoryPhp() in plugins yet');
    }

    public function removeJunction(string $junction)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::removeJunction() in plugins yet');
    }

    public function rename(string $source, string $target)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::rename() in plugins yet');
    }

    public function rmdir(string $path)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::rmdir() in plugins yet');
    }

    public function safeCopy(string $source, string $target): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::safeCopy() in plugins yet');
    }

    public function size(string $path)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::size() in plugins yet');
    }

    public static function trimTrailingSlash(string $path)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::trimTrailingSlash() in plugins yet');
    }

    public function unlink(string $path)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Filesystem::unlink() in plugins yet');
    }
}
