<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

final class ForgejoUrl
{
    public const URL_REGEX = '{^(?:(?:https?|git)://([^/]+)/|git@([^:]+):/?)([^/]+)/([^/]+?)(?:\\.git|/)?$}';

    public $apiUrl;
    public $originUrl;
    public $owner;
    public $repository;

    public static function create(string $repoUrl): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\ForgejoUrl::create() in plugins yet');
    }

    public function generateSshUrl(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\ForgejoUrl::generateSshUrl() in plugins yet');
    }

    public static function tryFrom(?string $repoUrl): ?self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\ForgejoUrl::tryFrom() in plugins yet');
    }
}
