<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

final class Forgejo
{
    public function __construct(\Composer\IO\IOInterface $io, \Composer\Config $config, \Composer\Util\HttpDownloader $httpDownloader)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Forgejo::__construct() in plugins yet');
    }

    public function authorizeOAuthInteractively(string $originUrl, ?string $message = null): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Forgejo::authorizeOAuthInteractively() in plugins yet');
    }
}
