<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

class Hg
{
    public function __construct(\Composer\IO\IOInterface $io, \Composer\Config $config, \Composer\Util\ProcessExecutor $process)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Hg::__construct() in plugins yet');
    }

    public static function getVersion(\Composer\Util\ProcessExecutor $process): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Hg::getVersion() in plugins yet');
    }

    public function runCommand(callable $commandCallable, string $url, ?string $cwd): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Hg::runCommand() in plugins yet');
    }
}
