<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

class HttpDownloader
{
    public function __construct(\Composer\IO\IOInterface $io, \Composer\Config $config, array $options = [], bool $disableTls = false)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::__construct() in plugins yet');
    }

    public function add(string $url, array $options = [])
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::add() in plugins yet');
    }

    public function addCopy(string $url, string $to, array $options = [])
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::addCopy() in plugins yet');
    }

    public function copy(string $url, string $to, array $options = [])
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::copy() in plugins yet');
    }

    public function countActiveJobs(?int $index = null): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::countActiveJobs() in plugins yet');
    }

    public function enableAsync(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::enableAsync() in plugins yet');
    }

    public function get(string $url, array $options = [])
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::get() in plugins yet');
    }

    public static function getExceptionHints(\Throwable $e): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::getExceptionHints() in plugins yet');
    }

    public function getOptions()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::getOptions() in plugins yet');
    }

    public static function isCurlEnabled(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::isCurlEnabled() in plugins yet');
    }

    public static function outputWarnings(\Composer\IO\IOInterface $io, string $url, $data): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::outputWarnings() in plugins yet');
    }

    public function setOptions(array $options)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::setOptions() in plugins yet');
    }

    public function wait(?int $index = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\HttpDownloader::wait() in plugins yet');
    }
}
