<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

class NoProxyPattern
{
    protected $hostNames = [];
    protected $noproxy;
    protected $rules = [];

    public function __construct(string $pattern)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\NoProxyPattern::__construct() in plugins yet');
    }

    protected function getUrlData(string $url)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\NoProxyPattern::getUrlData() in plugins yet');
    }

    protected function match(int $index, string $hostName, \stdClass $url): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\NoProxyPattern::match() in plugins yet');
    }

    protected function matchRange(\stdClass $network, \stdClass $target): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\NoProxyPattern::matchRange() in plugins yet');
    }

    public function test(string $url): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\NoProxyPattern::test() in plugins yet');
    }
}
