<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

class PackageInfo
{
    public static function getViewSourceOrHomepageUrl(\Composer\Package\PackageInterface $package): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\PackageInfo::getViewSourceOrHomepageUrl() in plugins yet');
    }

    public static function getViewSourceUrl(\Composer\Package\PackageInterface $package): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\PackageInfo::getViewSourceUrl() in plugins yet');
    }
}
