<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

class PackageSorter
{
    public static function getMostCurrentVersion(array $packages): ?\Composer\Package\PackageInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\PackageSorter::getMostCurrentVersion() in plugins yet');
    }

    public static function sortPackages(array $packages, array $weights = []): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\PackageSorter::sortPackages() in plugins yet');
    }

    public static function sortPackagesAlphabetically(array $packages): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\PackageSorter::sortPackagesAlphabetically() in plugins yet');
    }
}
