<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

class Perforce
{
    protected $commandResult;
    protected $filesystem;
    protected $io;
    protected $p4Branch;
    protected $p4Client;
    protected $p4ClientSpec;
    protected $p4Depot;
    protected $p4DepotType;
    protected $p4Password;
    protected $p4Port;
    protected $p4Stream;
    protected $p4User;
    protected $path;
    protected $process;
    protected $uniquePerforceClientName;
    protected $windowsFlag;

    public function __construct($repoConfig, string $port, string $path, \Composer\Util\ProcessExecutor $process, bool $isWindows, \Composer\IO\IOInterface $io)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::__construct() in plugins yet');
    }

    public static function checkServerExists(string $url, \Composer\Util\ProcessExecutor $processExecutor): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::checkServerExists() in plugins yet');
    }

    public function checkStream(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::checkStream() in plugins yet');
    }

    public function cleanupClientSpec(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::cleanupClientSpec() in plugins yet');
    }

    public function connectClient(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::connectClient() in plugins yet');
    }

    public static function create($repoConfig, string $port, string $path, \Composer\Util\ProcessExecutor $process, \Composer\IO\IOInterface $io): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::create() in plugins yet');
    }

    protected function executeCommand($command): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::executeCommand() in plugins yet');
    }

    public function generateP4Command(array $arguments, bool $useClient = true): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::generateP4Command() in plugins yet');
    }

    public function generateUniquePerforceClientName(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::generateUniquePerforceClientName() in plugins yet');
    }

    public function getBranches(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getBranches() in plugins yet');
    }

    protected function getChangeList(string $reference): mixed
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getChangeList() in plugins yet');
    }

    public function getClient(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getClient() in plugins yet');
    }

    public function getCommitLogs(string $fromReference, string $toReference): mixed
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getCommitLogs() in plugins yet');
    }

    public function getComposerInformation(string $identifier): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getComposerInformation() in plugins yet');
    }

    public function getFileContent(string $file, string $identifier): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getFileContent() in plugins yet');
    }

    public function getFilePath(string $file, string $identifier): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getFilePath() in plugins yet');
    }

    public function getFilesystem(): \Composer\Util\Filesystem
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getFilesystem() in plugins yet');
    }

    public function getP4ClientSpec(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getP4ClientSpec() in plugins yet');
    }

    protected function getP4variable(string $name): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getP4variable() in plugins yet');
    }

    protected function getPath(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getPath() in plugins yet');
    }

    protected function getPort(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getPort() in plugins yet');
    }

    public function getStream(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getStream() in plugins yet');
    }

    public function getStreamWithoutLabel(string $stream): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getStreamWithoutLabel() in plugins yet');
    }

    public function getTags(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getTags() in plugins yet');
    }

    public function getUser(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::getUser() in plugins yet');
    }

    public function initialize($repoConfig): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::initialize() in plugins yet');
    }

    public function initializeDepotAndBranch(?string $depot, ?string $branch): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::initializeDepotAndBranch() in plugins yet');
    }

    public function initializePath(string $path): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::initializePath() in plugins yet');
    }

    public function isLoggedIn(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::isLoggedIn() in plugins yet');
    }

    public function isStream(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::isStream() in plugins yet');
    }

    public static function isValidPort(string $url): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::isValidPort() in plugins yet');
    }

    public function p4Login(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::p4Login() in plugins yet');
    }

    public function queryP4Password(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::queryP4Password() in plugins yet');
    }

    public function queryP4User(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::queryP4User() in plugins yet');
    }

    protected function read($pipe, $name): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::read() in plugins yet');
    }

    public function setFilesystem(\Composer\Util\Filesystem $fs): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::setFilesystem() in plugins yet');
    }

    public function setStream(string $stream): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::setStream() in plugins yet');
    }

    public function setUser(?string $user): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::setUser() in plugins yet');
    }

    public function syncCodeBase(?string $sourceReference): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::syncCodeBase() in plugins yet');
    }

    public function windowsLogin(?string $password): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::windowsLogin() in plugins yet');
    }

    public function writeClientSpecToFile($spec): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::writeClientSpecToFile() in plugins yet');
    }

    public function writeP4ClientSpec(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Perforce::writeP4ClientSpec() in plugins yet');
    }
}
