<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

class Platform
{
    public static function assertPharMetadataSafe(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::assertPharMetadataSafe() in plugins yet');
    }

    public static function clearEnv(string $name): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::clearEnv() in plugins yet');
    }

    public static function expandPath(string $path): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::expandPath() in plugins yet');
    }

    public static function getBoolEnv(string $name, ?bool $default = null): ?bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::getBoolEnv() in plugins yet');
    }

    public static function getCwd(bool $allowEmpty = false): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::getCwd() in plugins yet');
    }

    public static function getDevNull(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::getDevNull() in plugins yet');
    }

    public static function getEnv(string $name)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::getEnv() in plugins yet');
    }

    public static function getUserDirectory(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::getUserDirectory() in plugins yet');
    }

    public static function isDocker(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::isDocker() in plugins yet');
    }

    public static function isInputCompletionProcess(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::isInputCompletionProcess() in plugins yet');
    }

    public static function isTty($fd = null): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::isTty() in plugins yet');
    }

    public static function isWindows(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::isWindows() in plugins yet');
    }

    public static function isWindowsSubsystemForLinux(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::isWindowsSubsystemForLinux() in plugins yet');
    }

    public static function putEnv(string $name, string $value): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::putEnv() in plugins yet');
    }

    public static function realpath(string $path): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::realpath() in plugins yet');
    }

    public static function strlen(string $str): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::strlen() in plugins yet');
    }

    public static function workaroundFilesystemIssues(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Platform::workaroundFilesystemIssues() in plugins yet');
    }
}
