<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

final class TlsHelper
{
    public static function checkCertificateHost($certificate, string $hostname, ?string &$cn = null): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\TlsHelper::checkCertificateHost() in plugins yet');
    }

    public static function getCertificateFingerprint(string $certificate): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\TlsHelper::getCertificateFingerprint() in plugins yet');
    }

    public static function getCertificateNames($certificate): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\TlsHelper::getCertificateNames() in plugins yet');
    }

    public static function isOpensslParseSafe(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\TlsHelper::isOpensslParseSafe() in plugins yet');
    }
}
