<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util;

class Zip
{
    public static function getComposerJson(string $pathToZip): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Zip::getComposerJson() in plugins yet');
    }
}
