<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class DefaultPolicy implements \Composer\DependencyResolver\PolicyInterface
{
    public function __construct(bool $preferStable = false, bool $preferLowest = false, ?array $preferredVersions = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\DefaultPolicy::__construct() in plugins yet');
    }

    public function compareByPriority(\Composer\DependencyResolver\Pool $pool, \Composer\Package\BasePackage $a, \Composer\Package\BasePackage $b, ?string $requiredPackage = null, bool $ignoreReplace = false): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\DefaultPolicy::compareByPriority() in plugins yet');
    }

    protected function groupLiteralsByName(\Composer\DependencyResolver\Pool $pool, array $literals): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\DefaultPolicy::groupLiteralsByName() in plugins yet');
    }

    protected function pruneRemoteAliases(\Composer\DependencyResolver\Pool $pool, array $literals): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\DefaultPolicy::pruneRemoteAliases() in plugins yet');
    }

    protected function pruneToBestVersion(\Composer\DependencyResolver\Pool $pool, array $literals): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\DefaultPolicy::pruneToBestVersion() in plugins yet');
    }

    protected function replaces(\Composer\Package\BasePackage $source, \Composer\Package\BasePackage $target): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\DefaultPolicy::replaces() in plugins yet');
    }

    public function selectPreferredPackages(\Composer\DependencyResolver\Pool $pool, array $literals, ?string $requiredPackage = null): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\DefaultPolicy::selectPreferredPackages() in plugins yet');
    }

    public function versionCompare(\Composer\Package\PackageInterface $a, \Composer\Package\PackageInterface $b, string $operator): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\DefaultPolicy::versionCompare() in plugins yet');
    }
}
