<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class FilterListPoolFilter
{
    public function __construct(\Composer\Policy\PolicyConfig $policyConfig, \Composer\FilterList\FilterListAuditor $filterListAuditor, \Composer\Util\HttpDownloader $httpDownloader, string $blockScope, array $repositories, \Composer\IO\IOInterface $io)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\FilterListPoolFilter::__construct() in plugins yet');
    }

    public function filter(\Composer\DependencyResolver\Pool $pool, \Composer\DependencyResolver\Request $request): \Composer\DependencyResolver\Pool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\FilterListPoolFilter::filter() in plugins yet');
    }
}
