<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class GenericRule extends \Composer\DependencyResolver\Rule
{
    protected $literals;

    public function __construct(array $literals, $reason, $reasonData)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\GenericRule::__construct() in plugins yet');
    }

    public function __toString(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\GenericRule::__toString() in plugins yet');
    }

    public function equals(\Composer\DependencyResolver\Rule $rule): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\GenericRule::equals() in plugins yet');
    }

    public function getHash()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\GenericRule::getHash() in plugins yet');
    }

    public function getLiterals(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\GenericRule::getLiterals() in plugins yet');
    }

    public function isAssertion(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\GenericRule::isAssertion() in plugins yet');
    }
}
