<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class LockTransaction extends \Composer\DependencyResolver\Transaction
{
    protected $presentMap;
    protected $resultPackages;
    protected $unlockableMap;

    public function __construct(\Composer\DependencyResolver\Pool $pool, array $presentMap, array $unlockableMap, \Composer\DependencyResolver\Decisions $decisions)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\LockTransaction::__construct() in plugins yet');
    }

    public function getAliases(array $aliases): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\LockTransaction::getAliases() in plugins yet');
    }

    public function getNewLockPackages(bool $devMode, bool $updateMirrors = false): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\LockTransaction::getNewLockPackages() in plugins yet');
    }

    public function setNonDevPackages(\Composer\DependencyResolver\LockTransaction $extractionResult): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\LockTransaction::setNonDevPackages() in plugins yet');
    }

    public function setResultPackages(\Composer\DependencyResolver\Pool $pool, \Composer\DependencyResolver\Decisions $decisions): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\LockTransaction::setResultPackages() in plugins yet');
    }
}
