<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class MultiConflictRule extends \Composer\DependencyResolver\Rule
{
    protected $literals;

    public function __construct(array $literals, $reason, $reasonData)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\MultiConflictRule::__construct() in plugins yet');
    }

    public function __toString(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\MultiConflictRule::__toString() in plugins yet');
    }

    public function disable(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\MultiConflictRule::disable() in plugins yet');
    }

    public function equals(\Composer\DependencyResolver\Rule $rule): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\MultiConflictRule::equals() in plugins yet');
    }

    public function getHash()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\MultiConflictRule::getHash() in plugins yet');
    }

    public function getLiterals(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\MultiConflictRule::getLiterals() in plugins yet');
    }

    public function isAssertion(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\MultiConflictRule::isAssertion() in plugins yet');
    }
}
