<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class PoolOptimizer
{
    public function __construct(\Composer\DependencyResolver\PolicyInterface $policy)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\PoolOptimizer::__construct() in plugins yet');
    }

    public function optimize(\Composer\DependencyResolver\Request $request, \Composer\DependencyResolver\Pool $pool): \Composer\DependencyResolver\Pool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\PoolOptimizer::optimize() in plugins yet');
    }
}
