<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class Pool implements \Countable, \Stringable
{
    protected $packageByName = [];
    protected $packages = [];
    protected $providerCache = [];
    protected $removedVersions = [];
    protected $removedVersionsByPackage = [];
    protected $unacceptableFixedOrLockedPackages;
    protected $versionParser;

    public function __construct(array $packages = [], array $unacceptableFixedOrLockedPackages = [], array $removedVersions = [], array $removedVersionsByPackage = [], array $securityRemovedVersions = [], array $abandonedRemovedVersions = [], array $filterListRemovedVersions = [])
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::__construct() in plugins yet');
    }

    public function __toString(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::__toString() in plugins yet');
    }

    public function count(): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::count() in plugins yet');
    }

    public function getAllAbandonedRemovedPackageVersions(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::getAllAbandonedRemovedPackageVersions() in plugins yet');
    }

    public function getAllFilterListRemovedPackageVersions(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::getAllFilterListRemovedPackageVersions() in plugins yet');
    }

    public function getAllRemovedVersions(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::getAllRemovedVersions() in plugins yet');
    }

    public function getAllRemovedVersionsByPackage(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::getAllRemovedVersionsByPackage() in plugins yet');
    }

    public function getAllSecurityRemovedPackageVersions(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::getAllSecurityRemovedPackageVersions() in plugins yet');
    }

    public function getFilterListEntryForPackageVersion(string $packageName, ?\Composer\Semver\Constraint\ConstraintInterface $constraint): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::getFilterListEntryForPackageVersion() in plugins yet');
    }

    public function getPackages(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::getPackages() in plugins yet');
    }

    public function getRemovedVersions(string $name, \Composer\Semver\Constraint\ConstraintInterface $constraint): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::getRemovedVersions() in plugins yet');
    }

    public function getRemovedVersionsByPackage(int $objectId): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::getRemovedVersionsByPackage() in plugins yet');
    }

    public function getSecurityAdvisoryIdentifiersForPackageVersion(string $packageName, ?\Composer\Semver\Constraint\ConstraintInterface $constraint): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::getSecurityAdvisoryIdentifiersForPackageVersion() in plugins yet');
    }

    public function getUnacceptableFixedOrLockedPackages(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::getUnacceptableFixedOrLockedPackages() in plugins yet');
    }

    public function isAbandonedRemovedPackageVersion(string $packageName, ?\Composer\Semver\Constraint\ConstraintInterface $constraint): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::isAbandonedRemovedPackageVersion() in plugins yet');
    }

    public function isFilterListRemovedPackageVersion(string $packageName, ?\Composer\Semver\Constraint\ConstraintInterface $constraint): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::isFilterListRemovedPackageVersion() in plugins yet');
    }

    public function isSecurityRemovedPackageVersion(string $packageName, ?\Composer\Semver\Constraint\ConstraintInterface $constraint): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::isSecurityRemovedPackageVersion() in plugins yet');
    }

    public function isUnacceptableFixedOrLockedPackage(\Composer\Package\BasePackage $package): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::isUnacceptableFixedOrLockedPackage() in plugins yet');
    }

    public function literalToPackage(int $literal): \Composer\Package\BasePackage
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::literalToPackage() in plugins yet');
    }

    public function literalToPrettyString(int $literal, array $installedMap): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::literalToPrettyString() in plugins yet');
    }

    public function match(\Composer\Package\BasePackage $candidate, string $name, ?\Composer\Semver\Constraint\ConstraintInterface $constraint = null): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::match() in plugins yet');
    }

    public function packageById(int $id): \Composer\Package\BasePackage
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::packageById() in plugins yet');
    }

    public function whatProvides(string $name, ?\Composer\Semver\Constraint\ConstraintInterface $constraint = null): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Pool::whatProvides() in plugins yet');
    }
}
