<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class Request
{
    public const UPDATE_LISTED_WITH_TRANSITIVE_DEPS = 2;
    public const UPDATE_LISTED_WITH_TRANSITIVE_DEPS_NO_ROOT_REQUIRE = 1;
    public const UPDATE_ONLY_LISTED = 0;

    protected $fixedLockedPackages = [];
    protected $fixedPackages = [];
    protected $lockedPackages = [];
    protected $lockedRepository;
    protected $requires = [];
    protected $updateAllowList = [];
    protected $updateAllowTransitiveDependencies = false;

    public function __construct(?\Composer\Repository\LockArrayRepository $lockedRepository = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::__construct() in plugins yet');
    }

    public function fixLockedPackage(\Composer\Package\BasePackage $package): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::fixLockedPackage() in plugins yet');
    }

    public function fixPackage(\Composer\Package\BasePackage $package): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::fixPackage() in plugins yet');
    }

    public function getFixedOrLockedPackages(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::getFixedOrLockedPackages() in plugins yet');
    }

    public function getFixedPackages(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::getFixedPackages() in plugins yet');
    }

    public function getFixedPackagesMap(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::getFixedPackagesMap() in plugins yet');
    }

    public function getLockedPackages(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::getLockedPackages() in plugins yet');
    }

    public function getLockedRepository(): ?\Composer\Repository\LockArrayRepository
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::getLockedRepository() in plugins yet');
    }

    public function getPresentMap(bool $packageIds = false): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::getPresentMap() in plugins yet');
    }

    public function getRequires(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::getRequires() in plugins yet');
    }

    public function getRestrictedPackages(): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::getRestrictedPackages() in plugins yet');
    }

    public function getUpdateAllowList(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::getUpdateAllowList() in plugins yet');
    }

    public function getUpdateAllowTransitiveDependencies(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::getUpdateAllowTransitiveDependencies() in plugins yet');
    }

    public function getUpdateAllowTransitiveRootDependencies(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::getUpdateAllowTransitiveRootDependencies() in plugins yet');
    }

    public function isFixedPackage(\Composer\Package\BasePackage $package): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::isFixedPackage() in plugins yet');
    }

    public function isLockedPackage(\Composer\Package\PackageInterface $package): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::isLockedPackage() in plugins yet');
    }

    public function lockPackage(\Composer\Package\BasePackage $package): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::lockPackage() in plugins yet');
    }

    public function requireName(string $packageName, ?\Composer\Semver\Constraint\ConstraintInterface $constraint = null): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::requireName() in plugins yet');
    }

    public function restrictPackages(array $names): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::restrictPackages() in plugins yet');
    }

    public function setUpdateAllowList(array $updateAllowList, $updateAllowTransitiveDependencies): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::setUpdateAllowList() in plugins yet');
    }

    public function unlockPackage(\Composer\Package\BasePackage $package): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Request::unlockPackage() in plugins yet');
    }
}
