<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class RuleSetIterator implements \Iterator
{
    protected $currentOffset;
    protected $currentType;
    protected $currentTypeOffset;
    protected $rules;
    protected $types;

    public function __construct(array $rules)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSetIterator::__construct() in plugins yet');
    }

    public function current(): \Composer\DependencyResolver\Rule
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSetIterator::current() in plugins yet');
    }

    public function key(): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSetIterator::key() in plugins yet');
    }

    public function next(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSetIterator::next() in plugins yet');
    }

    public function rewind(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSetIterator::rewind() in plugins yet');
    }

    public function valid(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSetIterator::valid() in plugins yet');
    }
}
