<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class RuleSet implements \Countable, \IteratorAggregate, \Stringable
{
    public const TYPES = [0 => 'PACKAGE', 1 => 'REQUEST', 4 => 'LEARNED'];
    public const TYPE_LEARNED = 4;
    public const TYPE_PACKAGE = 0;
    public const TYPE_REQUEST = 1;

    protected $nextRuleId = 0;
    public $ruleById = [];
    protected $rules;
    protected $rulesByHash = [];

    public function __construct()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSet::__construct() in plugins yet');
    }

    public function __toString(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSet::__toString() in plugins yet');
    }

    public function add(\Composer\DependencyResolver\Rule $rule, $type): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSet::add() in plugins yet');
    }

    public function count(): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSet::count() in plugins yet');
    }

    public function getIterator(): \Composer\DependencyResolver\RuleSetIterator
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSet::getIterator() in plugins yet');
    }

    public function getIteratorFor($types): \Composer\DependencyResolver\RuleSetIterator
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSet::getIteratorFor() in plugins yet');
    }

    public function getIteratorWithout($types): \Composer\DependencyResolver\RuleSetIterator
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSet::getIteratorWithout() in plugins yet');
    }

    public function getPrettyString(?\Composer\Repository\RepositorySet $repositorySet = null, ?\Composer\DependencyResolver\Request $request = null, ?\Composer\DependencyResolver\Pool $pool = null, bool $isVerbose = false): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSet::getPrettyString() in plugins yet');
    }

    public function getRules(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSet::getRules() in plugins yet');
    }

    public function getTypes(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSet::getTypes() in plugins yet');
    }

    public function ruleById(int $id): \Composer\DependencyResolver\Rule
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleSet::ruleById() in plugins yet');
    }
}
