<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

abstract class Rule implements \Stringable
{
    public const RULE_FIXED = 3;
    public const RULE_LEARNED = 12;
    public const RULE_LOCKED_FILTER_LIST_REMOVED = 15;
    public const RULE_PACKAGE_ALIAS = 13;
    public const RULE_PACKAGE_CONFLICT = 6;
    public const RULE_PACKAGE_INVERSE_ALIAS = 14;
    public const RULE_PACKAGE_REQUIRES = 7;
    public const RULE_PACKAGE_SAME_NAME = 10;
    public const RULE_ROOT_REQUIRE = 2;

    protected $bitfield;
    protected $reasonData;
    protected $request;

    public function __construct($reason, $reasonData)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::__construct() in plugins yet');
    }

    abstract public function __toString(): string;

    public function disable(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::disable() in plugins yet');
    }

    public function enable(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::enable() in plugins yet');
    }

    abstract public function equals(\Composer\DependencyResolver\Rule $rule): bool;

    protected function formatPackagesUnique(\Composer\DependencyResolver\Pool $pool, array $literalsOrPackages, bool $isVerbose, ?\Composer\Semver\Constraint\ConstraintInterface $constraint = null, bool $useRemovedVersionGroup = false): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::formatPackagesUnique() in plugins yet');
    }

    abstract public function getHash();

    abstract public function getLiterals(): array;

    public function getPrettyString(\Composer\Repository\RepositorySet $repositorySet, \Composer\DependencyResolver\Request $request, \Composer\DependencyResolver\Pool $pool, bool $isVerbose, array $installedMap = [], array $learnedPool = []): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::getPrettyString() in plugins yet');
    }

    public function getReason(): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::getReason() in plugins yet');
    }

    public function getReasonData()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::getReasonData() in plugins yet');
    }

    public function getRequiredPackage(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::getRequiredPackage() in plugins yet');
    }

    public function getSourcePackage(\Composer\DependencyResolver\Pool $pool): \Composer\Package\BasePackage
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::getSourcePackage() in plugins yet');
    }

    public function getType(): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::getType() in plugins yet');
    }

    abstract public function isAssertion(): bool;

    public function isCausedByLock(\Composer\Repository\RepositorySet $repositorySet, \Composer\DependencyResolver\Request $request, \Composer\DependencyResolver\Pool $pool): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::isCausedByLock() in plugins yet');
    }

    public function isDisabled(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::isDisabled() in plugins yet');
    }

    public function isEnabled(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::isEnabled() in plugins yet');
    }

    public function setType($type): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule::setType() in plugins yet');
    }
}
