<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class RuleWatchChain extends \SplDoublyLinkedList
{
    public function remove(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleWatchChain::remove() in plugins yet');
    }

    public function seek(int $offset): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\RuleWatchChain::seek() in plugins yet');
    }
}
