<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class Rule2Literals extends \Composer\DependencyResolver\Rule
{
    protected $literal1;
    protected $literal2;

    public function __construct(int $literal1, int $literal2, $reason, $reasonData)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule2Literals::__construct() in plugins yet');
    }

    public function __toString(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule2Literals::__toString() in plugins yet');
    }

    public function equals(\Composer\DependencyResolver\Rule $rule): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule2Literals::equals() in plugins yet');
    }

    public function getHash()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule2Literals::getHash() in plugins yet');
    }

    public function getLiterals(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule2Literals::getLiterals() in plugins yet');
    }

    public function isAssertion(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Rule2Literals::isAssertion() in plugins yet');
    }
}
