<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\DependencyResolver;

class Transaction
{
    protected $operations;
    protected $presentPackages;
    protected $resultPackageMap;
    protected $resultPackagesByName = [];

    public function __construct(array $presentPackages, array $resultPackages)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Transaction::__construct() in plugins yet');
    }

    protected function calculateOperations(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Transaction::calculateOperations() in plugins yet');
    }

    public function getOperations(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Transaction::getOperations() in plugins yet');
    }

    protected function getProvidersInResult(\Composer\Package\Link $link): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Transaction::getProvidersInResult() in plugins yet');
    }

    protected function getRootPackages(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\DependencyResolver\\Transaction::getRootPackages() in plugins yet');
    }
}
