<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository\Vcs;

class ForgejoDriver extends \Composer\Repository\Vcs\VcsDriver
{
    protected $gitDriver;

    protected function attemptCloneFallback(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::attemptCloneFallback() in plugins yet');
    }

    public function getBranches(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::getBranches() in plugins yet');
    }

    public function getChangeDate(string $identifier): ?\DateTimeImmutable
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::getChangeDate() in plugins yet');
    }

    public function getComposerInformation(string $identifier): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::getComposerInformation() in plugins yet');
    }

    protected function getContents(string $url, bool $fetchingRepoData = false): \Composer\Util\Http\Response
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::getContents() in plugins yet');
    }

    public function getDist(string $identifier): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::getDist() in plugins yet');
    }

    public function getFileContent(string $file, string $identifier): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::getFileContent() in plugins yet');
    }

    protected function getNextPage(\Composer\Util\Http\Response $response): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::getNextPage() in plugins yet');
    }

    public function getRootIdentifier(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::getRootIdentifier() in plugins yet');
    }

    public function getSource(string $identifier): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::getSource() in plugins yet');
    }

    public function getTags(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::getTags() in plugins yet');
    }

    public function getUrl(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::getUrl() in plugins yet');
    }

    public function initialize(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::initialize() in plugins yet');
    }

    protected function setupGitDriver(string $url): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::setupGitDriver() in plugins yet');
    }

    public static function supports(\Composer\IO\IOInterface $io, \Composer\Config $config, string $url, bool $deep = false): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\ForgejoDriver::supports() in plugins yet');
    }
}
