<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository\Vcs;

class GitBitbucketDriver extends \Composer\Repository\Vcs\VcsDriver
{
    protected $fallbackDriver;
    protected $owner;
    protected $repository;

    protected function attemptCloneFallback(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::attemptCloneFallback() in plugins yet');
    }

    protected function fetchWithOAuthCredentials(string $url, bool $fetchingRepoData = false): \Composer\Util\Http\Response
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::fetchWithOAuthCredentials() in plugins yet');
    }

    protected function generateSshUrl(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::generateSshUrl() in plugins yet');
    }

    public function getBranches(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::getBranches() in plugins yet');
    }

    public function getChangeDate(string $identifier): ?\DateTimeImmutable
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::getChangeDate() in plugins yet');
    }

    public function getComposerInformation(string $identifier): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::getComposerInformation() in plugins yet');
    }

    public function getDist(string $identifier): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::getDist() in plugins yet');
    }

    public function getFileContent(string $file, string $identifier): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::getFileContent() in plugins yet');
    }

    protected function getRepoData(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::getRepoData() in plugins yet');
    }

    public function getRootIdentifier(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::getRootIdentifier() in plugins yet');
    }

    public function getSource(string $identifier): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::getSource() in plugins yet');
    }

    public function getTags(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::getTags() in plugins yet');
    }

    public function getUrl(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::getUrl() in plugins yet');
    }

    public function initialize(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::initialize() in plugins yet');
    }

    protected function parseCloneUrls(array $cloneLinks): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::parseCloneUrls() in plugins yet');
    }

    protected function setupFallbackDriver(string $url): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::setupFallbackDriver() in plugins yet');
    }

    public static function supports(\Composer\IO\IOInterface $io, \Composer\Config $config, string $url, bool $deep = false): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\GitBitbucketDriver::supports() in plugins yet');
    }
}
