<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository\Vcs;

class HgDriver extends \Composer\Repository\Vcs\VcsDriver
{
    protected $branches;
    protected $repoDir;
    protected $rootIdentifier;
    protected $tags;

    public function getBranches(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\HgDriver::getBranches() in plugins yet');
    }

    public function getChangeDate(string $identifier): ?\DateTimeImmutable
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\HgDriver::getChangeDate() in plugins yet');
    }

    public function getDist(string $identifier): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\HgDriver::getDist() in plugins yet');
    }

    public function getFileContent(string $file, string $identifier): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\HgDriver::getFileContent() in plugins yet');
    }

    public function getRootIdentifier(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\HgDriver::getRootIdentifier() in plugins yet');
    }

    public function getSource(string $identifier): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\HgDriver::getSource() in plugins yet');
    }

    public function getTags(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\HgDriver::getTags() in plugins yet');
    }

    public function getUrl(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\HgDriver::getUrl() in plugins yet');
    }

    public function initialize(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\HgDriver::initialize() in plugins yet');
    }

    public static function supports(\Composer\IO\IOInterface $io, \Composer\Config $config, string $url, bool $deep = false): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\HgDriver::supports() in plugins yet');
    }
}
