<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository\Vcs;

class PerforceDriver extends \Composer\Repository\Vcs\VcsDriver
{
    protected $branch;
    protected $depot;
    protected $perforce;

    public function cleanup(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::cleanup() in plugins yet');
    }

    public function getBranch(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::getBranch() in plugins yet');
    }

    public function getBranches(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::getBranches() in plugins yet');
    }

    public function getChangeDate(string $identifier): ?\DateTimeImmutable
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::getChangeDate() in plugins yet');
    }

    public function getContents(string $url): \Composer\Util\Http\Response
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::getContents() in plugins yet');
    }

    public function getDepot(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::getDepot() in plugins yet');
    }

    public function getDist(string $identifier): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::getDist() in plugins yet');
    }

    public function getFileContent(string $file, string $identifier): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::getFileContent() in plugins yet');
    }

    public function getRootIdentifier(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::getRootIdentifier() in plugins yet');
    }

    public function getSource(string $identifier): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::getSource() in plugins yet');
    }

    public function getTags(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::getTags() in plugins yet');
    }

    public function getUrl(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::getUrl() in plugins yet');
    }

    public function hasComposerFile(string $identifier): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::hasComposerFile() in plugins yet');
    }

    public function initialize(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::initialize() in plugins yet');
    }

    public static function supports(\Composer\IO\IOInterface $io, \Composer\Config $config, string $url, bool $deep = false): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\PerforceDriver::supports() in plugins yet');
    }
}
