<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository\Vcs;

class SvnDriver extends \Composer\Repository\Vcs\VcsDriver
{
    protected $baseUrl;
    protected $branches;
    protected $branchesPath = 'branches';
    protected $cacheCredentials = true;
    protected $packagePath = '';
    protected $rootIdentifier;
    protected $tags;
    protected $tagsPath = 'tags';
    protected $trunkPath = 'trunk';

    protected function buildIdentifier(string $baseDir, int $revision): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::buildIdentifier() in plugins yet');
    }

    protected function execute(array $command, string $url): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::execute() in plugins yet');
    }

    public function getBranches(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::getBranches() in plugins yet');
    }

    public function getChangeDate(string $identifier): ?\DateTimeImmutable
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::getChangeDate() in plugins yet');
    }

    public function getComposerInformation(string $identifier): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::getComposerInformation() in plugins yet');
    }

    public function getDist(string $identifier): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::getDist() in plugins yet');
    }

    public function getFileContent(string $file, string $identifier): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::getFileContent() in plugins yet');
    }

    public function getRootIdentifier(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::getRootIdentifier() in plugins yet');
    }

    public function getSource(string $identifier): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::getSource() in plugins yet');
    }

    public function getTags(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::getTags() in plugins yet');
    }

    public function getUrl(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::getUrl() in plugins yet');
    }

    public function initialize(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::initialize() in plugins yet');
    }

    protected static function normalizeUrl(string $url): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::normalizeUrl() in plugins yet');
    }

    protected function shouldCache(string $identifier): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::shouldCache() in plugins yet');
    }

    public static function supports(\Composer\IO\IOInterface $io, \Composer\Config $config, string $url, bool $deep = false): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\SvnDriver::supports() in plugins yet');
    }
}
