<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository\Vcs;

interface VcsDriverInterface
{
    public function cleanup(): void;

    public function getBranches(): array;

    public function getChangeDate(string $identifier): ?\DateTimeImmutable;

    public function getComposerInformation(string $identifier): ?array;

    public function getDist(string $identifier): ?array;

    public function getFileContent(string $file, string $identifier): ?string;

    public function getRootIdentifier(): string;

    public function getSource(string $identifier): array;

    public function getTags(): array;

    public function getUrl(): string;

    public function hasComposerFile(string $identifier): bool;

    public function initialize(): void;

    public static function supports(\Composer\IO\IOInterface $io, \Composer\Config $config, string $url, bool $deep = false): bool;
}
