<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository\Vcs;

abstract class VcsDriver implements \Composer\Repository\Vcs\VcsDriverInterface
{
    protected $cache;
    protected $config;
    protected $httpDownloader;
    protected $infoCache = [];
    protected $io;
    protected $originUrl;
    protected $process;
    protected $repoConfig;
    protected $url;

    final public function __construct(array $repoConfig, \Composer\IO\IOInterface $io, \Composer\Config $config, \Composer\Util\HttpDownloader $httpDownloader, \Composer\Util\ProcessExecutor $process)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\VcsDriver::__construct() in plugins yet');
    }

    public function cleanup(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\VcsDriver::cleanup() in plugins yet');
    }

    protected function getBaseComposerInformation(string $identifier): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\VcsDriver::getBaseComposerInformation() in plugins yet');
    }

    public function getComposerInformation(string $identifier): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\VcsDriver::getComposerInformation() in plugins yet');
    }

    protected function getContents(string $url): \Composer\Util\Http\Response
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\VcsDriver::getContents() in plugins yet');
    }

    protected function getScheme(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\VcsDriver::getScheme() in plugins yet');
    }

    public function hasComposerFile(string $identifier): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\VcsDriver::hasComposerFile() in plugins yet');
    }

    protected function shouldCache(string $identifier): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\Vcs\\VcsDriver::shouldCache() in plugins yet');
    }
}
