<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

class ArrayRepository implements \Composer\Repository\RepositoryInterface
{
    protected $packageMap;
    protected $packages;

    public function __construct(array $packages = [])
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::__construct() in plugins yet');
    }

    public function addPackage(\Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::addPackage() in plugins yet');
    }

    public function count(): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::count() in plugins yet');
    }

    protected function createAliasPackage(\Composer\Package\BasePackage $package, string $alias, string $prettyAlias)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::createAliasPackage() in plugins yet');
    }

    public function findPackage(string $name, $constraint)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::findPackage() in plugins yet');
    }

    public function findPackages(string $name, $constraint = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::findPackages() in plugins yet');
    }

    public function getPackages()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::getPackages() in plugins yet');
    }

    public function getProviders(string $packageName)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::getProviders() in plugins yet');
    }

    public function getRepoName()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::getRepoName() in plugins yet');
    }

    public function hasPackage(\Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::hasPackage() in plugins yet');
    }

    protected function initialize()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::initialize() in plugins yet');
    }

    public function loadPackages(array $packageNameMap, array $acceptableStabilities, array $stabilityFlags, array $alreadyLoaded = [])
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::loadPackages() in plugins yet');
    }

    public function removePackage(\Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::removePackage() in plugins yet');
    }

    public function search(string $query, int $mode = 0, ?string $type = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArrayRepository::search() in plugins yet');
    }
}
