<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

class ArtifactRepository extends \Composer\Repository\ArrayRepository implements \Composer\Repository\ConfigurableRepositoryInterface
{
    protected $loader;
    protected $lookup;
    protected $repoConfig;

    public function __construct(array $repoConfig, \Composer\IO\IOInterface $io)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArtifactRepository::__construct() in plugins yet');
    }

    public function getRepoConfig()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArtifactRepository::getRepoConfig() in plugins yet');
    }

    public function getRepoName()
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('repo.getRepoName', [$this]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArtifactRepository::getRepoName() in plugins yet');
    }

    protected function initialize()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ArtifactRepository::initialize() in plugins yet');
    }
}
