<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

class ComposerRepository extends \Composer\Repository\ArrayRepository implements \Composer\Repository\AdvisoryProviderInterface, \Composer\Repository\ConfigurableRepositoryInterface, \Composer\Repository\FilterListProviderInterface
{
    protected $availablePackagePatterns;
    protected $availablePackages;
    protected $cache;
    protected $hasAvailablePackageList = false;
    protected $hasProviders = false;
    protected $lazyProvidersUrl;
    protected $listUrl;
    protected $loader;
    protected $notifyUrl;
    protected $providerListing;
    protected $providersApiUrl;
    protected $providersUrl;
    protected $searchUrl;

    public function __construct(array $repoConfig, \Composer\IO\IOInterface $io, \Composer\Config $config, \Composer\Util\HttpDownloader $httpDownloader, ?\Composer\EventDispatcher\EventDispatcher $eventDispatcher = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::__construct() in plugins yet');
    }

    public function addPackage(\Composer\Package\PackageInterface $package)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::addPackage() in plugins yet');
    }

    protected function configurePackageTransportOptions(\Composer\Package\PackageInterface $package): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::configurePackageTransportOptions() in plugins yet');
    }

    protected function fetchFile(string $filename, ?string $cacheKey = null, ?string $sha256 = null, bool $storeLastModifiedTime = false)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::fetchFile() in plugins yet');
    }

    public function findPackage(string $name, $constraint)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::findPackage() in plugins yet');
    }

    public function findPackages(string $name, $constraint = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::findPackages() in plugins yet');
    }

    public function getFilter(array $packageConstraintMap, array $configuredLists): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::getFilter() in plugins yet');
    }

    public function getFilterLists(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::getFilterLists() in plugins yet');
    }

    public function getPackageNames(?string $packageFilter = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::getPackageNames() in plugins yet');
    }

    public function getPackages()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::getPackages() in plugins yet');
    }

    public function getProviders(string $packageName)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::getProviders() in plugins yet');
    }

    public function getRepoConfig()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::getRepoConfig() in plugins yet');
    }

    public function getRepoName()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::getRepoName() in plugins yet');
    }

    public function getSecurityAdvisories(array $packageConstraintMap, bool $allowPartialAdvisories = false): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::getSecurityAdvisories() in plugins yet');
    }

    public function hasFilter(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::hasFilter() in plugins yet');
    }

    public function hasSecurityAdvisories(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::hasSecurityAdvisories() in plugins yet');
    }

    protected function initialize()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::initialize() in plugins yet');
    }

    protected function lazyProvidersRepoContains(string $name)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::lazyProvidersRepoContains() in plugins yet');
    }

    public function loadPackages(array $packageNameMap, array $acceptableStabilities, array $stabilityFlags, array $alreadyLoaded = [])
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::loadPackages() in plugins yet');
    }

    protected function loadRootServerFile(?int $rootMaxAge = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::loadRootServerFile() in plugins yet');
    }

    public function search(string $query, int $mode = 0, ?string $type = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\ComposerRepository::search() in plugins yet');
    }
}
