<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

class FilesystemRepository extends \Composer\Repository\WritableArrayRepository
{
    protected $file;

    public function __construct(\Composer\Json\JsonFile $repositoryFile, bool $dumpVersions = false, ?\Composer\Package\RootPackageInterface $rootPackage = null, ?\Composer\Util\Filesystem $filesystem = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilesystemRepository::__construct() in plugins yet');
    }

    public function getDevMode()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilesystemRepository::getDevMode() in plugins yet');
    }

    protected function initialize()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilesystemRepository::initialize() in plugins yet');
    }

    public function reload()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilesystemRepository::reload() in plugins yet');
    }

    public static function safelyLoadInstalledVersions(string $path): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilesystemRepository::safelyLoadInstalledVersions() in plugins yet');
    }

    public function write(bool $devMode, \Composer\Installer\InstallationManager $installationManager)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilesystemRepository::write() in plugins yet');
    }
}
