<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

interface FilterListProviderInterface
{
    public function getFilter(array $packageConstraintMap, array $configuredLists): array;

    public function getFilterLists(): array;

    public function hasFilter(): bool;
}
