<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

class FilterRepository implements \Composer\Repository\AdvisoryProviderInterface, \Composer\Repository\FilterListProviderInterface, \Composer\Repository\RepositoryInterface
{
    public function __construct(\Composer\Repository\RepositoryInterface $repo, array $options)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::__construct() in plugins yet');
    }

    public function count(): int
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('repo.count', [$this]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::count() in plugins yet');
    }

    public function findPackage($name, $constraint): ?\Composer\Package\BasePackage
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('repo.findPackage', [$this, $name, $constraint]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::findPackage() in plugins yet');
    }

    public function findPackages($name, $constraint = null): array
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('repo.findPackages', [$this, $name, $constraint]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::findPackages() in plugins yet');
    }

    public function getFilter(array $packageConstraintMap, array $configuredLists): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::getFilter() in plugins yet');
    }

    public function getFilterLists(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::getFilterLists() in plugins yet');
    }

    public function getPackages(): array
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('repo.getPackages', [$this]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::getPackages() in plugins yet');
    }

    public function getProviders($packageName): array
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('repo.getProviders', [$this, $packageName]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::getProviders() in plugins yet');
    }

    public function getRepoName(): string
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('repo.getRepoName', [$this]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::getRepoName() in plugins yet');
    }

    public function getRepository(): \Composer\Repository\RepositoryInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::getRepository() in plugins yet');
    }

    public function getSecurityAdvisories(array $packageConstraintMap, bool $allowPartialAdvisories = false): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::getSecurityAdvisories() in plugins yet');
    }

    public function hasFilter(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::hasFilter() in plugins yet');
    }

    public function hasPackage(\Composer\Package\PackageInterface $package): bool
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('repo.hasPackage', [$this, $package]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::hasPackage() in plugins yet');
    }

    public function hasSecurityAdvisories(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::hasSecurityAdvisories() in plugins yet');
    }

    public function loadPackages(array $packageNameMap, array $acceptableStabilities, array $stabilityFlags, array $alreadyLoaded = []): array
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('repo.loadPackages', [$this, $packageNameMap, $acceptableStabilities, $stabilityFlags, $alreadyLoaded]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::loadPackages() in plugins yet');
    }

    public function search(string $query, int $mode = 0, ?string $type = null): array
    {
        if (\Maestro\Shim\Remote::owned($this)) {
            return \Maestro\Shim\Rpc::call('repo.search', [$this, $query, $mode, $type]);
        }

        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\FilterRepository::search() in plugins yet');
    }
}
