<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

class InstalledFilesystemRepository extends \Composer\Repository\FilesystemRepository implements \Composer\Repository\InstalledRepositoryInterface
{
    public function getRepoName()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\InstalledFilesystemRepository::getRepoName() in plugins yet');
    }

    public function isFresh()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\InstalledFilesystemRepository::isFresh() in plugins yet');
    }
}
