<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

class PearRepository extends \Composer\Repository\ArrayRepository
{
    public function __construct()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\PearRepository::__construct() in plugins yet');
    }
}
