<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

interface RepositoryInterface extends \Countable
{
    public const SEARCH_FULLTEXT = 0;
    public const SEARCH_NAME = 1;
    public const SEARCH_VENDOR = 2;

    public function findPackage(string $name, $constraint);

    public function findPackages(string $name, $constraint = null);

    public function getPackages();

    public function getProviders(string $packageName);

    public function getRepoName();

    public function hasPackage(\Composer\Package\PackageInterface $package);

    public function loadPackages(array $packageNameMap, array $acceptableStabilities, array $stabilityFlags, array $alreadyLoaded = []);

    public function search(string $query, int $mode = 0, ?string $type = null);
}
