<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

class RepositoryFactory
{
    public static function configFromString(\Composer\IO\IOInterface $io, \Composer\Config $config, string $repository, bool $allowFilesystem = false)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryFactory::configFromString() in plugins yet');
    }

    public static function createRepo(\Composer\IO\IOInterface $io, \Composer\Config $config, array $repoConfig, ?\Composer\Repository\RepositoryManager $rm = null): \Composer\Repository\RepositoryInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryFactory::createRepo() in plugins yet');
    }

    public static function defaultRepos(?\Composer\IO\IOInterface $io = null, ?\Composer\Config $config = null, ?\Composer\Repository\RepositoryManager $rm = null): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryFactory::defaultRepos() in plugins yet');
    }

    public static function defaultReposWithDefaultManager(\Composer\IO\IOInterface $io): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryFactory::defaultReposWithDefaultManager() in plugins yet');
    }

    public static function fromString(\Composer\IO\IOInterface $io, \Composer\Config $config, string $repository, bool $allowFilesystem = false, ?\Composer\Repository\RepositoryManager $rm = null): \Composer\Repository\RepositoryInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryFactory::fromString() in plugins yet');
    }

    public static function generateRepositoryName($index, array $repo, array $existingRepos): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryFactory::generateRepositoryName() in plugins yet');
    }

    public static function manager(\Composer\IO\IOInterface $io, \Composer\Config $config, ?\Composer\Util\HttpDownloader $httpDownloader = null, ?\Composer\EventDispatcher\EventDispatcher $eventDispatcher = null, ?\Composer\Util\ProcessExecutor $process = null): \Composer\Repository\RepositoryManager
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryFactory::manager() in plugins yet');
    }
}
