<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

class RepositoryUtils
{
    public static function filterRequiredPackages(array $packages, \Composer\Package\PackageInterface $requirer, bool $includeRequireDev = false, array $bucket = []): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryUtils::filterRequiredPackages() in plugins yet');
    }

    public static function flattenRepositories(\Composer\Repository\RepositoryInterface $repo, bool $unwrapFilterRepos = true): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryUtils::flattenRepositories() in plugins yet');
    }
}
