<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

class RepositoryManager
{
    public function __construct(\Composer\IO\IOInterface $io, \Composer\Config $config, \Composer\Util\HttpDownloader $httpDownloader, ?\Composer\EventDispatcher\EventDispatcher $eventDispatcher = null, ?\Composer\Util\ProcessExecutor $process = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryManager::__construct() in plugins yet');
    }

    public function addRepository(\Composer\Repository\RepositoryInterface $repository): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryManager::addRepository() in plugins yet');
    }

    public function createRepository(string $type, array $config, ?string $name = null): \Composer\Repository\RepositoryInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryManager::createRepository() in plugins yet');
    }

    public function findPackage(string $name, $constraint): ?\Composer\Package\PackageInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryManager::findPackage() in plugins yet');
    }

    public function findPackages(string $name, $constraint): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryManager::findPackages() in plugins yet');
    }

    public function getHttpDownloader(): \Composer\Util\HttpDownloader
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryManager::getHttpDownloader() in plugins yet');
    }

    public function getLocalRepository(): \Composer\Repository\InstalledRepositoryInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryManager::getLocalRepository() in plugins yet');
    }

    public function getRepositories(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryManager::getRepositories() in plugins yet');
    }

    public function prependRepository(\Composer\Repository\RepositoryInterface $repository): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryManager::prependRepository() in plugins yet');
    }

    public function setLocalRepository(\Composer\Repository\InstalledRepositoryInterface $repository): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryManager::setLocalRepository() in plugins yet');
    }

    public function setRepositoryClass(string $type, $class): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Repository\\RepositoryManager::setRepositoryClass() in plugins yet');
    }
}
