<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Repository;

interface VersionCacheInterface
{
    public function getVersionPackage(string $version, string $identifier);
}
