<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer;

class Cache
{
    public function __construct(\Composer\IO\IOInterface $io, string $cacheDir, string $allowlist = 'a-z0-9._', ?\Composer\Util\Filesystem $filesystem = null, bool $readOnly = false)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::__construct() in plugins yet');
    }

    public function clear()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::clear() in plugins yet');
    }

    public function copyFrom(string $file, string $source)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::copyFrom() in plugins yet');
    }

    public function copyTo(string $file, string $target)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::copyTo() in plugins yet');
    }

    public function gc(int $ttl, int $maxSize)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::gc() in plugins yet');
    }

    public function gcIsNecessary()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::gcIsNecessary() in plugins yet');
    }

    public function gcVcsCache(int $ttl): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::gcVcsCache() in plugins yet');
    }

    public function getAge(string $file)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::getAge() in plugins yet');
    }

    protected function getFinder()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::getFinder() in plugins yet');
    }

    public function getRoot()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::getRoot() in plugins yet');
    }

    public function isEnabled()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::isEnabled() in plugins yet');
    }

    public function isReadOnly()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::isReadOnly() in plugins yet');
    }

    public static function isUsable(string $path)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::isUsable() in plugins yet');
    }

    public function read(string $file)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::read() in plugins yet');
    }

    public function remove(string $file)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::remove() in plugins yet');
    }

    public function setReadOnly(bool $readOnly)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::setReadOnly() in plugins yet');
    }

    public function sha1(string $file)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::sha1() in plugins yet');
    }

    public function sha256(string $file)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::sha256() in plugins yet');
    }

    public function write(string $file, string $contents)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Cache::write() in plugins yet');
    }
}
