<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer;

class PartialComposer
{
    public function getConfig(): \Composer\Config
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::getConfig() in plugins yet');
    }

    public function getEventDispatcher(): \Composer\EventDispatcher\EventDispatcher
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::getEventDispatcher() in plugins yet');
    }

    public function getInstallationManager(): \Composer\Installer\InstallationManager
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::getInstallationManager() in plugins yet');
    }

    public function getLoop(): \Composer\Util\Loop
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::getLoop() in plugins yet');
    }

    public function getPackage(): \Composer\Package\RootPackageInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::getPackage() in plugins yet');
    }

    public function getRepositoryManager(): \Composer\Repository\RepositoryManager
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::getRepositoryManager() in plugins yet');
    }

    public function isGlobal(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::isGlobal() in plugins yet');
    }

    public function setConfig(\Composer\Config $config): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::setConfig() in plugins yet');
    }

    public function setEventDispatcher(\Composer\EventDispatcher\EventDispatcher $eventDispatcher): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::setEventDispatcher() in plugins yet');
    }

    public function setGlobal(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::setGlobal() in plugins yet');
    }

    public function setInstallationManager(\Composer\Installer\InstallationManager $manager): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::setInstallationManager() in plugins yet');
    }

    public function setLoop(\Composer\Util\Loop $loop): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::setLoop() in plugins yet');
    }

    public function setPackage(\Composer\Package\RootPackageInterface $package): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::setPackage() in plugins yet');
    }

    public function setRepositoryManager(\Composer\Repository\RepositoryManager $manager): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\PartialComposer::setRepositoryManager() in plugins yet');
    }
}
