<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package;

class AliasPackage extends \Composer\Package\BasePackage
{
    protected $aliasOf;
    protected $conflicts;
    protected $dev;
    protected $devRequires;
    protected $hasSelfVersionRequires = false;
    protected $prettyVersion;
    protected $provides;
    protected $replaces;
    protected $requires;
    protected $rootPackageAlias = false;
    protected $stability;
    protected $version;

    public function __construct(\Composer\Package\BasePackage $aliasOf, string $version, string $prettyVersion)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::__construct() in plugins yet');
    }

    public function __toString(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::__toString() in plugins yet');
    }

    public function getAliasOf()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getAliasOf() in plugins yet');
    }

    public function getAutoload(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getAutoload() in plugins yet');
    }

    public function getBinaries(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getBinaries() in plugins yet');
    }

    public function getConflicts(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getConflicts() in plugins yet');
    }

    public function getDevAutoload(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getDevAutoload() in plugins yet');
    }

    public function getDevRequires(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getDevRequires() in plugins yet');
    }

    public function getDistMirrors(): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getDistMirrors() in plugins yet');
    }

    public function getDistReference(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getDistReference() in plugins yet');
    }

    public function getDistSha1Checksum(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getDistSha1Checksum() in plugins yet');
    }

    public function getDistType(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getDistType() in plugins yet');
    }

    public function getDistUrl(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getDistUrl() in plugins yet');
    }

    public function getDistUrls(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getDistUrls() in plugins yet');
    }

    public function getExtra(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getExtra() in plugins yet');
    }

    public function getIncludePaths(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getIncludePaths() in plugins yet');
    }

    public function getInstallationSource(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getInstallationSource() in plugins yet');
    }

    public function getNotificationUrl(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getNotificationUrl() in plugins yet');
    }

    public function getPhpExt(): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getPhpExt() in plugins yet');
    }

    public function getPrettyVersion(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getPrettyVersion() in plugins yet');
    }

    public function getProvides(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getProvides() in plugins yet');
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getReleaseDate() in plugins yet');
    }

    public function getReplaces(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getReplaces() in plugins yet');
    }

    public function getRequires(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getRequires() in plugins yet');
    }

    public function getSourceMirrors(): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getSourceMirrors() in plugins yet');
    }

    public function getSourceReference(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getSourceReference() in plugins yet');
    }

    public function getSourceType(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getSourceType() in plugins yet');
    }

    public function getSourceUrl(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getSourceUrl() in plugins yet');
    }

    public function getSourceUrls(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getSourceUrls() in plugins yet');
    }

    public function getStability(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getStability() in plugins yet');
    }

    public function getSuggests(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getSuggests() in plugins yet');
    }

    public function getTargetDir(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getTargetDir() in plugins yet');
    }

    public function getTransportOptions(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getTransportOptions() in plugins yet');
    }

    public function getType(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getType() in plugins yet');
    }

    public function getVersion(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::getVersion() in plugins yet');
    }

    public function hasSelfVersionRequires(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::hasSelfVersionRequires() in plugins yet');
    }

    public function isDefaultBranch(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::isDefaultBranch() in plugins yet');
    }

    public function isDev(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::isDev() in plugins yet');
    }

    public function isRootPackageAlias(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::isRootPackageAlias() in plugins yet');
    }

    protected function replaceSelfVersionDependencies(array $links, $linkType): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::replaceSelfVersionDependencies() in plugins yet');
    }

    public function setDistMirrors(?array $mirrors): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::setDistMirrors() in plugins yet');
    }

    public function setDistReference(?string $reference): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::setDistReference() in plugins yet');
    }

    public function setDistType(?string $type): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::setDistType() in plugins yet');
    }

    public function setDistUrl(?string $url): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::setDistUrl() in plugins yet');
    }

    public function setInstallationSource(?string $type): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::setInstallationSource() in plugins yet');
    }

    public function setRootPackageAlias(bool $value): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::setRootPackageAlias() in plugins yet');
    }

    public function setSourceDistReferences(string $reference): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::setSourceDistReferences() in plugins yet');
    }

    public function setSourceMirrors(?array $mirrors): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::setSourceMirrors() in plugins yet');
    }

    public function setSourceReference(?string $reference): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::setSourceReference() in plugins yet');
    }

    public function setTransportOptions(array $options): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\AliasPackage::setTransportOptions() in plugins yet');
    }
}
