<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package;

abstract class BasePackage implements \Composer\Package\PackageInterface
{
    public const STABILITIES = ['stable' => 0, 'RC' => 5, 'beta' => 10, 'alpha' => 15, 'dev' => 20];
    public const STABILITY_ALPHA = 15;
    public const STABILITY_BETA = 10;
    public const STABILITY_DEV = 20;
    public const STABILITY_RC = 5;
    public const STABILITY_STABLE = 0;

    public $id;
    protected $name;
    protected $prettyName;
    protected $repository;
    public static $stabilities = ['stable' => 0, 'RC' => 5, 'beta' => 10, 'alpha' => 15, 'dev' => 20];
    public static $supportedLinkTypes = ['require' => ['description' => 'requires', 'method' => 'requires'], 'conflict' => ['description' => 'conflicts', 'method' => 'conflicts'], 'provide' => ['description' => 'provides', 'method' => 'provides'], 'replace' => ['description' => 'replaces', 'method' => 'replaces'], 'require-dev' => ['description' => 'requires (for development)', 'method' => 'devRequires']];

    public function __clone()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::__clone() in plugins yet');
    }

    public function __construct(string $name)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::__construct() in plugins yet');
    }

    public function __toString(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::__toString() in plugins yet');
    }

    public function equals(\Composer\Package\PackageInterface $package): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::equals() in plugins yet');
    }

    public function getFullPrettyVersion(bool $truncate = true, int $displayMode = \Composer\Package\PackageInterface::DISPLAY_SOURCE_REF_IF_DEV): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::getFullPrettyVersion() in plugins yet');
    }

    public function getId(): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::getId() in plugins yet');
    }

    public function getName(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::getName() in plugins yet');
    }

    public function getNames($provides = true): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::getNames() in plugins yet');
    }

    public function getPrettyName(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::getPrettyName() in plugins yet');
    }

    public function getPrettyString(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::getPrettyString() in plugins yet');
    }

    public function getRepository(): ?\Composer\Repository\RepositoryInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::getRepository() in plugins yet');
    }

    public function getStabilityPriority(): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::getStabilityPriority() in plugins yet');
    }

    public function getUniqueName(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::getUniqueName() in plugins yet');
    }

    public function isPlatform(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::isPlatform() in plugins yet');
    }

    public static function packageNameToRegexp(string $allowPattern, string $wrap = '{^%s$}i'): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::packageNameToRegexp() in plugins yet');
    }

    public static function packageNamesToRegexp(array $packageNames, string $wrap = '{^(?:%s)$}iD'): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::packageNamesToRegexp() in plugins yet');
    }

    public function setId(int $id): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::setId() in plugins yet');
    }

    public function setRepository(\Composer\Repository\RepositoryInterface $repository): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\BasePackage::setRepository() in plugins yet');
    }
}
