<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package;

interface CompletePackageInterface extends \Composer\Package\PackageInterface
{
    public function getArchiveExcludes(): array;

    public function getArchiveName(): ?string;

    public function getAuthors(): array;

    public function getDescription(): ?string;

    public function getFunding(): array;

    public function getHomepage(): ?string;

    public function getKeywords(): array;

    public function getLicense(): array;

    public function getReplacementPackage(): ?string;

    public function getRepositories(): array;

    public function getScripts(): array;

    public function getSupport(): array;

    public function isAbandoned(): bool;

    public function setAbandoned($abandoned): void;

    public function setArchiveExcludes(array $excludes): void;

    public function setArchiveName(string $name): void;

    public function setAuthors(array $authors): void;

    public function setDescription(string $description): void;

    public function setFunding(array $funding): void;

    public function setHomepage(string $homepage): void;

    public function setKeywords(array $keywords): void;

    public function setLicense(array $license): void;

    public function setRepositories(array $repositories): void;

    public function setScripts(array $scripts): void;

    public function setSupport(array $support): void;
}
