<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package;

class Link implements \Stringable
{
    public const TYPE_CONFLICT = 'conflicts';
    public const TYPE_DEV_REQUIRE = 'devRequires';
    public const TYPE_DOES_NOT_REQUIRE = 'does not require';
    public const TYPE_PROVIDE = 'provides';
    public const TYPE_REPLACE = 'replaces';
    public const TYPE_REQUIRE = 'requires';

    public static $TYPES = ['requires', 'devRequires', 'provides', 'conflicts', 'replaces'];
    protected $constraint;
    protected $description;
    protected $prettyConstraint;
    protected $source;
    protected $target;

    public function __construct(string $source, string $target, \Composer\Semver\Constraint\ConstraintInterface $constraint, $description = self::TYPE_UNKNOWN, ?string $prettyConstraint = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Link::__construct() in plugins yet');
    }

    public function __toString(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Link::__toString() in plugins yet');
    }

    public function getConstraint(): \Composer\Semver\Constraint\ConstraintInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Link::getConstraint() in plugins yet');
    }

    public function getDescription(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Link::getDescription() in plugins yet');
    }

    public function getPrettyConstraint(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Link::getPrettyConstraint() in plugins yet');
    }

    public function getPrettyString(\Composer\Package\PackageInterface $sourcePackage): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Link::getPrettyString() in plugins yet');
    }

    public function getSource(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Link::getSource() in plugins yet');
    }

    public function getTarget(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Link::getTarget() in plugins yet');
    }
}
