<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package;

class Package extends \Composer\Package\BasePackage
{
    protected $autoload = [];
    protected $binaries = [];
    protected $conflicts = [];
    protected $dev;
    protected $devAutoload = [];
    protected $devRequires = [];
    protected $distMirrors;
    protected $distReference;
    protected $distSha1Checksum;
    protected $distType;
    protected $distUrl;
    protected $extra = [];
    protected $includePaths = [];
    protected $installationSource;
    protected $isDefaultBranch = false;
    protected $notificationUrl;
    protected $phpExt;
    protected $prettyVersion;
    protected $provides = [];
    protected $releaseDate;
    protected $replaces = [];
    protected $requires = [];
    protected $sourceMirrors;
    protected $sourceReference;
    protected $sourceType;
    protected $sourceUrl;
    protected $stability;
    protected $suggests = [];
    protected $targetDir;
    protected $transportOptions = [];
    protected $type;
    protected $version;

    public function __construct(string $name, string $version, string $prettyVersion)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::__construct() in plugins yet');
    }

    public function getAutoload(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getAutoload() in plugins yet');
    }

    public function getBinaries(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getBinaries() in plugins yet');
    }

    public function getConflicts(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getConflicts() in plugins yet');
    }

    public function getDevAutoload(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getDevAutoload() in plugins yet');
    }

    public function getDevRequires(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getDevRequires() in plugins yet');
    }

    public function getDistMirrors(): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getDistMirrors() in plugins yet');
    }

    public function getDistReference(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getDistReference() in plugins yet');
    }

    public function getDistSha1Checksum(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getDistSha1Checksum() in plugins yet');
    }

    public function getDistType(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getDistType() in plugins yet');
    }

    public function getDistUrl(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getDistUrl() in plugins yet');
    }

    public function getDistUrls(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getDistUrls() in plugins yet');
    }

    public function getExtra(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getExtra() in plugins yet');
    }

    public function getIncludePaths(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getIncludePaths() in plugins yet');
    }

    public function getInstallationSource(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getInstallationSource() in plugins yet');
    }

    public function getNotificationUrl(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getNotificationUrl() in plugins yet');
    }

    public function getPhpExt(): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getPhpExt() in plugins yet');
    }

    public function getPrettyVersion(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getPrettyVersion() in plugins yet');
    }

    public function getProvides(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getProvides() in plugins yet');
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getReleaseDate() in plugins yet');
    }

    public function getReplaces(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getReplaces() in plugins yet');
    }

    public function getRequires(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getRequires() in plugins yet');
    }

    public function getSourceMirrors(): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getSourceMirrors() in plugins yet');
    }

    public function getSourceReference(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getSourceReference() in plugins yet');
    }

    public function getSourceType(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getSourceType() in plugins yet');
    }

    public function getSourceUrl(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getSourceUrl() in plugins yet');
    }

    public function getSourceUrls(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getSourceUrls() in plugins yet');
    }

    public function getStability(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getStability() in plugins yet');
    }

    public function getSuggests(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getSuggests() in plugins yet');
    }

    public function getTargetDir(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getTargetDir() in plugins yet');
    }

    public function getTransportOptions(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getTransportOptions() in plugins yet');
    }

    public function getType(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getType() in plugins yet');
    }

    protected function getUrls(?string $url, ?array $mirrors, ?string $ref, ?string $type, string $urlType): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getUrls() in plugins yet');
    }

    public function getVersion(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::getVersion() in plugins yet');
    }

    public function isDefaultBranch(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::isDefaultBranch() in plugins yet');
    }

    public function isDev(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::isDev() in plugins yet');
    }

    public function replaceVersion(string $version, string $prettyVersion): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::replaceVersion() in plugins yet');
    }

    public function setAutoload(array $autoload): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setAutoload() in plugins yet');
    }

    public function setBinaries(array $binaries): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setBinaries() in plugins yet');
    }

    public function setConflicts(array $conflicts): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setConflicts() in plugins yet');
    }

    public function setDevAutoload(array $devAutoload): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setDevAutoload() in plugins yet');
    }

    public function setDevRequires(array $devRequires): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setDevRequires() in plugins yet');
    }

    public function setDistMirrors(?array $mirrors): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setDistMirrors() in plugins yet');
    }

    public function setDistReference(?string $reference): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setDistReference() in plugins yet');
    }

    public function setDistSha1Checksum(?string $sha1checksum): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setDistSha1Checksum() in plugins yet');
    }

    public function setDistType(?string $type): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setDistType() in plugins yet');
    }

    public function setDistUrl(?string $url): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setDistUrl() in plugins yet');
    }

    public function setExtra(array $extra): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setExtra() in plugins yet');
    }

    public function setIncludePaths(array $includePaths): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setIncludePaths() in plugins yet');
    }

    public function setInstallationSource(?string $type): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setInstallationSource() in plugins yet');
    }

    public function setIsDefaultBranch(bool $defaultBranch): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setIsDefaultBranch() in plugins yet');
    }

    public function setNotificationUrl(string $notificationUrl): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setNotificationUrl() in plugins yet');
    }

    public function setPhpExt(?array $phpExt): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setPhpExt() in plugins yet');
    }

    public function setProvides(array $provides): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setProvides() in plugins yet');
    }

    public function setReleaseDate(?\DateTimeInterface $releaseDate): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setReleaseDate() in plugins yet');
    }

    public function setReplaces(array $replaces): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setReplaces() in plugins yet');
    }

    public function setRequires(array $requires): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setRequires() in plugins yet');
    }

    public function setSourceDistReferences(string $reference): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setSourceDistReferences() in plugins yet');
    }

    public function setSourceMirrors(?array $mirrors): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setSourceMirrors() in plugins yet');
    }

    public function setSourceReference(?string $reference): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setSourceReference() in plugins yet');
    }

    public function setSourceType(?string $type): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setSourceType() in plugins yet');
    }

    public function setSourceUrl(?string $url): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setSourceUrl() in plugins yet');
    }

    public function setSuggests(array $suggests): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setSuggests() in plugins yet');
    }

    public function setTargetDir(?string $targetDir): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setTargetDir() in plugins yet');
    }

    public function setTransportOptions(array $options): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setTransportOptions() in plugins yet');
    }

    public function setType(string $type): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Package::setType() in plugins yet');
    }
}
