<?php

/*
 * maestro's plugin shim (docs/PLUGINS.md §5.1). Not part of Composer.
 * Written for PHP 7.2.5 to 8.5.
 */

namespace Maestro\Shim;

/**
 * The shim's class loader: one static class map over the shim, its stubs
 * and the vendored libraries (autoload.php, generated by tools/shimgen),
 * registered before anything else so its classes win over a project's
 * copies of the same names, as the phar's do.
 */
final class Autoloader
{
    /** @var array<string, string> class => absolute file */
    private static $classMap = [];

    /**
     * Registers the loader (prepended) and requires the vendored libraries'
     * autoload `files` in the phar's order, marking them in
     * $GLOBALS['__composer_autoload_files'] as Composer's own autoloader
     * does, so a project's autoloader skips its copies of them.
     */
    public static function register(string $root): void
    {
        $index = require $root.'/autoload.php';
        foreach ($index['classmap'] as $class => $file) {
            self::$classMap[$class] = $root.'/'.$file;
        }

        spl_autoload_register([self::class, 'loadClass'], true, true);

        // The phar's classes load through a ClassLoader of its vendor
        // directory, through which InstalledVersions also reports the
        // packages Composer bundles (lib/composer/installed.php); this one
        // only stands for it in ClassLoader::getRegisteredLoaders().
        $bundled = new \Composer\Autoload\ClassLoader($root.'/lib');
        $bundled->setClassMapAuthoritative(true);
        $bundled->register(false);

        foreach ($index['files'] as $id => $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$id])) {
                $GLOBALS['__composer_autoload_files'][$id] = true;
                self::requireFile($root.'/'.$file);
            }
        }
    }

    /**
     * @param string $class
     */
    public static function loadClass($class): void
    {
        if (!isset(self::$classMap[$class])) {
            return;
        }
        // the Console classes whose methods enter frames (SymfonyHooks)
        if ($class === 'Symfony\\Component\\Console\\Application' || $class === 'Symfony\\Component\\Console\\Command\\Command') {
            SymfonyHooks::load($class, self::$classMap[$class]);

            return;
        }
        self::requireFile(self::$classMap[$class]);
    }

    /**
     * Requires a file without exposing $this or the loader's locals to it.
     */
    private static function requireFile(string $file): void
    {
        require $file;
    }
}
