// Ports the proxy heredocs of src/Composer/Installer/BinaryInstaller.php
// (generateUnixyProxyCode), transcribed mechanically from the PHP source
// with PHP's heredoc escapes applied. The bin proxy oracle test checks the
// files they produce byte for byte.

package installer

// streamProxyCode is the STREAMPROXY heredoc of generateUnixyProxyCode.
func streamProxyCode(phpunitHack1, phpunitHack2, binPathExported string) string {
	return "if (PHP_VERSION_ID < 80000) {\n    if (!class_exists('Composer\\BinProxyWrapper')) {\n        /**\n         * @internal\n         */\n        final class BinProxyWrapper\n        {\n            private $handle;\n            private $position;\n            private $realpath;\n\n            public function stream_open($path, $mode, $options, &$opened_path)\n            {\n                // get rid of phpvfscomposer:// prefix for __FILE__ & __DIR__ resolution\n                $opened_path = substr($path, 17);\n                $this->realpath = realpath($opened_path) ?: $opened_path;\n                $opened_path = " +
		phpunitHack1 +
		"$this->realpath;\n                $this->handle = fopen($this->realpath, $mode);\n                $this->position = 0;\n\n                return (bool) $this->handle;\n            }\n\n            public function stream_read($count)\n            {\n                $data = fread($this->handle, $count);\n\n                if ($this->position === 0) {\n                    $data = preg_replace('{^#!.*\\r?\\n}', '', $data);\n                }" +
		phpunitHack2 +
		"\n\n                $this->position += strlen($data);\n\n                return $data;\n            }\n\n            public function stream_cast($castAs)\n            {\n                return $this->handle;\n            }\n\n            public function stream_close()\n            {\n                fclose($this->handle);\n            }\n\n            public function stream_lock($operation)\n            {\n                return $operation ? flock($this->handle, $operation) : true;\n            }\n\n            public function stream_seek($offset, $whence)\n            {\n                if (0 === fseek($this->handle, $offset, $whence)) {\n                    $this->position = ftell($this->handle);\n                    return true;\n                }\n\n                return false;\n            }\n\n            public function stream_tell()\n            {\n                return $this->position;\n            }\n\n            public function stream_eof()\n            {\n                return feof($this->handle);\n            }\n\n            public function stream_stat()\n            {\n                return array();\n            }\n\n            public function stream_set_option($option, $arg1, $arg2)\n            {\n                return true;\n            }\n\n            public function url_stat($path, $flags)\n            {\n                $path = substr($path, 17);\n                if (file_exists($path)) {\n                    return stat($path);\n                }\n\n                return false;\n            }\n        }\n    }\n\n    if (\n        (function_exists('stream_get_wrappers') && in_array('phpvfscomposer', stream_get_wrappers(), true))\n        || (function_exists('stream_wrapper_register') && stream_wrapper_register('phpvfscomposer', 'Composer\\BinProxyWrapper'))\n    ) {\n        return include(\"phpvfscomposer://\" . " +
		binPathExported +
		");\n    }\n}\n"
}

// phpProxyCode is the PHP proxy heredoc of generateUnixyProxyCode, without
// the shebang line.
func phpProxyCode(binPathExported, binPath, streamHint, globalsCode, streamProxyCode string) string {
	return "<?php\n\n/**\n * Proxy PHP file generated by Composer\n *\n * This file includes the referenced bin path (" +
		binPath +
		")\n *" +
		streamHint +
		"\n * @generated\n */\n\nnamespace Composer;\n\n" +
		globalsCode +
		"\n" +
		streamProxyCode +
		"\nreturn include " +
		binPathExported +
		";\n"
}

// shellProxyCode is the shell proxy heredoc of generateUnixyProxyCode.
func shellProxyCode(binDir, binFile string) string {
	return "#!/usr/bin/env sh\n\n# Support bash to support `source` with fallback on $0 if this does not run with bash\n# https://stackoverflow.com/a/35006505/6512\nselfArg=\"$BASH_SOURCE\"\nif [ -z \"$selfArg\" ]; then\n    selfArg=\"$0\"\nfi\n\nself=$(realpath \"$selfArg\" 2> /dev/null)\nif [ -z \"$self\" ]; then\n    self=\"$selfArg\"\nfi\n\ndir=$(cd \"${self%[/\\\\]*}\" > /dev/null; cd " +
		binDir +
		" && pwd)\n\nif [ -d /proc/cygdrive ]; then\n    case $(which php) in\n        $(readlink -n /proc/cygdrive)/*)\n            # We are in Cygwin using Windows php, so the path must be translated\n            dir=$(cygpath -m \"$dir\");\n            ;;\n    esac\nfi\n\nexport COMPOSER_RUNTIME_BIN_DIR=\"$(cd \"${self%[/\\\\]*}\" > /dev/null; pwd)\"\n\n# If bash is sourcing this file, we have to source the target as well\nbashSource=\"$BASH_SOURCE\"\nif [ -n \"$bashSource\" ]; then\n    if [ \"$bashSource\" != \"$0\" ]; then\n        source \"${dir}/" +
		binFile +
		"\" \"$@\"\n        return\n    fi\nfi\n\nexec \"${dir}/" +
		binFile +
		"\" \"$@\"\n"
}
