<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Loader;

class ArrayLoader implements \Composer\Package\Loader\LoaderInterface
{
    protected $loadOptions;
    protected $versionParser;

    public function __construct(?\Composer\Package\Version\VersionParser $parser = null, bool $loadOptions = false)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\ArrayLoader::__construct() in plugins yet');
    }

    public function getBranchAlias(array $config): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\ArrayLoader::getBranchAlias() in plugins yet');
    }

    public function load(array $config, string $class = 'Composer\\Package\\CompletePackage'): \Composer\Package\BasePackage
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\ArrayLoader::load() in plugins yet');
    }

    public function loadPackages(array $versions): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\ArrayLoader::loadPackages() in plugins yet');
    }

    public function parseLinks(string $source, string $sourceVersion, string $description, array $links): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\ArrayLoader::parseLinks() in plugins yet');
    }
}
