<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Loader;

class InvalidPackageException extends \Exception
{
    public function __construct(array $errors, array $warnings, array $data)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\InvalidPackageException::__construct() in plugins yet');
    }

    public function getData(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\InvalidPackageException::getData() in plugins yet');
    }

    public function getErrors(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\InvalidPackageException::getErrors() in plugins yet');
    }

    public function getWarnings(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\InvalidPackageException::getWarnings() in plugins yet');
    }
}
