<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Loader;

class JsonLoader
{
    public function __construct(\Composer\Package\Loader\LoaderInterface $loader)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\JsonLoader::__construct() in plugins yet');
    }

    public function load($json): \Composer\Package\BasePackage
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\JsonLoader::load() in plugins yet');
    }
}
