<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Loader;

class RootPackageLoader extends \Composer\Package\Loader\ArrayLoader
{
    public function __construct(\Composer\Repository\RepositoryManager $manager, \Composer\Config $config, ?\Composer\Package\Version\VersionParser $parser = null, ?\Composer\Package\Version\VersionGuesser $versionGuesser = null, ?\Composer\IO\IOInterface $io = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\RootPackageLoader::__construct() in plugins yet');
    }

    public static function extractReferences(array $requires, array $references): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\RootPackageLoader::extractReferences() in plugins yet');
    }

    public static function extractStabilityFlags(array $requires, string $minimumStability, array $stabilityFlags): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\RootPackageLoader::extractStabilityFlags() in plugins yet');
    }

    public function load(array $config, string $class = 'Composer\\Package\\RootPackage', ?string $cwd = null): \Composer\Package\BasePackage
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Loader\\RootPackageLoader::load() in plugins yet');
    }
}
