<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\SelfUpdate;

class Keys
{
    public static function fingerprint(string $path): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\SelfUpdate\\Keys::fingerprint() in plugins yet');
    }
}
