<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util\Http;

class CurlResponse extends \Composer\Util\Http\Response
{
    public function __construct(array $request, ?int $code, array $headers, ?string $body, array $curlInfo)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\CurlResponse::__construct() in plugins yet');
    }

    public function getCurlInfo(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\CurlResponse::getCurlInfo() in plugins yet');
    }
}
