<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util\Http;

class CurlDownloader
{
    protected $multiErrors = [1 => ['CURLM_BAD_HANDLE', 'The passed-in handle is not a valid CURLM handle.'], 2 => ['CURLM_BAD_EASY_HANDLE', 'An easy handle was not good/valid. It could mean that it isn\'t an easy handle at all, or possibly that the handle already is in used by this or another multi handle.'], 3 => ['CURLM_OUT_OF_MEMORY', 'You are doomed.'], 4 => ['CURLM_INTERNAL_ERROR', 'This can only be returned if libcurl bugs. Please report it to us!']];

    public function __construct(\Composer\IO\IOInterface $io, \Composer\Config $config, array $options = [], bool $disableTls = false)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\CurlDownloader::__construct() in plugins yet');
    }

    public function abortRequest(int $id): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\CurlDownloader::abortRequest() in plugins yet');
    }

    public function download(callable $resolve, callable $reject, string $origin, string $url, array $options, ?string $copyTo = null): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\CurlDownloader::download() in plugins yet');
    }

    public function tick(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\CurlDownloader::tick() in plugins yet');
    }
}
