<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util\Http;

class ProxyManager
{
    public static function getInstance(): \Composer\Util\Http\ProxyManager
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\ProxyManager::getInstance() in plugins yet');
    }

    public function getProxyForRequest(string $requestUrl): \Composer\Util\Http\RequestProxy
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\ProxyManager::getProxyForRequest() in plugins yet');
    }

    public function hasProxy(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\ProxyManager::hasProxy() in plugins yet');
    }

    public static function reset(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\ProxyManager::reset() in plugins yet');
    }
}
