<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util\Http;

class RequestProxy
{
    public function __construct(?string $url, ?string $auth, ?array $contextOptions, ?string $status)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\RequestProxy::__construct() in plugins yet');
    }

    public function getContextOptions(): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\RequestProxy::getContextOptions() in plugins yet');
    }

    public function getCurlOptions(array $sslOptions): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\RequestProxy::getCurlOptions() in plugins yet');
    }

    public function getStatus(?string $format = null): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\RequestProxy::getStatus() in plugins yet');
    }

    public function isExcludedByNoProxy(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\RequestProxy::isExcludedByNoProxy() in plugins yet');
    }

    public function isSecure(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\RequestProxy::isSecure() in plugins yet');
    }

    public static function noProxy(): \Composer\Util\Http\RequestProxy
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\RequestProxy::noProxy() in plugins yet');
    }

    public static function none(): \Composer\Util\Http\RequestProxy
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\RequestProxy::none() in plugins yet');
    }

    public function supportsSecureProxy(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\RequestProxy::supportsSecureProxy() in plugins yet');
    }
}
