<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Util\Http;

class Response
{
    public function __construct(array $request, ?int $code, array $headers, ?string $body)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\Response::__construct() in plugins yet');
    }

    public function collect(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\Response::collect() in plugins yet');
    }

    public function decodeJson()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\Response::decodeJson() in plugins yet');
    }

    public static function findHeaderValue(array $headers, string $name): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\Response::findHeaderValue() in plugins yet');
    }

    public function getBody(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\Response::getBody() in plugins yet');
    }

    public function getHeader(string $name): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\Response::getHeader() in plugins yet');
    }

    public function getHeaders(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\Response::getHeaders() in plugins yet');
    }

    public function getStatusCode(): int
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\Response::getStatusCode() in plugins yet');
    }

    public function getStatusMessage(): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Util\\Http\\Response::getStatusMessage() in plugins yet');
    }
}
