<?php

/*
 * maestro's plugin shim: Composer\Package\Package, reimplemented with
 * Composer 2.10.3's behaviour (docs/PLUGINS.md §4.5). See BasePackage for
 * how a Go-owned package mirrors maestro's; its setters change maestro's
 * package (pkg.<setter>), whose new state reaches PHP before they return.
 * Generated by hand from Composer's API; written for PHP 7.2.5 to 8.5.
 */

namespace Composer\Package;

use Composer\Package\Version\VersionParser;
use Composer\Pcre\Preg;
use Maestro\Shim\Remote;
use Maestro\Shim\Rpc;

class Package extends BasePackage
{
    protected $type;
    protected $targetDir;
    protected $installationSource;
    protected $sourceType;
    protected $sourceUrl;
    protected $sourceReference;
    protected $sourceMirrors;
    protected $distType;
    protected $distUrl;
    protected $distReference;
    protected $distSha1Checksum;
    protected $distMirrors;
    protected $version;
    protected $prettyVersion;
    protected $releaseDate;
    protected $extra = [];
    protected $binaries = [];
    protected $dev;
    protected $stability;
    protected $notificationUrl;
    protected $requires = [];
    protected $conflicts = [];
    protected $provides = [];
    protected $replaces = [];
    protected $devRequires = [];
    protected $suggests = [];
    protected $autoload = [];
    protected $devAutoload = [];
    protected $includePaths = [];
    protected $isDefaultBranch = false;
    protected $transportOptions = [];
    protected $phpExt = null;

    public function __construct(string $name, string $version, string $prettyVersion)
    {
        parent::__construct($name);

        $this->version = $version;
        $this->prettyVersion = $prettyVersion;

        $this->stability = VersionParser::parseStability($version);
        $this->dev = $this->stability === 'dev';
    }

    public function isDev(): bool
    {
        return $this->dev;
    }

    public function getType(): string
    {
        return $this->type ?: 'library';
    }

    public function getStability(): string
    {
        return $this->stability;
    }

    public function getTargetDir(): ?string
    {
        \Maestro\Shim\LazyPackages::load($this);
        if (null === $this->targetDir) {
            return null;
        }

        return ltrim(Preg::replace('{ (?:^|[\\\\/]+) \.\.? (?:[\\\\/]+|$) (?:\.\.? (?:[\\\\/]+|$) )*}x', '/', $this->targetDir), '/');
    }

    public function getExtra(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->extra;
    }

    public function getBinaries(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->binaries;
    }

    public function getInstallationSource(): ?string
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->installationSource;
    }

    public function getSourceType(): ?string
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->sourceType;
    }

    public function getSourceUrl(): ?string
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->sourceUrl;
    }

    public function getSourceReference(): ?string
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->sourceReference;
    }

    public function getSourceMirrors(): ?array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->sourceMirrors;
    }

    public function getSourceUrls(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        if (Remote::owned($this)) {
            return Rpc::call('pkg.getSourceUrls', [$this]);
        }

        return $this->getUrls($this->sourceUrl, $this->sourceMirrors, $this->sourceReference, $this->sourceType, 'source');
    }

    public function getDistType(): ?string
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->distType;
    }

    public function getDistUrl(): ?string
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->distUrl;
    }

    public function getDistReference(): ?string
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->distReference;
    }

    public function getDistSha1Checksum(): ?string
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->distSha1Checksum;
    }

    public function getDistMirrors(): ?array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->distMirrors;
    }

    public function getDistUrls(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        if (Remote::owned($this)) {
            return Rpc::call('pkg.getDistUrls', [$this]);
        }

        return $this->getUrls($this->distUrl, $this->distMirrors, $this->distReference, $this->distType, 'dist');
    }

    public function getTransportOptions(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->transportOptions;
    }

    public function getVersion(): string
    {
        return $this->version;
    }

    public function getPrettyVersion(): string
    {
        return $this->prettyVersion;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->releaseDate;
    }

    public function getRequires(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->requires;
    }

    public function getConflicts(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->conflicts;
    }

    public function getProvides(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->provides;
    }

    public function getReplaces(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->replaces;
    }

    public function getDevRequires(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->devRequires;
    }

    public function getSuggests(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->suggests;
    }

    public function getAutoload(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->autoload;
    }

    public function getDevAutoload(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->devAutoload;
    }

    public function getIncludePaths(): array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->includePaths;
    }

    public function getPhpExt(): ?array
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->phpExt;
    }

    public function getNotificationUrl(): ?string
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->notificationUrl;
    }

    public function isDefaultBranch(): bool
    {
        \Maestro\Shim\LazyPackages::load($this);
        return $this->isDefaultBranch;
    }

    public function setType(string $type): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setType', [$this, $type]);

            return;
        }
        $this->type = $type;
    }

    public function setTargetDir(?string $targetDir): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setTargetDir', [$this, $targetDir]);

            return;
        }
        $this->targetDir = $targetDir;
    }

    public function setExtra(array $extra): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setExtra', [$this, $extra]);

            return;
        }
        $this->extra = $extra;
    }

    public function setBinaries(array $binaries): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setBinaries', [$this, $binaries]);

            return;
        }
        $this->binaries = $binaries;
    }

    public function setInstallationSource(?string $type): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setInstallationSource', [$this, $type]);

            return;
        }
        $this->installationSource = $type;
    }

    public function setSourceType(?string $type): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setSourceType', [$this, $type]);

            return;
        }
        $this->sourceType = $type;
    }

    public function setSourceUrl(?string $url): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setSourceUrl', [$this, $url]);

            return;
        }
        $this->sourceUrl = $url;
    }

    public function setSourceReference(?string $reference): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setSourceReference', [$this, $reference]);

            return;
        }
        $this->sourceReference = $reference;
    }

    public function setSourceMirrors(?array $mirrors): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setSourceMirrors', [$this, $mirrors]);

            return;
        }
        $this->sourceMirrors = $mirrors;
    }

    public function setDistType(?string $type): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setDistType', [$this, $type]);

            return;
        }
        $this->distType = $type === '' ? null : $type;
    }

    public function setDistUrl(?string $url): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setDistUrl', [$this, $url]);

            return;
        }
        $this->distUrl = $url === '' ? null : $url;
    }

    public function setDistReference(?string $reference): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setDistReference', [$this, $reference]);

            return;
        }
        $this->distReference = $reference;
    }

    public function setDistSha1Checksum(?string $sha1checksum): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setDistSha1Checksum', [$this, $sha1checksum]);

            return;
        }
        $this->distSha1Checksum = $sha1checksum;
    }

    public function setDistMirrors(?array $mirrors): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setDistMirrors', [$this, $mirrors]);

            return;
        }
        $this->distMirrors = $mirrors;
    }

    public function setTransportOptions(array $options): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setTransportOptions', [$this, $options]);

            return;
        }
        $this->transportOptions = $options;
    }

    public function setReleaseDate(?\DateTimeInterface $releaseDate): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setReleaseDate', [$this, $releaseDate]);

            return;
        }
        $this->releaseDate = $releaseDate;
    }

    public function setSuggests(array $suggests): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setSuggests', [$this, $suggests]);

            return;
        }
        $this->suggests = $suggests;
    }

    public function setAutoload(array $autoload): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setAutoload', [$this, $autoload]);

            return;
        }
        $this->autoload = $autoload;
    }

    public function setDevAutoload(array $devAutoload): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setDevAutoload', [$this, $devAutoload]);

            return;
        }
        $this->devAutoload = $devAutoload;
    }

    public function setIncludePaths(array $includePaths): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setIncludePaths', [$this, $includePaths]);

            return;
        }
        $this->includePaths = $includePaths;
    }

    public function setPhpExt(?array $phpExt): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setPhpExt', [$this, $phpExt]);

            return;
        }
        $this->phpExt = $phpExt;
    }

    public function setNotificationUrl(string $notificationUrl): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setNotificationUrl', [$this, $notificationUrl]);

            return;
        }
        $this->notificationUrl = $notificationUrl;
    }

    public function setIsDefaultBranch(bool $defaultBranch): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setIsDefaultBranch', [$this, $defaultBranch]);

            return;
        }
        $this->isDefaultBranch = $defaultBranch;
    }

    public function setRequires(array $requires): void
    {
        if (isset($requires[0])) {
            $requires = $this->convertLinksToMap($requires, 'setRequires');
        }
        if (Remote::owned($this)) {
            Rpc::call('pkg.setRequires', [$this, $requires]);

            return;
        }
        $this->requires = $requires;
    }

    public function setConflicts(array $conflicts): void
    {
        if (isset($conflicts[0])) {
            $conflicts = $this->convertLinksToMap($conflicts, 'setConflicts');
        }
        if (Remote::owned($this)) {
            Rpc::call('pkg.setConflicts', [$this, $conflicts]);

            return;
        }
        $this->conflicts = $conflicts;
    }

    public function setProvides(array $provides): void
    {
        if (isset($provides[0])) {
            $provides = $this->convertLinksToMap($provides, 'setProvides');
        }
        if (Remote::owned($this)) {
            Rpc::call('pkg.setProvides', [$this, $provides]);

            return;
        }
        $this->provides = $provides;
    }

    public function setReplaces(array $replaces): void
    {
        if (isset($replaces[0])) {
            $replaces = $this->convertLinksToMap($replaces, 'setReplaces');
        }
        if (Remote::owned($this)) {
            Rpc::call('pkg.setReplaces', [$this, $replaces]);

            return;
        }
        $this->replaces = $replaces;
    }

    public function setDevRequires(array $devRequires): void
    {
        if (isset($devRequires[0])) {
            $devRequires = $this->convertLinksToMap($devRequires, 'setDevRequires');
        }
        if (Remote::owned($this)) {
            Rpc::call('pkg.setDevRequires', [$this, $devRequires]);

            return;
        }
        $this->devRequires = $devRequires;
    }

    public function setSourceDistReferences(string $reference): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.setSourceDistReferences', [$this, $reference]);

            return;
        }
        $this->setSourceReference($reference);

        // only bitbucket, github and gitlab have auto generated dist URLs that easily allow replacing the reference in the dist URL
        if (
            $this->getDistUrl() !== null
            && Preg::isMatch('{^https?://(?:(?:www\.)?bitbucket\.org|(api\.)?github\.com|(?:www\.)?gitlab\.com)/}i', $this->getDistUrl())
        ) {
            $this->setDistReference($reference);
            $this->setDistUrl(Preg::replace('{(?<=/|sha=)[a-f0-9]{40}(?=/|$)}i', $reference, $this->getDistUrl()));
        } elseif ($this->getDistReference()) { // update the dist reference if there was one, but if none was provided ignore it
            $this->setDistReference($reference);
        }
    }

    public function replaceVersion(string $version, string $prettyVersion): void
    {
        if (Remote::owned($this)) {
            Rpc::call('pkg.replaceVersion', [$this, $version, $prettyVersion]);

            return;
        }
        $this->version = $version;
        $this->prettyVersion = $prettyVersion;

        $this->stability = VersionParser::parseStability($version);
        $this->dev = $this->stability === 'dev';
    }

    protected function getUrls(?string $url, ?array $mirrors, ?string $ref, ?string $type, string $urlType): array
    {
        if (!$url) {
            return [];
        }

        if (($urlType === 'dist' && false !== strpos($url, '%')) || $mirrors) {
            // ComposerMirror's URL processing is maestro's.
            return Rpc::call('pkg.urls', [$url, $mirrors, $ref, $type, $urlType, $this->name, $this->version, $this->prettyVersion]);
        }

        return [$url];
    }

    /**
     * @param array<int, Link> $links
     * @return array<string, Link>
     */
    private function convertLinksToMap(array $links, string $source): array
    {
        trigger_error('Package::'.$source.' must be called with a map of lowercased package name => Link object, got a indexed array, this is deprecated and you should fix your usage.'); // @line 716
        $newLinks = [];
        foreach ($links as $link) {
            $newLinks[$link->getTarget()] = $link;
        }

        return $newLinks;
    }
}
