<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Policy;

class AdvisoriesPolicyConfig extends \Composer\Policy\ListPolicyConfig
{
    public const NAME = 'advisories';

    public $ignoreId;
    public $ignoreSeverity;

    public function __construct(bool $block, string $audit, array $ignore, array $ignoreId, array $ignoreSeverity)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\AdvisoriesPolicyConfig::__construct() in plugins yet');
    }

    public static function disabled(): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\AdvisoriesPolicyConfig::disabled() in plugins yet');
    }

    public static function fromRawConfig(array $policyConfig, array $auditConfig, \Composer\Semver\VersionParser $parser): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\AdvisoriesPolicyConfig::fromRawConfig() in plugins yet');
    }

    public function getIgnoreIdForOperation(string $operation): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\AdvisoriesPolicyConfig::getIgnoreIdForOperation() in plugins yet');
    }

    public function getIgnoreListForOperation(string $operation): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\AdvisoriesPolicyConfig::getIgnoreListForOperation() in plugins yet');
    }

    public function getIgnoreSeverityForOperation(string $operation): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\AdvisoriesPolicyConfig::getIgnoreSeverityForOperation() in plugins yet');
    }

    public function withAudit(string $audit)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\AdvisoriesPolicyConfig::withAudit() in plugins yet');
    }

    public function withBlockingDisabled()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\AdvisoriesPolicyConfig::withBlockingDisabled() in plugins yet');
    }

    public function withIgnoreSeverity(array $severities)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\AdvisoriesPolicyConfig::withIgnoreSeverity() in plugins yet');
    }
}
