<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Policy;

class IgnoreSeverityRule
{
    public $onAudit;
    public $onBlock;
    public $reason;
    public $severity;

    public function __construct(string $severity, ?string $reason = null, bool $onBlock = true, bool $onAudit = true)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\IgnoreSeverityRule::__construct() in plugins yet');
    }

    public static function parseIgnoreSeverityMap(array $config): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\IgnoreSeverityRule::parseIgnoreSeverityMap() in plugins yet');
    }
}
