<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Policy;

class PolicyConfig
{
    public const BUILTIN_LIST_NAMES = ['advisories', 'abandoned', 'malware'];
    public const FUTURE_RESERVED_NAMES = ['package', 'packages', 'license', 'licence', 'licenses', 'licences', 'support', 'maintenance', 'security', 'minimum-release-age'];
    public const FUTURE_RESERVED_PREFIXES = ['ignore'];
    public const NON_LIST_KEYS = ['ignore-unreachable'];
    public const RESERVED_NAMES = ['advisories', 'abandoned'];

    public $abandoned;
    public $advisories;
    public $customLists;
    public $enabled;
    public $ignoreUnreachable;
    public $malware;

    public function __construct(bool $enabled, \Composer\Policy\AdvisoriesPolicyConfig $advisories, \Composer\Policy\MalwarePolicyConfig $malware, \Composer\Policy\ListPolicyConfig $abandoned, array $customLists, \Composer\Policy\IgnoreUnreachable $ignoreUnreachable)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::__construct() in plugins yet');
    }

    public static function fromConfig(\Composer\Config $config): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::fromConfig() in plugins yet');
    }

    public function getActiveAuditFilterListNames(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::getActiveAuditFilterListNames() in plugins yet');
    }

    public function getActiveAuditFilterLists(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::getActiveAuditFilterLists() in plugins yet');
    }

    public function getActiveBlockFilterListNames(string $blockScope): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::getActiveBlockFilterListNames() in plugins yet');
    }

    public function getActiveBlockFilterLists(string $blockScope): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::getActiveBlockFilterLists() in plugins yet');
    }

    public function getAllLists(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::getAllLists() in plugins yet');
    }

    public function getCustomListsWithSources(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::getCustomListsWithSources() in plugins yet');
    }

    public static function getFutureReservedListNameError(string $listName): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::getFutureReservedListNameError() in plugins yet');
    }

    public function withAudit(?string $abandoned)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::withAudit() in plugins yet');
    }

    public function withBlockingDisabled(): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::withBlockingDisabled() in plugins yet');
    }

    public function withIgnoreSeverity(array $severities): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::withIgnoreSeverity() in plugins yet');
    }

    public function withIgnoreUnreachable(string ...$scopes): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Policy\\PolicyConfig::withIgnoreUnreachable() in plugins yet');
    }
}
