<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Json;

class JsonManipulator
{
    public function __construct(string $contents)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::__construct() in plugins yet');
    }

    public function addConfigSetting(string $name, $value): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::addConfigSetting() in plugins yet');
    }

    public function addLink(string $type, string $package, string $constraint, bool $sortPackages = false): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::addLink() in plugins yet');
    }

    public function addListItem(string $mainNode, $value, bool $append = true): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::addListItem() in plugins yet');
    }

    public function addMainKey(string $key, $content): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::addMainKey() in plugins yet');
    }

    public function addProperty(string $name, $value): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::addProperty() in plugins yet');
    }

    public function addRepository(string $name, $config, bool $append = true): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::addRepository() in plugins yet');
    }

    public function addSubNode(string $mainNode, string $name, $value, bool $append = true): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::addSubNode() in plugins yet');
    }

    public function changeEmptyMainKeyFromAssocToList(string $key): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::changeEmptyMainKeyFromAssocToList() in plugins yet');
    }

    protected function detectIndenting(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::detectIndenting() in plugins yet');
    }

    public function format($data, int $depth = 0, bool $wasObject = false): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::format() in plugins yet');
    }

    public function getContents(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::getContents() in plugins yet');
    }

    public function insertListItem(string $mainNode, $value, int $index): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::insertListItem() in plugins yet');
    }

    public function insertRepository(string $name, $config, string $referenceName, int $offset = 0): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::insertRepository() in plugins yet');
    }

    public function removeConfigSetting(string $name): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::removeConfigSetting() in plugins yet');
    }

    public function removeListItem(string $mainNode, int $nodeIndex): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::removeListItem() in plugins yet');
    }

    public function removeMainKey(string $key): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::removeMainKey() in plugins yet');
    }

    public function removeMainKeyIfEmpty(string $key): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::removeMainKeyIfEmpty() in plugins yet');
    }

    public function removeProperty(string $name): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::removeProperty() in plugins yet');
    }

    public function removeRepository(string $name): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::removeRepository() in plugins yet');
    }

    public function removeSubNode(string $mainNode, string $name): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::removeSubNode() in plugins yet');
    }

    public function setRepositoryUrl(string $name, string $url): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonManipulator::setRepositoryUrl() in plugins yet');
    }
}
