<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Json;

class JsonFormatter
{
    public static function format(string $json, bool $unescapeUnicode, bool $unescapeSlashes): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Json\\JsonFormatter::format() in plugins yet');
    }
}
