package config

import (
	stdjson "encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"testing"

	"github.com/stubbedev/maestro/internal/json"
	"github.com/stubbedev/maestro/internal/php"
	"github.com/stubbedev/maestro/internal/testutil"
)

// Replays testdata/oracle/configsource.json.gz, generated by
// tools/oracle/config/configsource.php: JsonConfigSource operations on
// generated files, including the whole-file fallbacks.
func TestJsonConfigSourceOracle(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("file modes")
	}
	raw, err := testutil.ReadGoldenFile("testdata/oracle/configsource.json.gz")
	if err != nil {
		t.Fatal(err)
	}
	var cases []struct {
		Doc  *string `json:"doc"`
		Auth bool    `json:"auth"`
		Ops  []struct {
			Method   string     `json:"method"`
			Args     string     `json:"args"`
			E        *[2]string `json:"e"`
			Contents *string    `json:"contents"`
			Mode     *string    `json:"mode"`
		} `json:"ops"`
	}
	if err := stdjson.Unmarshal(raw, &cases); err != nil {
		t.Fatal(err)
	}
	defer setUmask(0o022)()

	dir := t.TempDir()
	path := filepath.Join(dir, "composer.json")
	for i, c := range cases {
		_ = os.Remove(path)
		if c.Doc != nil {
			if err := os.WriteFile(path, []byte(*c.Doc), 0o644); err != nil {
				t.Fatal(err)
			}
		}
		file, err := json.NewFile(path, nil, nil)
		if err != nil {
			t.Fatal(err)
		}
		source := NewJSONConfigSource(file, c.Auth)
		for j, op := range c.Ops {
			where := "case " + strconv.Itoa(i) + " op " + strconv.Itoa(j) + " " + op.Method + op.Args
			args := getArray(t, mustDecode(t, op.Args)).Values()
			err := callSource(source, op.Method, args)
			if op.E != nil {
				if err == nil {
					t.Errorf("%s: no error, want %s: %s", where, op.E[0], op.E[1])
				} else if class, msg := errorClass(err), strings.ReplaceAll(err.Error(), dir, "<DIR>"); class != op.E[0] || msg != op.E[1] {
					t.Errorf("%s: got %s: %s\nwant %s: %s", where, class, msg, op.E[0], op.E[1])
				}
			} else if err != nil {
				t.Errorf("%s: unexpected %s: %v", where, errorClass(err), err)
			}

			data, readErr := os.ReadFile(path)
			switch {
			case op.Contents == nil && readErr == nil:
				t.Errorf("%s: file exists, want none", where)
			case op.Contents != nil && readErr != nil:
				t.Errorf("%s: no file, want %q", where, *op.Contents)
			case op.Contents != nil && string(data) != *op.Contents:
				t.Errorf("%s: contents\n%s\nwant\n%s", where, data, *op.Contents)
			}
			if op.Mode != nil && readErr == nil {
				fi, _ := os.Stat(path)
				if mode := strconv.FormatUint(uint64(fi.Mode().Perm()), 8); mode != *op.Mode {
					t.Errorf("%s: mode %s, want %s", where, mode, *op.Mode)
				}
			}
		}
	}
}

func mustDecode(t *testing.T, s string) any {
	t.Helper()
	v, err := php.JSONDecode(s, true)
	if err != nil {
		t.Fatalf("%s: %v", s, err)
	}

	return v
}

func callSource(s *JSONConfigSource, method string, args []any) error {
	str := func(i int) string { return args[i].(string) }
	switch method {
	case "addRepository":
		return s.AddRepository(str(0), args[1], args[2].(bool))
	case "insertRepository":
		return s.InsertRepository(str(0), args[1], str(2), int(args[3].(int64)))
	case "setRepositoryUrl":
		return s.SetRepositoryURL(str(0), str(1))
	case "removeRepository":
		return s.RemoveRepository(str(0))
	case "addConfigSetting":
		return s.AddConfigSetting(str(0), args[1])
	case "removeConfigSetting":
		return s.RemoveConfigSetting(str(0))
	case "addProperty":
		return s.AddProperty(str(0), args[1])
	case "removeProperty":
		return s.RemoveProperty(str(0))
	case "addLink":
		return s.AddLink(str(0), str(1), str(2))
	case "removeLink":
		return s.RemoveLink(str(0), str(1))
	}
	panic(method)
}
