package config

import (
	stdjson "encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"testing"

	"github.com/stubbedev/maestro/internal/io"
	"github.com/stubbedev/maestro/internal/php"
)

// Replays testdata/oracle/factory.json, generated by
// tools/oracle/config/factory.php: HomeDir, CacheDir, DataDir,
// CreateConfig, ComposerFile and LockFile.

var factoryEnvVars = []string{"COMPOSER_HOME", "COMPOSER_CACHE_DIR", "HOME", "XDG_CONFIG_HOME", "XDG_CACHE_HOME", "XDG_DATA_HOME", "XDG_RUNTIME_DIR", "APPDATA", "LOCALAPPDATA", "COMPOSER", "COMPOSER_AUTH", "COMPOSER_HTACCESS_PROTECT"}

// verbosityIO records WriteError calls as "verbosity|message".
type verbosityIO struct {
	*io.NullIO
	errors []string
}

func (v *verbosityIO) WriteError(message string, _ bool, verbosity io.Verbosity) {
	v.errors = append(v.errors, strconv.Itoa(int(verbosity))+"|"+message)
}

type factoryCase struct {
	Kind       string             `json:"kind"`
	Env        stdjson.RawMessage `json:"env"`
	Dirs       []string           `json:"dirs"`
	Home       oracleResult       `json:"home"`
	HomeArg    string             `json:"homeArg"`
	Cache      oracleResult       `json:"cache"`
	Data       oracleResult       `json:"data"`
	ConfigJSON *string            `json:"configJson"`
	AuthJSON   *string            `json:"authJson"`
	MkHome     bool               `json:"mkHome"`
	IO         bool               `json:"io"`
	Cwd        *string            `json:"cwd"`
	R          oracleResult       `json:"r"`
	Warnings   []string           `json:"warnings"`
	Files      []string           `json:"files"`
	File       string             `json:"file"`
}

func TestFactoryOracle(t *testing.T) {
	if runtime.GOOS != "linux" {
		t.Skip("the goldens were generated on Linux")
	}
	raw, err := os.ReadFile("testdata/oracle/factory.json")
	if err != nil {
		t.Fatal(err)
	}
	var golden struct {
		EtcXdg bool          `json:"etcXdg"`
		Cases  []factoryCase `json:"cases"`
	}
	if err := stdjson.Unmarshal(raw, &golden); err != nil {
		t.Fatal(err)
	}

	for _, kv := range os.Environ() {
		if name, _, _ := strings.Cut(kv, "="); strings.HasPrefix(name, "XDG_") {
			unsetenv(t, name)
		}
	}
	sameEtcXdg := php.IsDir("/etc/xdg") == golden.EtcXdg

	for i, c := range golden.Cases {
		base := filepath.Join(t.TempDir(), "b")
		if err := os.MkdirAll(base, 0o777); err != nil {
			t.Fatal(err)
		}
		where := "case " + strconv.Itoa(i) + " " + c.Kind
		// The goldens were recorded where PHP_EOL is "\n".
		rel := func(s string) string { return php.NormalizeEOL(strings.ReplaceAll(s, base, "<BASE>")) }
		abs := func(s string) string { return strings.ReplaceAll(s, "<BASE>", base) }
		check := func(what string, got string, err error, want oracleResult) {
			t.Helper()
			if err != nil {
				err = &relError{err, rel(err.Error())}
			}
			if want.V != nil && err == nil {
				if rel(got) != *want.V {
					t.Errorf("%s %s: got %q, want %q", where, what, rel(got), *want.V)
				}

				return
			}
			checkResult(t, where+" "+what, rel(got), err, want)
		}

		for _, name := range factoryEnvVars {
			unsetenv(t, name)
		}
		env := map[string]string{}
		if len(c.Env) > 0 && string(c.Env) != "null" && c.Env[0] == '{' {
			if err := stdjson.Unmarshal(c.Env, &env); err != nil {
				t.Fatal(err)
			}
		}
		hasXdg := false
		for name, value := range env {
			t.Setenv(name, abs(value))
			hasXdg = hasXdg || strings.HasPrefix(name, "XDG_")
		}

		switch c.Kind {
		case "dirs":
			if !sameEtcXdg && !hasXdg {
				continue
			}
			for _, dir := range c.Dirs {
				if err := os.MkdirAll(filepath.Join(base, dir), 0o777); err != nil {
					t.Fatal(err)
				}
			}
			home, err := HomeDir()
			check("home", home, err, c.Home)
			cache, err := CacheDir(abs(c.HomeArg))
			check("cache", cache, err, c.Cache)
			data, err := DataDir(abs(c.HomeArg))
			check("data", data, err, c.Data)

		case "create":
			if err := os.MkdirAll(filepath.Join(base, "project"), 0o777); err != nil {
				t.Fatal(err)
			}
			if c.ConfigJSON != nil || c.AuthJSON != nil || c.MkHome {
				if err := os.MkdirAll(filepath.Join(base, "chome"), 0o777); err != nil {
					t.Fatal(err)
				}
			}
			for name, contents := range map[string]*string{"config.json": c.ConfigJSON, "auth.json": c.AuthJSON} {
				if contents != nil {
					if err := os.WriteFile(filepath.Join(base, "chome", name), []byte(*contents), 0o666); err != nil {
						t.Fatal(err)
					}
				}
			}
			cwd := ""
			if c.Cwd != nil {
				cwd = abs(*c.Cwd)
			}
			load := func(name string, create func(io.IO, string) (*Config, error)) {
				t.Helper()
				rec := &verbosityIO{NullIO: io.NewNullIO()}
				var out io.IO
				if c.IO {
					out = rec
				}
				config, err := create(out, cwd)
				got := ""
				if err == nil {
					got = php.VarExport(php.ListOf(config.Raw(), config.ConfigSource().Name(), config.AuthConfigSource().Name()))
				}
				check(name, got, err, c.R)
				warnings := make([]string, len(rec.errors))
				for j, w := range rec.errors {
					warnings[j] = rel(w)
				}
				if strings.Join(warnings, "\n") != strings.Join(c.Warnings, "\n") {
					t.Errorf("%s %s: warnings\n%q\nwant\n%q", where, name, warnings, c.Warnings)
				}
			}
			// ReadConfig reads what CreateConfig reads and touches nothing.
			before := treeOf(t, base)
			load("readConfig", ReadConfig)
			if after := treeOf(t, base); strings.Join(after, "\n") != strings.Join(before, "\n") {
				t.Errorf("%s: readConfig changed the file system: %q, was %q", where, after, before)
			}
			load("createConfig", CreateConfig)
			var files []string
			for _, f := range []string{"chome/.htaccess", "ccache/.htaccess", "chome/cache/.htaccess"} {
				if data, err := os.ReadFile(filepath.Join(base, f)); err == nil {
					files = append(files, f+":"+string(data))
				}
			}
			if strings.Join(files, "\n") != strings.Join(c.Files, "\n") {
				t.Errorf("%s: files %q, want %q", where, files, c.Files)
			}

		case "composerFile":
			var value *string
			_ = stdjson.Unmarshal(c.Env, &value)
			if value != nil {
				t.Setenv("COMPOSER", abs(*value))
			}
			file, err := ComposerFile()
			check("composerFile", file, err, c.R)

		case "lockFile":
			if got := LockFile(c.File); got != *c.R.V {
				t.Errorf("%s: LockFile(%q) = %q, want %q", where, c.File, got, *c.R.V)
			}
		}
	}
}

// treeOf lists every path under root, relative to it.
func treeOf(t *testing.T, root string) []string {
	t.Helper()
	var paths []string
	err := filepath.WalkDir(root, func(path string, _ os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		paths = append(paths, rel)

		return err
	})
	if err != nil {
		t.Fatal(err)
	}

	return paths
}

// relError keeps an error's type but reports a message with the scratch
// directory replaced.
type relError struct {
	err error
	msg string
}

func (e *relError) Error() string { return e.msg }

func (e *relError) Unwrap() error { return e.err }
