package config

import (
	stdjson "encoding/json"
	"regexp"
	"testing"

	"github.com/stubbedev/maestro/internal/php"
	"github.com/stubbedev/maestro/internal/phperr"
	"github.com/stubbedev/maestro/internal/testutil"
)

// Replays testdata/oracle/config.json.gz, generated by
// tools/oracle/config/config.php from Composer's own Config.

// oracleResult is a recorded outcome: a var_export()ed value, or an
// exception class and message.
type oracleResult struct {
	V *string    `json:"v"`
	E *[2]string `json:"e"`
}

// errorClass names the PHP exception class an error stands for.
func errorClass(err error) string {
	if phperr.Of(err) == nil {
		return "?"
	}

	return phperr.Class(err)
}

// checkResult compares a Go outcome with a recorded one.
// calledIn is the suffix the oracle generators drop from TypeErrors
// (preg_replace('{, called in .* on line \d+$}', ”, ...)).
var calledIn = regexp.MustCompile(`, called in .* on line \d+$`)

func checkResult(t *testing.T, where string, got any, err error, want oracleResult) {
	t.Helper()
	if want.E != nil {
		if err == nil {
			t.Errorf("%s: got %s, want %s: %s", where, php.VarExport(got), want.E[0], want.E[1])

			return
		}
		// the generator drops the "called in <path>" of userland
		// TypeErrors, whose path is the machine's
		message := calledIn.ReplaceAllString(err.Error(), "")
		if class := errorClass(err); class != want.E[0] || message != want.E[1] {
			t.Errorf("%s: got %s: %s, want %s: %s", where, class, message, want.E[0], want.E[1])
		}

		return
	}
	if err != nil {
		t.Errorf("%s: got error %s: %v, want %s", where, errorClass(err), err, *want.V)

		return
	}
	if s := php.VarExport(got); s != *want.V {
		t.Errorf("%s: got %s, want %s", where, s, *want.V)
	}
}

// oracleEnvVars are the variables the generator sets or clears per case.
var oracleEnvVars = []string{
	"COMPOSER_VENDOR_DIR", "COMPOSER_BIN_DIR", "COMPOSER_PROCESS_TIMEOUT", "COMPOSER_DATA_DIR", "COMPOSER_CACHE_DIR",
	"COMPOSER_CACHE_FILES_DIR", "COMPOSER_CACHE_REPO_DIR", "COMPOSER_CACHE_VCS_DIR", "COMPOSER_CAFILE", "COMPOSER_CAPATH",
	"COMPOSER_CACHE_READ_ONLY", "COMPOSER_HTACCESS_PROTECT", "COMPOSER_BIN_COMPAT", "COMPOSER_DISCARD_CHANGES",
	"COMPOSER_AUDIT_ABANDONED", "COMPOSER_SECURITY_BLOCKING_ABANDONED", "COMPOSER_POLICY", "ORACLE_VAR",
}

// setOracleEnv clears oracleEnvVars and sets env (restored after the test).
func setOracleEnv(t *testing.T, env map[string]string) {
	t.Helper()
	for _, name := range oracleEnvVars {
		unsetenv(t, name)
	}
	for name, value := range env {
		t.Setenv(name, value)
	}
}

func decodeMergeData(t *testing.T, data string) *php.Array {
	t.Helper()
	v, err := php.JSONDecode(data, true)
	if err != nil {
		t.Fatalf("merge data %s: %v", data, err)
	}
	a, ok := v.(*php.Array)
	if !ok {
		t.Fatalf("merge data %s is not an array", data)
	}

	return a
}

func TestConfigOracle(t *testing.T) {
	raw, err := testutil.ReadGoldenFile("testdata/oracle/config.json.gz")
	if err != nil {
		t.Fatal(err)
	}
	var golden struct {
		Cases []struct {
			Env     map[string]string `json:"env"`
			UseEnv  bool              `json:"useEnv"`
			BaseDir *string           `json:"baseDir"`
			Ops     []struct {
				Op     string       `json:"op"`
				Data   string       `json:"data"`
				Source string       `json:"source"`
				Key    string       `json:"key"`
				Flags  int          `json:"flags"`
				R      oracleResult `json:"r"`
			} `json:"ops"`
		} `json:"cases"`
	}
	if err := stdjson.Unmarshal(raw, &golden); err != nil {
		t.Fatal(err)
	}

	t.Setenv("HOME", "/home/oracle")
	for i, c := range golden.Cases {
		setOracleEnv(t, c.Env)
		baseDir := ""
		if c.BaseDir != nil {
			baseDir = *c.BaseDir
		}
		config := New(c.UseEnv, baseDir)
		failed := false
		for j, op := range c.Ops {
			where := func() string { return "case " + itoa(i) + " op " + itoa(j) + " " + op.Op + " " + op.Key + op.Data }
			var got any
			var err error
			switch op.Op {
			case "merge":
				err = config.Merge(decodeMergeData(t, op.Data), op.Source)
			case "get":
				got, err = config.Get(op.Key, op.Flags)
			case "source":
				got, err = config.SourceOfValue(op.Key)
			case "has":
				got = config.Has(op.Key)
			case "repos":
				got = config.Repositories()
			case "raw":
				got = config.Raw()
			case "all":
				got, err = config.All(op.Flags)
			default:
				t.Fatalf("unknown op %s", op.Op)
			}
			before := t.Failed()
			checkResult(t, where(), got, err, op.R)
			if !before && t.Failed() {
				failed = true
			}
		}
		if failed && testing.Short() {
			return
		}
	}
}

func itoa(i int) string { return php.ToString(int64(i)) }
