package config

import (
	stdjson "encoding/json"
	"errors"
	"os"
	"slices"
	"testing"

	"github.com/stubbedev/maestro/internal/io"
	"github.com/stubbedev/maestro/internal/php"
	"github.com/stubbedev/maestro/internal/util"
)

// Replays testdata/oracle/url.json, generated by tools/oracle/config/url.php:
// filter_var(FILTER_VALIDATE_URL) and Config::prohibitUrlByConfig.
func TestURLOracle(t *testing.T) {
	raw, err := os.ReadFile("testdata/oracle/url.json")
	if err != nil {
		t.Fatal(err)
	}
	var cases []struct {
		URL      string             `json:"url"`
		Valid    bool               `json:"valid"`
		Merge    stdjson.RawMessage `json:"merge"`
		Options  stdjson.RawMessage `json:"options"`
		IO       bool               `json:"io"`
		Warnings []string           `json:"warnings"`
		Runs     []struct {
			OK bool                 `json:"ok"`
			E  []stdjson.RawMessage `json:"e"`
		} `json:"runs"`
	}
	if err := stdjson.Unmarshal(raw, &cases); err != nil {
		t.Fatal(err)
	}

	for _, c := range cases {
		if got := filterValidateURL(c.URL); got != c.Valid {
			t.Errorf("filter_var(%q, FILTER_VALIDATE_URL): got %v, want %v", c.URL, got, c.Valid)
		}

		config := New(false, "")
		check(t, config.Merge(php.ArrayOf("config", arr(t, string(c.Merge))), SourceUnknown))
		options := arr(t, string(c.Options))
		rec := &recordingIO{NullIO: io.NewNullIO()}
		var out io.IO
		if c.IO {
			out = rec
		}
		for i, run := range c.Runs {
			err := config.ProhibitURLByConfig(c.URL, out, options)
			if run.OK {
				if err != nil {
					t.Errorf("%q run %d: unexpected %v", c.URL, i, err)
				}

				continue
			}
			var class, message string
			var code int
			_ = stdjson.Unmarshal(run.E[0], &class)
			_ = stdjson.Unmarshal(run.E[1], &message)
			_ = stdjson.Unmarshal(run.E[2], &code)
			var te *util.TransportError
			if !errors.As(err, &te) || class != "Composer\\Downloader\\TransportException" || te.Message != message || te.Code != code {
				t.Errorf("%q run %d: got %v, want %s(%d): %s", c.URL, i, err, class, code, message)
			}
		}
		if !slices.Equal(rec.errors, c.Warnings) && (len(rec.errors) != 0 || len(c.Warnings) != 0) {
			t.Errorf("%q: warnings %q, want %q", c.URL, rec.errors, c.Warnings)
		}
	}
}
