<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Console\Input;

class InputArgument extends \Symfony\Component\Console\Input\InputArgument
{
    public function __construct(string $name, ?int $mode = null, string $description = '', $default = null, $suggestedValues = [])
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Console\\Input\\InputArgument::__construct() in plugins yet');
    }

    public function complete(\Symfony\Component\Console\Completion\CompletionInput $input, \Symfony\Component\Console\Completion\CompletionSuggestions $suggestions): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Console\\Input\\InputArgument::complete() in plugins yet');
    }
}
