<?php
// Generates internal/console/wcwidth_tables.go from symfony/string's
// wcswidth tables (the version Composer 2.10.3 ships).
// Run: php tools/oracle/console/gen_wcwidth.php
$root = dirname(__DIR__, 3);
$dir = $root.'/.ref/composer/vendor/symfony/string/Resources/data/';
$zero = require $dir.'wcswidth_table_zero.php';
$wide = require $dir.'wcswidth_table_wide.php';
$out = "// Code generated by tools/oracle/console/gen_wcwidth.php from symfony/string\n// v5.4.47 Resources/data/wcswidth_table_*.php. DO NOT EDIT.\n\npackage console\n\n";
foreach (['wcwidthZero' => $zero, 'wcwidthWide' => $wide] as $name => $table) {
    $out .= "var $name = [...][2]rune{\n";
    foreach ($table as [$a, $b]) {
        $out .= sprintf("\t{0x%04X, 0x%04X},\n", $a, $b);
    }
    $out .= "}\n\n";
}
file_put_contents($root.'/internal/console/wcwidth_tables.go', rtrim($out)."\n");
