<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Plugin;

interface PluginInterface
{
    public const PLUGIN_API_VERSION = '2.9.0';

    public function activate(\Composer\Composer $composer, \Composer\IO\IOInterface $io);

    public function deactivate(\Composer\Composer $composer, \Composer\IO\IOInterface $io);

    public function uninstall(\Composer\Composer $composer, \Composer\IO\IOInterface $io);
}
