<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Plugin;

class PluginManager
{
    protected $composer;
    protected $disablePlugins = false;
    protected $globalComposer;
    protected $io;
    protected $plugins = [];
    protected $registeredPlugins = [];
    protected $versionParser;

    public function __construct(\Composer\IO\IOInterface $io, \Composer\Composer $composer, ?\Composer\PartialComposer $globalComposer = null, $disablePlugins = false)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::__construct() in plugins yet');
    }

    public function addPlugin(\Composer\Plugin\PluginInterface $plugin, bool $isGlobalPlugin = false, ?\Composer\Package\PackageInterface $sourcePackage = null): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::addPlugin() in plugins yet');
    }

    public function arePluginsDisabled($type)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::arePluginsDisabled() in plugins yet');
    }

    public function deactivateInstalledPlugins(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::deactivateInstalledPlugins() in plugins yet');
    }

    public function deactivatePackage(\Composer\Package\PackageInterface $package): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::deactivatePackage() in plugins yet');
    }

    public function disablePlugins(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::disablePlugins() in plugins yet');
    }

    protected function getCapabilityImplementationClassName(\Composer\Plugin\PluginInterface $plugin, string $capability): ?string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::getCapabilityImplementationClassName() in plugins yet');
    }

    public function getGlobalComposer(): ?\Composer\PartialComposer
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::getGlobalComposer() in plugins yet');
    }

    protected function getPluginApiVersion(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::getPluginApiVersion() in plugins yet');
    }

    public function getPluginCapabilities($capabilityClassName, array $ctorArgs = []): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::getPluginCapabilities() in plugins yet');
    }

    public function getPluginCapability(\Composer\Plugin\PluginInterface $plugin, $capabilityClassName, array $ctorArgs = []): ?\Composer\Plugin\Capability\Capability
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::getPluginCapability() in plugins yet');
    }

    public function getPlugins(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::getPlugins() in plugins yet');
    }

    public function getRegisteredPlugins(): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::getRegisteredPlugins() in plugins yet');
    }

    public function isPluginAllowed(string $package, bool $isGlobalPlugin, bool $optional = false, bool $prompt = true): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::isPluginAllowed() in plugins yet');
    }

    public function loadInstalledPlugins(): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::loadInstalledPlugins() in plugins yet');
    }

    public function registerPackage(\Composer\Package\PackageInterface $package, bool $failOnMissingClasses = false, bool $isGlobalPlugin = false): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::registerPackage() in plugins yet');
    }

    public function removePlugin(\Composer\Plugin\PluginInterface $plugin): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::removePlugin() in plugins yet');
    }

    public function setRunningInGlobalDir(bool $runningInGlobalDir): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::setRunningInGlobalDir() in plugins yet');
    }

    public function uninstallPackage(\Composer\Package\PackageInterface $package): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::uninstallPackage() in plugins yet');
    }

    public function uninstallPlugin(\Composer\Plugin\PluginInterface $plugin): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PluginManager::uninstallPlugin() in plugins yet');
    }
}
