<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Plugin;

class PreCommandRunEvent extends \Composer\EventDispatcher\Event
{
    public function __construct(string $name, \Symfony\Component\Console\Input\InputInterface $input, string $command)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PreCommandRunEvent::__construct() in plugins yet');
    }

    public function getCommand(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PreCommandRunEvent::getCommand() in plugins yet');
    }

    public function getInput(): \Symfony\Component\Console\Input\InputInterface
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Plugin\\PreCommandRunEvent::getInput() in plugins yet');
    }
}
