package json

import (
	"bytes"
	"encoding/base64"
	stdjson "encoding/json"
	"strconv"
	"testing"

	"github.com/stubbedev/maestro/internal/php"
	"github.com/stubbedev/maestro/internal/phperr"
	"github.com/stubbedev/maestro/internal/testutil"
)

// Replays testdata/oracle/jsonfile.json.gz, generated by
// tools/oracle/json/jsonfile.php: JsonFile::encode, JsonFormatter::format,
// JsonFile::parseJson and JsonFile::detectIndenting.

type jfOutcome struct {
	V *string    `json:"v"`
	E *[2]string `json:"e"`
}

func jfB64(t *testing.T, s string) string {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}

	return string(b)
}

// jfDecodeValue decodes the tagged values of the generator.
func jfDecodeValue(t *testing.T, raw stdjson.RawMessage) any {
	t.Helper()
	var tagged map[string]stdjson.RawMessage
	if len(raw) == 0 || raw[0] != '{' {
		var v any
		dec := stdjson.NewDecoder(bytes.NewReader(raw))
		dec.UseNumber()
		if err := dec.Decode(&v); err != nil {
			t.Fatal(err)
		}
		if n, ok := v.(stdjson.Number); ok {
			i, err := strconv.ParseInt(n.String(), 10, 64)
			if err != nil {
				t.Fatal(err)
			}

			return i
		}

		return v
	}
	if err := stdjson.Unmarshal(raw, &tagged); err != nil {
		t.Fatal(err)
	}
	for tag, body := range tagged {
		switch tag {
		case "s":
			var s string
			_ = stdjson.Unmarshal(body, &s)

			return jfB64(t, s)
		case "f":
			var s string
			_ = stdjson.Unmarshal(body, &s)
			f, err := strconv.ParseFloat(s, 64)
			if err != nil {
				t.Fatalf("float %s: %v", s, err)
			}

			return f
		case "a", "o":
			var pairs [][2]stdjson.RawMessage
			if err := stdjson.Unmarshal(body, &pairs); err != nil {
				t.Fatal(err)
			}
			if tag == "o" {
				o := php.NewObject()
				for _, p := range pairs {
					var k string
					_ = stdjson.Unmarshal(p[0], &k)
					o.Set(k, jfDecodeValue(t, p[1]))
				}

				return o
			}
			a := php.NewArray()
			for _, p := range pairs {
				a.Set(jfDecodeValue(t, p[0]), jfDecodeValue(t, p[1]))
			}

			return a
		}
	}
	t.Fatalf("bad value %s", raw)

	return nil
}

func jfErrorClass(err error) string {
	if phperr.Of(err) == nil {
		return "?"
	}

	return phperr.Class(err)
}

func jfCheck(t *testing.T, where string, got string, err error, want jfOutcome) {
	t.Helper()
	if want.E != nil {
		msg := jfB64(t, want.E[1])
		if err == nil || jfErrorClass(err) != want.E[0] || err.Error() != msg {
			t.Errorf("%s: got %q, %v, want %s: %q", where, got, err, want.E[0], msg)
		}

		return
	}
	if v := jfB64(t, *want.V); err != nil || got != v {
		t.Errorf("%s: got %q, %v, want %q", where, got, err, v)
	}
}

func TestJsonFileOracle(t *testing.T) {
	raw, err := testutil.ReadGoldenFile("testdata/oracle/jsonfile.json.gz")
	if err != nil {
		t.Fatal(err)
	}
	var golden struct {
		Encode []struct {
			In     stdjson.RawMessage `json:"in"`
			Flags  php.JSONFlag       `json:"flags"`
			Indent string             `json:"indent"`
			R      jfOutcome          `json:"r"`
		} `json:"encode"`
		Format []struct {
			JSON string    `json:"json"`
			U    bool      `json:"u"`
			S    bool      `json:"s"`
			R    jfOutcome `json:"r"`
		} `json:"format"`
		Parse []struct {
			Text   string    `json:"text"`
			File   *string   `json:"file"`
			R      jfOutcome `json:"r"`
			Indent string    `json:"indent"`
		} `json:"parse"`
	}
	if err := stdjson.Unmarshal(raw, &golden); err != nil {
		t.Fatal(err)
	}

	for i, c := range golden.Encode {
		got, err := Encode(jfDecodeValue(t, c.In), c.Flags, c.Indent)
		jfCheck(t, "encode "+strconv.Itoa(i), got, err, c.R)
	}
	for i, c := range golden.Format {
		got, err := Format(jfB64(t, c.JSON), c.U, c.S)
		jfCheck(t, "format "+strconv.Itoa(i), got, err, c.R)
	}
	for i, c := range golden.Parse {
		text := jfB64(t, c.Text)
		file := ""
		if c.File != nil {
			file = *c.File
		}
		v, err := ParseJSON(text, file)
		jfCheck(t, "parse "+strconv.Itoa(i)+" "+strconv.Quote(text), php.VarExport(v), err, c.R)
		if got, want := DetectIndenting(text), jfB64(t, c.Indent); got != want {
			t.Errorf("detectIndenting(%q) = %q, want %q", text, got, want)
		}
	}
}
