package json

import (
	stdjson "encoding/json"
	"errors"
	"slices"
	"testing"

	"github.com/stubbedev/maestro/internal/php"
	"github.com/stubbedev/maestro/internal/testutil"
)

// TestSchemaOracle_ValidateJSONSchema compares ValidateJSONSchema with
// JsonFile::validateJsonSchema('file.json', json_decode($doc, true), $mode)
// over the corpus of internal/json/jsonschema/testdata/oracle/schema.json.gz
// (generated by tools/oracle/json/schema.php).
func TestSchemaOracle_ValidateJSONSchema(t *testing.T) {
	data, err := testutil.ReadGoldenFile("jsonschema/testdata/oracle/schema.json.gz")
	if err != nil {
		t.Fatal(err)
	}
	var cases []struct {
		Schema string             `json:"schema"`
		Doc    string             `json:"doc"`
		Result stdjson.RawMessage `json:"jsonfile"`
	}
	if err := stdjson.Unmarshal(data, &cases); err != nil {
		t.Fatal(err)
	}
	modes := map[string]int{"composer": LaxSchema, "strict": StrictSchema, "auth": AuthSchema, "lock": LockSchema}

	failures, checked := 0, 0
	for _, c := range cases {
		mode, ok := modes[c.Schema]
		if !ok {
			continue
		}
		checked++
		var want struct {
			Message *string  `json:"message"`
			Errors  []string `json:"errors"`
			E       *string  `json:"e"`
		}
		valid := string(c.Result) == "true"
		if !valid {
			if err := stdjson.Unmarshal(c.Result, &want); err != nil {
				t.Fatal(err)
			}
		}

		decoded, _ := php.JSONDecode(c.Doc, true)
		err := ValidateJSONSchema("file.json", decoded, mode, "")

		var verr *ValidationError
		switch {
		case valid:
			ok = err == nil
		case want.E != nil:
			ok = err != nil && err.Error() == *want.E
		default:
			ok = errors.As(err, &verr) && verr.Message == *want.Message && slices.Equal(verr.Errors, want.Errors)
		}
		if !ok {
			failures++
			if failures <= 20 {
				t.Errorf("mode %d %s:\n got %v %v\nwant %s", mode, c.Doc, err, verr, c.Result)
			}
		}
	}
	if failures > 0 {
		t.Errorf("%d of %d cases differ", failures, checked)
	}
}
