<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Config;

interface ConfigSourceInterface
{
    public function addConfigSetting(string $name, $value): void;

    public function addLink(string $type, string $name, string $value): void;

    public function addProperty(string $name, $value): void;

    public function addRepository(string $name, $config, bool $append = true): void;

    public function getName(): string;

    public function insertRepository(string $name, $config, string $referenceName, int $offset = 0): void;

    public function removeConfigSetting(string $name): void;

    public function removeLink(string $type, string $name): void;

    public function removeProperty(string $name): void;

    public function removeRepository(string $name): void;

    public function setRepositoryUrl(string $name, string $url): void;
}
