<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Config;

class JsonConfigSource implements \Composer\Config\ConfigSourceInterface
{
    public function __construct(\Composer\Json\JsonFile $file, bool $authConfig = false)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Config\\JsonConfigSource::__construct() in plugins yet');
    }

    public function addConfigSetting(string $name, $value): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Config\\JsonConfigSource::addConfigSetting() in plugins yet');
    }

    public function addLink(string $type, string $name, string $value): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Config\\JsonConfigSource::addLink() in plugins yet');
    }

    public function addProperty(string $name, $value): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Config\\JsonConfigSource::addProperty() in plugins yet');
    }

    public function addRepository(string $name, $config, bool $append = true): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Config\\JsonConfigSource::addRepository() in plugins yet');
    }

    public function getName(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Config\\JsonConfigSource::getName() in plugins yet');
    }

    public function insertRepository(string $name, $config, string $referenceName, int $offset = 0): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Config\\JsonConfigSource::insertRepository() in plugins yet');
    }

    public function removeConfigSetting(string $name): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Config\\JsonConfigSource::removeConfigSetting() in plugins yet');
    }

    public function removeLink(string $type, string $name): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Config\\JsonConfigSource::removeLink() in plugins yet');
    }

    public function removeProperty(string $name): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Config\\JsonConfigSource::removeProperty() in plugins yet');
    }

    public function removeRepository(string $name): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Config\\JsonConfigSource::removeRepository() in plugins yet');
    }

    public function setRepositoryUrl(string $name, string $url): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Config\\JsonConfigSource::setRepositoryUrl() in plugins yet');
    }
}
