<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Archiver;

class ArchivableFilesFinder extends \FilterIterator
{
    protected $finder;

    public function __construct(string $sources, array $excludes, bool $ignoreFilters = false)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\ArchivableFilesFinder::__construct() in plugins yet');
    }

    public function accept(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\ArchivableFilesFinder::accept() in plugins yet');
    }
}
