<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Archiver;

class ArchiveManager
{
    protected $archivers = [];
    protected $downloadManager;
    protected $loop;
    protected $overwriteFiles = true;

    public function __construct(\Composer\Downloader\DownloadManager $downloadManager, \Composer\Util\Loop $loop)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\ArchiveManager::__construct() in plugins yet');
    }

    public function addArchiver(\Composer\Package\Archiver\ArchiverInterface $archiver): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\ArchiveManager::addArchiver() in plugins yet');
    }

    public function archive(\Composer\Package\CompletePackageInterface $package, string $format, string $targetDir, ?string $fileName = null, bool $ignoreFilters = false): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\ArchiveManager::archive() in plugins yet');
    }

    public function getPackageFilename(\Composer\Package\CompletePackageInterface $package): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\ArchiveManager::getPackageFilename() in plugins yet');
    }

    public function getPackageFilenameFromParts(array $parts): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\ArchiveManager::getPackageFilenameFromParts() in plugins yet');
    }

    public function getPackageFilenameParts(\Composer\Package\CompletePackageInterface $package): array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\ArchiveManager::getPackageFilenameParts() in plugins yet');
    }

    public function setOverwriteFiles(bool $overwriteFiles): self
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\ArchiveManager::setOverwriteFiles() in plugins yet');
    }
}
