<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Archiver;

class ArchivableFilesFilter extends \FilterIterator
{
    public function accept(): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\ArchivableFilesFilter::accept() in plugins yet');
    }

    public function addEmptyDir(\PharData $phar, string $sources): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\ArchivableFilesFilter::addEmptyDir() in plugins yet');
    }
}
