<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Archiver;

class ComposerExcludeFilter extends \Composer\Package\Archiver\BaseExcludeFilter
{
    public function __construct(string $sourcePath, array $excludeRules)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\ComposerExcludeFilter::__construct() in plugins yet');
    }
}
