<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Archiver;

class GitExcludeFilter extends \Composer\Package\Archiver\BaseExcludeFilter
{
    public function __construct(string $sourcePath)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\GitExcludeFilter::__construct() in plugins yet');
    }

    public function parseGitAttributesLine(string $line): ?array
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\GitExcludeFilter::parseGitAttributesLine() in plugins yet');
    }
}
