<?php

// @generated by tools/shimgen from Composer's API (internal/upstream's release); do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Package\Archiver;

class PharArchiver implements \Composer\Package\Archiver\ArchiverInterface
{
    protected static $compressFormats = ['tar.gz' => 4096, 'tar.bz2' => 8192];
    protected static $formats = ['zip' => 3, 'tar' => 2, 'tar.gz' => 2, 'tar.bz2' => 2];

    public function archive(string $sources, string $target, string $format, array $excludes = [], bool $ignoreFilters = false): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\PharArchiver::archive() in plugins yet');
    }

    public function supports(string $format, ?string $sourceType): bool
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Package\\Archiver\\PharArchiver::supports() in plugins yet');
    }
}
