<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\Question;

class StrictConfirmationQuestion extends \Symfony\Component\Console\Question\Question
{
    public function __construct(string $question, bool $default = true, string $trueAnswerRegex = '/^y(?:es)?$/i', string $falseAnswerRegex = '/^no?$/i')
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\Question\\StrictConfirmationQuestion::__construct() in plugins yet');
    }
}
