<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\IO;

abstract class BaseIO implements \Composer\IO\IOInterface
{
    protected $authentications = [];

    public function alert($message, array $context = []): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::alert() in plugins yet');
    }

    protected function checkAndSetAuthentication(string $repositoryName, string $username, ?string $password = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::checkAndSetAuthentication() in plugins yet');
    }

    public function critical($message, array $context = []): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::critical() in plugins yet');
    }

    public function debug($message, array $context = []): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::debug() in plugins yet');
    }

    public function emergency($message, array $context = []): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::emergency() in plugins yet');
    }

    public function error($message, array $context = []): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::error() in plugins yet');
    }

    public function getAuthentication($repositoryName)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::getAuthentication() in plugins yet');
    }

    public function getAuthentications()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::getAuthentications() in plugins yet');
    }

    public function hasAuthentication($repositoryName)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::hasAuthentication() in plugins yet');
    }

    public function info($message, array $context = []): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::info() in plugins yet');
    }

    public function loadConfiguration(\Composer\Config $config)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::loadConfiguration() in plugins yet');
    }

    public function log($level, $message, array $context = []): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::log() in plugins yet');
    }

    public function notice($message, array $context = []): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::notice() in plugins yet');
    }

    public function resetAuthentications()
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::resetAuthentications() in plugins yet');
    }

    public function setAuthentication($repositoryName, $username, $password = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::setAuthentication() in plugins yet');
    }

    public function warning($message, array $context = []): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::warning() in plugins yet');
    }

    public function writeErrorRaw($messages, bool $newline = true, int $verbosity = self::NORMAL)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::writeErrorRaw() in plugins yet');
    }

    public function writeRaw($messages, bool $newline = true, int $verbosity = self::NORMAL)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BaseIO::writeRaw() in plugins yet');
    }
}
