<?php

// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.
// A presence-parity stub (docs/PLUGINS.md D7): every method throws
// Maestro\Shim\UnsupportedApiException until the shim implements it.

namespace Composer\IO;

class BufferIO extends \Composer\IO\ConsoleIO
{
    public function __construct(string $input = '', int $verbosity = \Symfony\Component\Console\Output\StreamOutput::VERBOSITY_NORMAL, ?\Symfony\Component\Console\Formatter\OutputFormatterInterface $formatter = null)
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BufferIO::__construct() in plugins yet');
    }

    public function getOutput(): string
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BufferIO::getOutput() in plugins yet');
    }

    public function setUserInputs(array $inputs): void
    {
        throw new \Maestro\Shim\UnsupportedApiException('maestro does not support Composer\\IO\\BufferIO::setUserInputs() in plugins yet');
    }
}
