// Command shimgen generates the plugin shim's presence-parity stubs
// (docs/PLUGINS.md D7, §5.1, §9.2): it reflects every class of Composer
// 2.10.3's src/ with reflect.php, writes the reflection as the parity
// golden internal/plugin/testdata/apiparity.json.gz, and writes a stub
// with Composer's exact signatures into internal/plugin/php/stubs/ for
// every class the shim does not implement by hand (internal/plugin/php/src)
// or embed verbatim (ClassLoader, InstalledVersions). It then rebuilds the
// shim's autoload index and manifest.
//
// Usage, from the repository root in the dev shell:
//
//	go run ./tools/shimgen          # stubs, golden, index, manifest
//	go run ./tools/shimgen -index   # index and manifest only (go generate)
package main

import (
	"bytes"
	"compress/gzip"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"

	"github.com/stubbedev/maestro/internal/classmap"
	"github.com/stubbedev/maestro/internal/php"
	"github.com/stubbedev/maestro/internal/plugin/shimbuild"
)

func main() {
	ref := flag.String("ref", ".ref/composer", "the Composer 2.10.3 checkout, with vendor/ installed")
	shim := flag.String("shim", "internal/plugin/php", "the shim source tree")
	golden := flag.String("golden", "internal/plugin/testdata/apiparity.json.gz", "the parity golden to write")
	indexOnly := flag.Bool("index", false, "only rebuild the autoload index and the manifest")
	flag.Parse()

	var err error
	if *indexOnly {
		err = shimbuild.WriteIndex(*shim)
	} else {
		err = run(*ref, *shim, *golden)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "shimgen:", err)
		os.Exit(1)
	}
}

func run(ref, shim, golden string) error {
	reflectPHP, err := filepath.Abs("tools/shimgen/reflect.php")
	if err != nil {
		return err
	}

	cmd := exec.Command("php", reflectPHP, "ref", ref) //nolint:gosec // a developer tool run on the given checkout.
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return fmt.Errorf("reflect.php: %w", err)
	}

	api, err := shimbuild.ParseAPI(out)
	if err != nil {
		return err
	}

	if err := writeGolden(golden, out); err != nil {
		return err
	}

	handWritten := map[string]bool{}
	for class := range shimbuild.VirtualClasses {
		handWritten[class] = true
	}
	if _, err := os.Stat(filepath.Join(shim, shimbuild.SrcDir)); err == nil {
		m, err := classmap.CreateMap(filepath.Join(shim, shimbuild.SrcDir))
		if err != nil {
			return err
		}
		for class := range m.Map() {
			handWritten[class] = true
		}
	}

	stubs := filepath.Join(shim, shimbuild.StubsDir)
	if err := os.RemoveAll(stubs); err != nil {
		return err
	}

	n := 0
	for _, name := range api.Names() {
		if handWritten[name] {
			continue
		}
		file := filepath.Join(stubs, filepath.FromSlash(strings.ReplaceAll(name, `\`, "/"))+".php")
		if err := os.MkdirAll(filepath.Dir(file), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(file, []byte(renderStub(name, api.Classes[name])), 0o644); err != nil {
			return err
		}
		n++
	}
	fmt.Printf("%d classes reflected, %d stubs written\n", len(api.Classes), n)

	return shimbuild.WriteIndex(shim)
}

// writeGolden writes the reflection gzipped, deterministically (no name
// or timestamp in the header).
func writeGolden(file string, data []byte) error {
	var buf bytes.Buffer
	zw, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if err != nil {
		return err
	}
	if _, err := zw.Write(data); err != nil {
		return err
	}
	if err := zw.Close(); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(file), 0o755); err != nil {
		return err
	}

	return os.WriteFile(file, buf.Bytes(), 0o644)
}

// renderStub writes the PHP source of the stub of class c.
func renderStub(name string, c *shimbuild.Class) string {
	ns, short := splitName(name)

	var b strings.Builder
	b.WriteString("<?php\n\n// @generated by tools/shimgen from Composer 2.10.3's API; do not edit.\n")
	b.WriteString("// A presence-parity stub (docs/PLUGINS.md D7): every method throws\n")
	b.WriteString("// Maestro\\Shim\\UnsupportedApiException until the shim implements it.\n\n")
	if ns != "" {
		b.WriteString("namespace " + ns + ";\n\n")
	}

	switch c.Kind {
	case "interface":
		b.WriteString("interface " + short)
		if len(c.DirectInterfaces) > 0 {
			b.WriteString(" extends " + qualifiedList(c.DirectInterfaces))
		}
	case "trait":
		b.WriteString("trait " + short)
	default:
		if c.Abstract {
			b.WriteString("abstract ")
		}
		if c.Final {
			b.WriteString("final ")
		}
		b.WriteString("class " + short)
		if c.Parent != nil {
			b.WriteString(" extends \\" + *c.Parent)
		}
		if len(c.DirectInterfaces) > 0 {
			b.WriteString(" implements " + qualifiedList(c.DirectInterfaces))
		}
	}
	b.WriteString("\n{\n")

	var sections []string

	if len(c.Traits) > 0 {
		var s strings.Builder
		for _, t := range c.Traits {
			s.WriteString("    use \\" + t + ";\n")
		}
		sections = append(sections, s.String())
	}

	if len(c.Constants.Keys) > 0 {
		var s strings.Builder
		for _, k := range c.Constants.Keys {
			v := c.Constants.Values[k]
			s.WriteString("    " + v.Visibility + " const " + k + " = " + v.Value + ";\n")
		}
		sections = append(sections, s.String())
	}

	if len(c.Properties.Keys) > 0 {
		var s strings.Builder
		for _, k := range c.Properties.Keys {
			p := c.Properties.Values[k]
			s.WriteString("    " + p.Visibility)
			if p.Static {
				s.WriteString(" static")
			}
			if p.Type != nil {
				s.WriteString(" " + *p.Type)
			}
			s.WriteString(" $" + k)
			if p.Default != nil && (*p.Default != "null" || p.Type != nil) {
				s.WriteString(" = " + *p.Default)
			}
			s.WriteString(";\n")
		}
		sections = append(sections, s.String())
	}

	remote := remoteMethods(name, c)
	for _, k := range c.Methods.Keys {
		sections = append(sections, renderMethod(name, k, c.Methods.Values[k], c.Kind == "interface", remote[k]))
	}

	b.WriteString(strings.Join(sections, "\n"))
	b.WriteString("}\n")

	return b.String()
}

// repositoryMethods are the RepositoryInterface methods maestro serves
// for its own repositories (repo.*, internal/plugin/svc_repo.go).
var repositoryMethods = []string{"count", "findPackage", "findPackages", "getPackages", "getProviders", "getRepoName", "hasPackage", "loadPackages", "search"}

// transactionMethods are the Transaction methods maestro serves for its own
// transactions (transaction.*, internal/plugin/svc_resolverevents.go).
var transactionMethods = []string{"getOperations"}

// downloaderMethods are the downloader methods maestro serves for its own
// downloaders (downloader.*, internal/plugin/svc_downloader.go).
var downloaderMethods = []string{"getInstallationSource", "download", "prepare", "install", "update", "remove", "cleanup", "getLocalChanges", "getUnpushedChanges", "getVcsReference"}

// builtinHooks are the methods of Composer's command classes that maestro
// serves for its own commands (builtin.*, internal/plugin/svc_builtin.go):
// the hooks Symfony's Command::run() calls when PHP code runs one of the
// commands of maestro's Application ($app->find('install')->run(...)), and
// the commands' own run(), isProxyCommand() and complete() overrides.
var builtinHooks = []string{"initialize", "interact", "execute", "run", "isProxyCommand", "complete"}

// remoteMethods are the methods of a stub class whose instances may be
// maestro's (a remote repository, a transaction or a command maestro hands
// to PHP): name => the RPC method serving them on such an instance.
func remoteMethods(class string, c *shimbuild.Class) map[string]string {
	out := map[string]string{}
	if c.Kind != "class" {
		return out
	}
	if strings.HasPrefix(class, `Composer\Command\`) {
		for _, name := range builtinHooks {
			if m, ok := c.Methods.Values[name]; ok && !m.Static && !m.Abstract {
				out[name] = "builtin." + name
			}
		}

		return out
	}
	if class == `Composer\DependencyResolver\Transaction` {
		for _, name := range transactionMethods {
			if _, ok := c.Methods.Values[name]; ok {
				out[name] = "transaction." + name
			}
		}

		return out
	}
	if slices.Contains(c.Interfaces, `Composer\Downloader\DownloaderInterface`) {
		for _, name := range downloaderMethods {
			if m, ok := c.Methods.Values[name]; ok && !m.Static && !m.Abstract && m.Visibility == "public" {
				out[name] = "downloader." + name
			}
		}
		if class == `Composer\Downloader\FileDownloader` {
			// new FileDownloader(...) (and its subclasses without a
			// constructor of their own) creates maestro's downloader.
			out["__construct"] = "downloader.new"
		}

		return out
	}
	if !slices.Contains(c.Interfaces, `Composer\Repository\RepositoryInterface`) {
		return out
	}
	for _, name := range repositoryMethods {
		if m, ok := c.Methods.Values[name]; ok && !m.Static && !m.Abstract && m.Visibility == "public" {
			out[name] = "repo." + name
		}
	}

	return out
}

func renderMethod(class, name string, m *shimbuild.Method, inInterface bool, remote string) string {
	var b strings.Builder

	for _, a := range m.Attributes {
		// Attributes are comments before PHP 8, so each gets its own line.
		b.WriteString("    #[\\" + a + "]\n")
	}

	b.WriteString("    ")
	if m.Final {
		b.WriteString("final ")
	}
	if m.Abstract {
		b.WriteString("abstract ")
	}
	b.WriteString(m.Visibility + " ")
	if m.Static {
		b.WriteString("static ")
	}
	b.WriteString("function ")
	if m.ByRef {
		b.WriteString("&")
	}
	b.WriteString(name + "(")

	for i, p := range m.Params {
		if i > 0 {
			b.WriteString(", ")
		}
		if p.Type != nil {
			b.WriteString(*p.Type + " ")
		}
		if p.ByRef {
			b.WriteString("&")
		}
		if p.Variadic {
			b.WriteString("...")
		}
		b.WriteString("$" + p.Name)
		if p.Default != nil {
			b.WriteString(" = " + *p.Default)
		}
	}
	b.WriteString(")")

	if m.ReturnType != nil {
		b.WriteString(": " + *m.ReturnType)
	}

	if inInterface || m.Abstract {
		b.WriteString(";\n")

		return b.String()
	}

	b.WriteString("\n    {\n")
	switch {
	case remote != "" && name == "__construct":
		params := []string{"$this"}
		for _, p := range m.Params {
			params = append(params, "$"+p.Name)
		}
		b.WriteString("        \\Maestro\\Shim\\Rpc::call(" + php.VarExport(remote) + ", [" + strings.Join(params, ", ") + "]);\n    }\n")

		return b.String()
	case remote != "":
		var call string
		if strings.HasPrefix(remote, "builtin.") {
			// Maestro\Shim\Console::builtin() makes the input and output
			// maestro's as they cross (Console::inputValue(), outputValue()).
			params := make([]string, len(m.Params))
			for i, p := range m.Params {
				params[i] = "$" + p.Name
			}
			call = "\\Maestro\\Shim\\Console::builtin($this, " + php.VarExport(name) + ", [" + strings.Join(params, ", ") + "])"
		} else {
			params := []string{"$this"}
			for _, p := range m.Params {
				params = append(params, "$"+p.Name)
			}
			call = "\\Maestro\\Shim\\Rpc::call(" + php.VarExport(remote) + ", [" + strings.Join(params, ", ") + "])"
		}
		b.WriteString("        if (\\Maestro\\Shim\\Remote::owned($this)) {\n")
		if m.ReturnType != nil && *m.ReturnType == "void" {
			b.WriteString("            " + call + ";\n\n            return;\n")
		} else {
			b.WriteString("            return " + call + ";\n")
		}
		b.WriteString("        }\n\n")
	}
	b.WriteString("        throw new \\Maestro\\Shim\\UnsupportedApiException(" + php.VarExport("maestro does not support "+class+"::"+name+"() in plugins yet") + ");\n    }\n")

	return b.String()
}

func splitName(name string) (ns, short string) {
	i := strings.LastIndexByte(name, '\\')
	if i < 0 {
		return "", name
	}

	return name[:i], name[i+1:]
}

func qualifiedList(names []string) string {
	q := make([]string, len(names))
	for i, n := range names {
		q[i] = `\` + n
	}

	return strings.Join(q, ", ")
}
